"""Candidate objects for the 100-object batch (real style, Malonno theme).

Each row: id, what (prompt), detection size (w, h), tags, names en/it/de/es/fr.
No green objects: the grid is keyed on chroma green.
"""

C = [
    # kitchen / osteria
    ("copper_polenta_pot", "old hammered copper polenta cauldron with an iron handle, blackened bottom", (55, 55), ["metallo", "cucina", "antico", "medio"], ["Copper Polenta Pot", "Paiolo di Rame", "Kupferkessel", "Caldero de Cobre", "Chaudron en Cuivre"]),
    ("milk_churn", "old dented metal milk churn with a lid and side handles", (40, 65), ["metallo", "contenitore", "cucina", "vintage", "medio"], ["Milk Churn", "Bidone del Latte", "Milchkanne", "Lechera de Metal", "Bidon à Lait"]),
    ("wooden_milk_pail", "old wooden milk pail with iron hoops and a rope handle", (45, 50), ["legno", "contenitore", "cucina", "antico", "medio"], ["Wooden Milk Pail", "Secchio di Legno", "Holzeimer", "Cubo de Madera", "Seau en Bois"]),
    ("cast_iron_pan", "old black cast iron frying pan, rusty edges", (70, 40), ["ferro", "cucina", "vintage", "medio"], ["Cast Iron Pan", "Padella di Ghisa", "Gusseiserne Pfanne", "Sartén de Hierro", "Poêle en Fonte"]),
    ("enamel_coffee_pot", "chipped white and blue enamel coffee pot, old", (40, 50), ["metallo", "cucina", "bevanda", "vintage", "medio"], ["Enamel Coffee Pot", "Caffettiera Smaltata", "Emaille-Kaffeekanne", "Cafetera Esmaltada", "Cafetière Émaillée"]),
    ("moka_pot", "old aluminium moka coffee maker, dented and stained", (30, 45), ["metallo", "cucina", "bevanda", "vintage", "medio"], ["Moka Pot", "Moka", "Espressokocher", "Cafetera Moka", "Cafetière Moka"]),
    ("coffee_grinder_manual", "antique wooden manual coffee grinder with a brass crank", (35, 50), ["legno", "metallo", "cucina", "antico", "medio"], ["Coffee Grinder", "Macinacaffè", "Kaffeemühle", "Molinillo de Café", "Moulin à Café"]),
    ("salt_cellar_wooden", "small carved wooden salt box with a hinged lid", (35, 35), ["legno", "cucina", "contenitore", "antico", "piccolo"], ["Salt Box", "Saliera di Legno", "Salzfass", "Salero de Madera", "Boîte à Sel"]),
    ("rustic_bread_loaf", "rustic round loaf of crusty bread, flour dusted", (50, 40), ["cibo", "cucina", "medio"], ["Bread Loaf", "Pagnotta", "Brotlaib", "Hogaza de Pan", "Miche de Pain"]),
    ("hanging_salami", "cured italian salami tied with string", (20, 60), ["cibo", "cucina", "medio"], ["Salami", "Salame", "Salami", "Salami", "Saucisson"]),
    ("garlic_braid", "braid of dried white garlic bulbs", (30, 70), ["cibo", "cucina", "medio"], ["Garlic Braid", "Treccia d'Aglio", "Knoblauchzopf", "Ristra de Ajos", "Tresse d'Ail"]),
    ("straw_wine_flask", "old straw wrapped wine flask, dusty glass", (35, 65), ["vetro", "bevanda", "bar", "vintage", "medio"], ["Straw Wine Flask", "Fiasco Impagliato", "Strohflasche", "Frasco de Paja", "Fiasque Paillée"]),
    ("ceramic_wine_jug", "rustic terracotta wine jug with a handle, glazed and chipped", (40, 50), ["ceramica", "bevanda", "bar", "antico", "medio"], ["Wine Jug", "Brocca del Vino", "Weinkrug", "Jarra de Vino", "Pichet à Vin"]),
    ("pewter_goblet", "old pewter goblet, dull and scratched", (25, 45), ["metallo", "bevanda", "antico", "medio"], ["Pewter Goblet", "Calice di Peltro", "Zinnkelch", "Copa de Peltre", "Gobelet en Étain"]),
    ("carved_wooden_spoon", "hand carved wooden spoon, worn", (15, 60), ["legno", "cucina", "piccolo"], ["Wooden Spoon", "Cucchiaio di Legno", "Holzlöffel", "Cuchara de Madera", "Cuillère en Bois"]),
    ("rolling_pin", "old wooden rolling pin with handles, flour stains", (70, 18), ["legno", "cucina", "medio"], ["Rolling Pin", "Mattarello", "Nudelholz", "Rodillo", "Rouleau à Pâtisserie"]),
    ("butter_mold", "antique carved wooden butter mold stamp with a flower pattern", (35, 40), ["legno", "cucina", "antico", "piccolo"], ["Butter Mold", "Stampo per Burro", "Butterform", "Molde de Mantequilla", "Moule à Beurre"]),
    ("honey_jar", "glass jar of golden honey with a cloth lid tied with string", (30, 40), ["vetro", "cibo", "cucina", "piccolo"], ["Honey Jar", "Vasetto di Miele", "Honigglas", "Tarro de Miel", "Pot de Miel"]),
    ("chestnut_roasting_pan", "old iron chestnut roasting pan with holes and a long handle", (75, 35), ["ferro", "cucina", "antico", "medio"], ["Chestnut Pan", "Padella per Castagne", "Maronenpfanne", "Sartén de Castañas", "Poêle à Châtaignes"]),
    ("corkscrew_antique", "antique wooden handle corkscrew", (35, 45), ["metallo", "legno", "bar", "antico", "piccolo"], ["Corkscrew", "Cavatappi", "Korkenzieher", "Sacacorchos", "Tire-bouchon"]),
    # home
    ("iron_candlestick", "wrought iron candlestick with a burnt down candle", (25, 55), ["ferro", "luce", "antico", "medio"], ["Iron Candlestick", "Candeliere di Ferro", "Eiserner Kerzenhalter", "Candelabro de Hierro", "Bougeoir en Fer"]),
    ("brass_bed_warmer", "antique brass bed warming pan with a long wooden handle", (40, 80), ["ottone", "legno", "arredamento", "antico", "grande"], ["Bed Warmer", "Scaldaletto", "Bettwärmer", "Calentador de Cama", "Bassinoire"]),
    ("charcoal_clothes_iron", "antique cast iron charcoal clothes iron with a wooden handle", (45, 40), ["ferro", "arredamento", "antico", "medio"], ["Charcoal Iron", "Ferro da Stiro a Carbone", "Kohlebügeleisen", "Plancha de Carbón", "Fer à Repasser à Charbon"]),
    ("washboard", "old wooden washboard with a corrugated metal panel", (40, 65), ["legno", "metallo", "bagno", "vintage", "medio"], ["Washboard", "Asse per Lavare", "Waschbrett", "Tabla de Lavar", "Planche à Laver"]),
    ("wooden_thread_spool", "old wooden thread spool with faded red thread", (20, 25), ["legno", "stoffa", "piccolo"], ["Thread Spool", "Rocchetto di Filo", "Garnspule", "Carrete de Hilo", "Bobine de Fil"]),
    ("pin_cushion", "old red velvet pin cushion with pins", (30, 25), ["stoffa", "metallo", "piccolo"], ["Pin Cushion", "Puntaspilli", "Nadelkissen", "Acerico", "Pelote à Épingles"]),
    ("wool_ball_needles", "ball of grey wool yarn with two knitting needles", (40, 35), ["stoffa", "medio"], ["Wool and Needles", "Gomitolo con Ferri", "Wollknäuel", "Ovillo de Lana", "Pelote de Laine"]),
    ("antique_scissors", "old iron sewing scissors, ornate handles", (25, 50), ["ferro", "metallo", "antico", "piccolo"], ["Antique Scissors", "Forbici Antiche", "Alte Schere", "Tijeras Antiguas", "Ciseaux Anciens"]),
    ("chamber_pot", "old white enamel chamber pot with a handle, chipped", (45, 35), ["metallo", "bagno", "vintage", "medio"], ["Chamber Pot", "Vaso da Notte", "Nachttopf", "Orinal", "Pot de Chambre"]),
    ("hot_water_bottle", "old red rubber hot water bottle", (35, 50), ["plastica", "bagno", "vintage", "medio"], ["Hot Water Bottle", "Borsa dell'Acqua Calda", "Wärmflasche", "Bolsa de Agua Caliente", "Bouillotte"]),
    ("lace_doily", "round white crocheted lace doily", (45, 45), ["stoffa", "arredamento", "vintage", "medio"], ["Lace Doily", "Centrino", "Spitzendeckchen", "Tapete de Encaje", "Napperon"]),
    ("embroidery_hoop", "wooden embroidery hoop with an unfinished floral embroidery", (45, 45), ["legno", "stoffa", "arte", "medio"], ["Embroidery Hoop", "Telaio da Ricamo", "Stickrahmen", "Bastidor de Bordado", "Tambour à Broder"]),
    ("hand_mirror_brass", "antique brass hand mirror with a cracked glass", (30, 55), ["ottone", "vetro", "bellezza", "antico", "medio"], ["Hand Mirror", "Specchietto", "Handspiegel", "Espejo de Mano", "Miroir à Main"]),
    ("folding_hand_fan", "antique folding hand fan, faded painted paper", (60, 35), ["carta", "legno", "accessorio", "antico", "medio"], ["Hand Fan", "Ventaglio", "Fächer", "Abanico", "Éventail"]),
    ("tortoiseshell_comb", "old tortoiseshell hair comb", (40, 18), ["plastica", "bellezza", "vintage", "piccolo"], ["Hair Comb", "Pettine", "Haarkamm", "Peine", "Peigne"]),
    ("shaving_brush", "old shaving brush with a bone handle", (20, 40), ["bellezza", "bagno", "vintage", "piccolo"], ["Shaving Brush", "Pennello da Barba", "Rasierpinsel", "Brocha de Afeitar", "Blaireau"]),
    ("straight_razor", "antique folding straight razor, open, bone handle", (60, 20), ["metallo", "bellezza", "antico", "medio"], ["Straight Razor", "Rasoio", "Rasiermesser", "Navaja de Afeitar", "Rasoir"]),
    ("door_hinge_rusty", "old rusty iron door hinge with nails", (45, 30), ["ferro", "arredamento", "antico", "medio"], ["Rusty Hinge", "Cardine Arrugginito", "Rostiges Scharnier", "Bisagra Oxidada", "Charnière Rouillée"]),
    ("iron_door_handle", "old wrought iron ring door handle on a plate", (35, 45), ["ferro", "arredamento", "antico", "medio"], ["Door Handle", "Maniglia di Ferro", "Türgriff", "Tirador de Hierro", "Poignée de Porte"]),
    ("brass_door_bell", "old brass door bell with a pull handle", (30, 45), ["ottone", "arredamento", "antico", "medio"], ["Door Bell", "Campanello da Porta", "Türglocke", "Campanilla", "Sonnette"]),
    # farm and tools
    ("sheep_shears", "old iron sheep shears", (25, 60), ["ferro", "attrezzo", "antico", "medio"], ["Sheep Shears", "Cesoie da Tosatura", "Schafschere", "Tijeras de Esquilar", "Forces à Mouton"]),
    ("milking_stool", "small three legged wooden milking stool, worn", (45, 40), ["legno", "arredamento", "antico", "medio"], ["Milking Stool", "Sgabello da Mungitura", "Melkschemel", "Taburete de Ordeño", "Tabouret de Traite"]),
    ("horseshoe_rusty", "old rusty horseshoe with nails", (35, 35), ["ferro", "antico", "piccolo"], ["Horseshoe", "Ferro di Cavallo", "Hufeisen", "Herradura", "Fer à Cheval"]),
    ("crosscut_saw", "old two man crosscut lumberjack saw with wooden handles", (90, 25), ["metallo", "legno", "attrezzo", "antico", "grande"], ["Crosscut Saw", "Sega da Boscaiolo", "Zugsäge", "Tronzador", "Passe-partout"]),
    ("wooden_mallet", "old wooden carpenter mallet, worn", (35, 55), ["legno", "attrezzo", "medio"], ["Wooden Mallet", "Mazzuolo", "Holzhammer", "Mazo de Madera", "Maillet"]),
    ("hand_drill_brace", "antique carpenter brace hand drill, wood and iron", (60, 40), ["legno", "ferro", "attrezzo", "antico", "medio"], ["Brace Drill", "Trapano a Manovella", "Bohrwinde", "Berbiquí", "Vilebrequin"]),
    ("wood_plane", "old wooden hand plane with an iron blade", (55, 25), ["legno", "attrezzo", "antico", "medio"], ["Wood Plane", "Pialla", "Hobel", "Cepillo de Carpintero", "Rabot"]),
    ("folding_ruler", "old wooden folding carpenter ruler, partly open", (60, 20), ["legno", "attrezzo", "vintage", "medio"], ["Folding Ruler", "Metro Pieghevole", "Zollstock", "Metro Plegable", "Mètre Pliant"]),
    ("oil_can_small", "small old metal oil can with a long spout", (40, 40), ["metallo", "attrezzo", "vintage", "medio"], ["Oil Can", "Oliatore", "Ölkännchen", "Aceitera", "Burette d'Huile"]),
    ("nails_jar", "old glass jar full of rusty nails", (30, 40), ["vetro", "ferro", "attrezzo", "piccolo"], ["Jar of Nails", "Barattolo di Chiodi", "Nagelglas", "Tarro de Clavos", "Bocal de Clous"]),
    ("hatchet_old", "old hatchet with a worn wooden handle and a rusty head", (40, 60), ["ferro", "legno", "attrezzo", "antico", "medio"], ["Hatchet", "Accetta", "Beil", "Hacha de Mano", "Hachette"]),
    ("iron_wedge", "old iron log splitting wedge, battered", (25, 40), ["ferro", "attrezzo", "piccolo"], ["Iron Wedge", "Cuneo di Ferro", "Spaltkeil", "Cuña de Hierro", "Coin en Fer"]),
    ("butter_churn", "old wooden butter churn with a plunger", (40, 80), ["legno", "cucina", "antico", "grande"], ["Butter Churn", "Zangola", "Butterfass", "Mantequera", "Baratte"]),
    ("mushroom_basket", "wicker basket full of porcini mushrooms", (55, 45), ["cibo", "legno", "medio"], ["Mushroom Basket", "Cesto di Funghi", "Pilzkorb", "Cesta de Setas", "Panier de Champignons"]),
    ("pine_cone", "large brown pine cone", (30, 40), ["natura", "piccolo"], ["Pine Cone", "Pigna", "Kiefernzapfen", "Piña", "Pomme de Pin"]),
    ("deer_antler", "shed deer antler, weathered", (60, 55), ["osso", "natura", "medio"], ["Deer Antler", "Palco di Cervo", "Hirschgeweih", "Asta de Ciervo", "Bois de Cerf"]),
    ("bird_skull", "small bird skull, bleached bone", (25, 25), ["osso", "horror", "piccolo"], ["Bird Skull", "Teschio di Uccello", "Vogelschädel", "Cráneo de Pájaro", "Crâne d'Oiseau"]),
    # hunting and mountain
    ("hunting_horn", "old brass hunting horn with a leather strap", (55, 40), ["ottone", "cuoio", "antico", "medio"], ["Hunting Horn", "Corno da Caccia", "Jagdhorn", "Cuerno de Caza", "Cor de Chasse"]),
    ("duck_decoy", "old painted wooden duck decoy, faded and chipped", (55, 30), ["legno", "decorazione", "vintage", "medio"], ["Duck Decoy", "Anatra da Richiamo", "Lockente", "Señuelo de Pato", "Appelant"]),
    ("leghold_trap", "old rusty steel leghold animal trap, open jaws", (60, 40), ["ferro", "horror", "antico", "medio"], ["Leghold Trap", "Tagliola", "Tellereisen", "Cepo", "Piège à Mâchoires"]),
    ("cartridge_belt", "old leather cartridge belt with brass shotgun shells", (70, 25), ["cuoio", "ottone", "militare", "vintage", "medio"], ["Cartridge Belt", "Cartucciera", "Patronengurt", "Canana", "Cartouchière"]),
    ("alpine_hat", "italian alpine troops felt hat with a black feather", (55, 40), ["abbigliamento", "cappello", "militare", "medio"], ["Alpine Hat", "Cappello Alpino", "Alpinihut", "Sombrero Alpino", "Chapeau Alpin"]),
    ("wool_mittens", "pair of grey hand knitted wool mittens", (45, 40), ["stoffa", "abbigliamento", "medio"], ["Wool Mittens", "Muffole di Lana", "Fäustlinge", "Manoplas de Lana", "Moufles"]),
    ("wooden_snowshoes", "pair of old wooden snowshoes with leather laces", (50, 80), ["legno", "cuoio", "montagna", "sport", "grande"], ["Snowshoes", "Ciaspole", "Schneeschuhe", "Raquetas de Nieve", "Raquettes"]),
    ("wooden_sled", "small old wooden sled with iron runners", (80, 45), ["legno", "ferro", "montagna", "vintage", "grande"], ["Wooden Sled", "Slittino di Legno", "Holzschlitten", "Trineo de Madera", "Luge en Bois"]),
    ("alpenstock", "old wooden alpenstock walking staff with an iron tip", (15, 90), ["legno", "montagna", "attrezzatura", "antico", "grande"], ["Alpenstock", "Bastone da Montagna", "Bergstock", "Bastón Alpino", "Alpenstock"]),
    ("wooden_skis", "pair of vintage wooden skis with leather bindings", (30, 95), ["legno", "montagna", "sport", "vintage", "grande"], ["Wooden Skis", "Sci di Legno", "Holzski", "Esquís de Madera", "Skis en Bois"]),
    ("carbide_lamp", "old brass miner carbide lamp", (30, 45), ["ottone", "luce", "vintage", "medio"], ["Carbide Lamp", "Lampada a Carburo", "Karbidlampe", "Lámpara de Carburo", "Lampe à Carbure"]),
    # military
    ("mess_tin", "old military aluminium mess tin with a folding handle", (50, 35), ["metallo", "militare", "cucina", "vintage", "medio"], ["Mess Tin", "Gavetta", "Kochgeschirr", "Fiambrera Militar", "Gamelle"]),
    ("ww1_helmet", "old world war one steel helmet, rusty and dented", (55, 40), ["metallo", "militare", "antico", "medio"], ["Army Helmet", "Elmetto", "Stahlhelm", "Casco Militar", "Casque"]),
    ("bayonet", "old bayonet with a scabbard", (15, 75), ["metallo", "arma", "militare", "antico", "medio"], ["Bayonet", "Baionetta", "Bajonett", "Bayoneta", "Baïonnette"]),
    ("military_canteen", "old military canteen covered in brown felt with a cork", (35, 50), ["metallo", "stoffa", "militare", "bevanda", "medio"], ["Canteen", "Borraccia Militare", "Feldflasche", "Cantimplora", "Gourde Militaire"]),
    ("field_telephone", "old military field telephone in a wooden box with a crank", (55, 45), ["legno", "militare", "tecnologia", "antico", "medio"], ["Field Telephone", "Telefono da Campo", "Feldtelefon", "Teléfono de Campaña", "Téléphone de Campagne"]),
    ("folded_old_map", "old folded paper topographic map, worn creases", (55, 40), ["carta", "viaggio", "vintage", "medio"], ["Old Map", "Mappa Piegata", "Alte Landkarte", "Mapa Antiguo", "Vieille Carte"]),
    ("dog_tags", "old metal military dog tags on a chain", (25, 40), ["metallo", "militare", "vintage", "piccolo"], ["Dog Tags", "Piastrine", "Erkennungsmarken", "Placas", "Plaques d'Identité"]),
    # church and cemetery
    ("prayer_book", "old leather prayer book with gold cross and worn edges", (35, 45), ["carta", "cuoio", "religione", "antico", "medio"], ["Prayer Book", "Libro di Preghiere", "Gebetbuch", "Devocionario", "Missel"]),
    ("holy_water_font", "small ceramic holy water font with a cross", (30, 40), ["ceramica", "religione", "antico", "piccolo"], ["Holy Water Font", "Acquasantiera", "Weihwasserbecken", "Pila de Agua Bendita", "Bénitier"]),
    ("censer", "old brass church censer on chains", (35, 65), ["ottone", "religione", "antico", "medio"], ["Censer", "Turibolo", "Weihrauchfass", "Incensario", "Encensoir"]),
    ("votive_heart", "silver ex voto heart plaque, tarnished", (30, 35), ["metallo", "religione", "antico", "piccolo"], ["Votive Heart", "Ex Voto", "Votivherz", "Exvoto", "Ex-voto"]),
    ("saint_statuette", "small old painted plaster statue of a saint, chipped paint", (25, 60), ["ceramica", "religione", "antico", "medio"], ["Saint Statuette", "Statuetta di Santo", "Heiligenfigur", "Estatuilla de Santo", "Statuette de Saint"]),
    ("grave_lantern", "old red glass cemetery grave candle lantern with a metal lid", (25, 40), ["vetro", "metallo", "luce", "horror", "piccolo"], ["Grave Lantern", "Lumino Cimiteriale", "Grablicht", "Farolillo de Tumba", "Lumignon"]),
    ("church_bell_small", "small old bronze church hand bell with a wooden handle", (30, 45), ["metallo", "religione", "antico", "medio"], ["Hand Bell", "Campanella", "Handglocke", "Campanilla de Mano", "Clochette"]),
    # school, post and study
    ("sepia_portrait_photo", "old sepia portrait photograph of a family on a card mount, bent", (40, 55), ["carta", "foto", "antico", "medio"], ["Old Portrait", "Foto Seppia", "Altes Porträt", "Retrato Sepia", "Portrait Sépia"]),
    ("fountain_pen", "old black fountain pen with a gold nib", (60, 12), ["plastica", "metallo", "ufficio", "vintage", "medio"], ["Fountain Pen", "Penna Stilografica", "Füllfederhalter", "Pluma Estilográfica", "Stylo-plume"]),
    ("wax_seal_stamp", "antique brass wax seal stamp with a wooden handle and a red wax stick", (40, 40), ["ottone", "legno", "ufficio", "antico", "piccolo"], ["Wax Seal", "Sigillo di Ceralacca", "Siegelstempel", "Sello de Lacre", "Cachet de Cire"]),
    ("letter_opener", "antique brass letter opener", (60, 12), ["ottone", "ufficio", "antico", "medio"], ["Letter Opener", "Tagliacarte", "Brieföffner", "Abrecartas", "Coupe-papier"]),
    ("postal_scale", "old brass postal letter scale", (45, 40), ["ottone", "bilancia", "ufficio", "antico", "medio"], ["Postal Scale", "Bilancia Postale", "Briefwaage", "Balanza Postal", "Pèse-lettre"]),
    ("school_slate", "old school writing slate in a wooden frame with chalk scribbles", (50, 40), ["legno", "studio", "antico", "medio"], ["School Slate", "Lavagnetta", "Schiefertafel", "Pizarra Escolar", "Ardoise"]),
    ("abacus_wooden", "old wooden counting abacus with red and white beads", (55, 40), ["legno", "studio", "vintage", "medio"], ["Abacus", "Pallottoliere", "Rechenschieber", "Ábaco", "Boulier"]),
    ("leather_satchel", "old worn brown leather school satchel with buckles", (55, 45), ["cuoio", "studio", "vintage", "medio"], ["School Satchel", "Cartella di Cuoio", "Schulranzen", "Cartera Escolar", "Cartable"]),
    ("old_globe", "old small desk globe with faded sepia map", (45, 55), ["carta", "legno", "studio", "antico", "medio"], ["Old Globe", "Mappamondo", "Globus", "Globo Terráqueo", "Globe Terrestre"]),
    # toys and games
    ("tin_soldier", "old painted tin toy soldier, chipped red coat", (20, 45), ["metallo", "giocattolo", "vintage", "piccolo"], ["Tin Soldier", "Soldatino di Latta", "Zinnsoldat", "Soldadito de Plomo", "Soldat de Plomb"]),
    ("spinning_top", "old painted wooden spinning top with string", (30, 35), ["legno", "giocattolo", "vintage", "piccolo"], ["Spinning Top", "Trottola", "Kreisel", "Peonza", "Toupie"]),
    ("rag_doll", "old handmade rag doll with button eyes, worn", (35, 60), ["stoffa", "giocattolo", "horror", "vintage", "medio"], ["Rag Doll", "Bambola di Pezza", "Stoffpuppe", "Muñeca de Trapo", "Poupée de Chiffon"]),
    ("marbles_bag", "small cloth bag spilling colourful glass marbles", (40, 35), ["vetro", "stoffa", "giocattolo", "vintage", "piccolo"], ["Marbles", "Sacchetto di Biglie", "Murmeln", "Bolsa de Canicas", "Billes"]),
    ("music_box", "antique wooden music box with an open lid and a brass mechanism", (45, 40), ["legno", "musica", "antico", "medio"], ["Music Box", "Carillon", "Spieldose", "Caja de Música", "Boîte à Musique"]),
    ("napoletane_cards", "fanned deck of old italian playing cards, worn", (50, 40), ["carta", "gioco", "vintage", "medio"], ["Playing Cards", "Carte Napoletane", "Spielkarten", "Naipes", "Cartes à Jouer"]),
    ("bone_dice", "pair of old bone dice", (25, 20), ["osso", "gioco", "antico", "piccolo"], ["Bone Dice", "Dadi d'Osso", "Knochenwürfel", "Dados de Hueso", "Dés en Os"]),
    # smoking and pocket
    ("cigarette_case", "old engraved silver cigarette case, closed", (40, 30), ["argento", "metallo", "accessorio", "vintage", "piccolo"], ["Cigarette Case", "Portasigarette", "Zigarettenetui", "Pitillera", "Étui à Cigarettes"]),
    ("cigar_box", "old wooden cigar box with a faded paper label", (55, 30), ["legno", "carta", "contenitore", "vintage", "medio"], ["Cigar Box", "Scatola di Sigari", "Zigarrenkiste", "Caja de Puros", "Boîte à Cigares"]),
    ("petrol_lighter", "old brass petrol lighter, scratched", (20, 30), ["ottone", "accessorio", "vintage", "piccolo"], ["Petrol Lighter", "Accendino a Benzina", "Benzinfeuerzeug", "Encendedor de Gasolina", "Briquet à Essence"]),
    ("snuff_box", "small antique silver snuff box with an engraved lid", (30, 25), ["argento", "contenitore", "antico", "piccolo"], ["Snuff Box", "Tabacchiera", "Schnupftabakdose", "Tabaquera", "Tabatière"]),
    ("pocket_knife", "old folding pocket knife with a wooden handle, open blade", (55, 18), ["metallo", "legno", "attrezzo", "vintage", "medio"], ["Pocket Knife", "Coltellino", "Taschenmesser", "Navaja", "Canif"]),
    ("walking_cane", "old wooden walking cane with a silver handle", (15, 90), ["legno", "argento", "accessorio", "antico", "grande"], ["Walking Cane", "Bastone da Passeggio", "Spazierstock", "Bastón", "Canne"]),
    # pharmacy
    ("albarello_jar", "antique painted ceramic pharmacy albarello jar with a lid", (35, 50), ["ceramica", "medicina", "antico", "medio"], ["Apothecary Jar", "Vaso da Farmacia", "Apothekergefäß", "Bote de Botica", "Pot à Pharmacie"]),
    ("mortar_pestle_brass", "old brass mortar and pestle", (40, 40), ["ottone", "medicina", "cucina", "antico", "medio"], ["Mortar and Pestle", "Mortaio", "Mörser", "Mortero", "Mortier"]),
    ("brown_medicine_vial", "small old brown glass medicine vial with a cork", (15, 35), ["vetro", "medicina", "vintage", "piccolo"], ["Medicine Vial", "Fialetta", "Arzneifläschchen", "Frasco de Medicina", "Fiole"]),
    ("stethoscope_old", "old stethoscope with rubber tubes, worn", (50, 50), ["metallo", "medicina", "vintage", "medio"], ["Stethoscope", "Stetoscopio", "Stethoskop", "Estetoscopio", "Stéthoscope"]),
    # added after the duplicate check
    ("wooden_clogs", "pair of old carved wooden clogs, worn", (55, 35), ["legno", "abbigliamento", "antico", "medio"], ["Wooden Clogs", "Zoccoli di Legno", "Holzschuhe", "Zuecos", "Sabots"]),
    ("brass_scale_weights", "set of old brass scale weights in a wooden block", (45, 35), ["ottone", "bilancia", "antico", "medio"], ["Scale Weights", "Pesi d'Ottone", "Messinggewichte", "Pesas de Latón", "Poids en Laiton"]),
    ("iron_kettle", "old black cast iron kettle with a handle, soot stained", (45, 45), ["ferro", "cucina", "antico", "medio"], ["Iron Kettle", "Bollitore di Ferro", "Eisenkessel", "Tetera de Hierro", "Bouilloire en Fonte"]),
    ("enamel_mug", "chipped white enamel mug with a blue rim", (30, 30), ["metallo", "cucina", "bevanda", "vintage", "piccolo"], ["Enamel Mug", "Tazza Smaltata", "Emaillebecher", "Taza Esmaltada", "Tasse Émaillée"]),
    ("wooden_bowl", "old hand turned wooden bowl, cracked", (45, 25), ["legno", "cucina", "antico", "medio"], ["Wooden Bowl", "Ciotola di Legno", "Holzschale", "Cuenco de Madera", "Bol en Bois"]),
    ("candle_snuffer", "antique brass candle snuffer with a long handle", (20, 55), ["ottone", "luce", "antico", "piccolo"], ["Candle Snuffer", "Spegnimoccolo", "Kerzenlöscher", "Apagavelas", "Éteignoir"]),
    ("ocarina", "old terracotta ocarina", (40, 30), ["ceramica", "musica", "antico", "piccolo"], ["Ocarina", "Ocarina", "Okarina", "Ocarina", "Ocarina"]),
    ("mandolin", "old wooden mandolin with a rounded back, worn varnish", (40, 85), ["legno", "musica", "antico", "grande"], ["Mandolin", "Mandolino", "Mandoline", "Mandolina", "Mandoline"]),
    ("rusty_chain", "coil of old rusty iron chain", (45, 40), ["ferro", "horror", "medio"], ["Rusty Chain", "Catena Arrugginita", "Rostige Kette", "Cadena Oxidada", "Chaîne Rouillée"]),
    ("small_wooden_barrel", "small old wooden barrel with iron hoops and a tap", (45, 50), ["legno", "ferro", "contenitore", "bar", "medio"], ["Small Barrel", "Botticella", "Kleines Fass", "Barril Pequeño", "Tonnelet"]),
    ("glass_milk_bottle", "old glass milk bottle with a foil cap, empty", (20, 45), ["vetro", "bevanda", "vintage", "piccolo"], ["Milk Bottle", "Bottiglia del Latte", "Milchflasche", "Botella de Leche", "Bouteille de Lait"]),
    ("wooden_birdhouse", "old weathered wooden birdhouse with a round hole", (40, 50), ["legno", "natura", "vintage", "medio"], ["Birdhouse", "Casetta per Uccelli", "Vogelhaus", "Casita para Pájaros", "Nichoir"]),
    ("flour_sieve", "old round wooden flour sieve with a mesh", (50, 30), ["legno", "cucina", "antico", "medio"], ["Flour Sieve", "Setaccio", "Mehlsieb", "Tamiz", "Tamis"]),
    ("fireplace_tongs", "old wrought iron fireplace tongs", (20, 75), ["ferro", "arredamento", "antico", "medio"], ["Fire Tongs", "Molle del Camino", "Kaminzange", "Tenazas de Chimenea", "Pincettes"]),
    ("fireplace_bellows", "old wooden and leather fireplace bellows", (40, 70), ["legno", "cuoio", "arredamento", "antico", "medio"], ["Bellows", "Soffietto", "Blasebalg", "Fuelle", "Soufflet"]),
    ("coin_purse", "old worn leather coin purse with a metal clasp, coins spilling", (40, 30), ["cuoio", "accessorio", "vintage", "piccolo"], ["Coin Purse", "Borsellino", "Geldbörse", "Monedero", "Porte-monnaie"]),
    ("brass_inkstand", "antique brass inkstand with two glass inkwells", (50, 30), ["ottone", "vetro", "ufficio", "antico", "medio"], ["Inkstand", "Calamaio d'Ottone", "Tintenfass", "Tintero", "Encrier"]),
    ("old_ledger", "old thick leather ledger book, worn corners", (45, 55), ["carta", "cuoio", "libro", "ufficio", "antico", "medio"], ["Old Ledger", "Registro Antico", "Altes Kassenbuch", "Libro de Cuentas", "Registre Ancien"]),
    ("zither", "old wooden zither with strings", (70, 40), ["legno", "musica", "antico", "medio"], ["Zither", "Cetra", "Zither", "Cítara", "Cithare"]),
]
DROP = {"moka_pot", "honey_jar", "rolling_pin", "charcoal_clothes_iron", "antique_scissors",
        "tortoiseshell_comb", "straight_razor", "bird_skull", "pine_cone", "leghold_trap",
        "military_canteen", "fountain_pen", "wood_plane", "old_globe", "tin_soldier", "bone_dice",
        "petrol_lighter", "stethoscope_old", "hanging_salami", "albarello_jar",
        "copper_polenta_pot", "cast_iron_pan"}
C = [c for c in C if c[0] not in DROP][:100]
