"""400-object batch, part D (100): clothing, accessories, science, nature, fantasy,
horror, history, military, medicine, vehicles."""

_ROWS = [
    ("fedora_black", "black felt fedora hat", (50, 30), ["abbigliamento", "cappello", "medio"], "Black Fedora", "Fedora Nero", "Schwarzer Hut", "Fedora Negro", "Feutre Noir"),
    ("cowboy_boots", "pair of brown cowboy boots", (50, 50), ["cuoio", "abbigliamento", "medio"], "Cowboy Boots", "Stivali da Cowboy", "Cowboystiefel", "Botas Vaqueras", "Bottes de Cowboy"),
    ("ballet_shoes", "pair of pink ballet slippers", (40, 30), ["stoffa", "abbigliamento", "piccolo"], "Ballet Shoes", "Scarpette da Danza", "Ballettschuhe", "Zapatillas de Ballet", "Chaussons de Danse"),
    ("wooden_clogs_painted", "pair of painted wooden clogs", (50, 30), ["legno", "abbigliamento", "piccolo"], "Painted Clogs", "Zoccoli Dipinti", "Bemalte Holzschuhe", "Zuecos Pintados", "Sabots Peints"),
    ("leather_gloves_black", "pair of black leather gloves", (40, 35), ["cuoio", "abbigliamento", "piccolo"], "Black Gloves", "Guanti Neri", "Schwarze Handschuhe", "Guantes Negros", "Gants Noirs"),
    ("wool_scarf_plaid", "plaid wool scarf, folded", (40, 30), ["stoffa", "abbigliamento", "piccolo"], "Plaid Scarf", "Sciarpa Scozzese", "Karoschal", "Bufanda Escocesa", "Écharpe à Carreaux"),
    ("bow_tie_red", "red bow tie", (35, 18), ["stoffa", "abbigliamento", "piccolo"], "Red Bow Tie", "Papillon Rosso", "Rote Fliege", "Pajarita Roja", "Nœud Rouge"),
    ("pocket_square", "folded silk pocket square", (25, 20), ["stoffa", "accessorio", "piccolo"], "Pocket Square", "Pochette da Giacca", "Einstecktuch", "Pañuelo de Bolsillo", "Pochette"),
    ("suspenders_red", "red suspenders", (35, 50), ["stoffa", "abbigliamento", "piccolo"], "Suspenders", "Bretelle Rosse", "Hosenträger", "Tirantes", "Bretelles"),
    ("apron_kitchen", "striped kitchen apron", (40, 55), ["stoffa", "cucina", "medio"], "Apron", "Grembiule", "Schürze", "Delantal", "Tablier"),
    ("chef_hat_white", "white chef toque hat", (35, 45), ["stoffa", "cappello", "cucina", "piccolo"], "Chef Hat", "Cappello da Cuoco", "Kochmütze", "Gorro de Chef", "Toque"),
    ("pilot_cap", "pilot captain cap", (45, 30), ["stoffa", "cappello", "viaggio", "medio"], "Pilot Cap", "Berretto da Pilota", "Pilotenmütze", "Gorra de Piloto", "Casquette de Pilote"),
    ("sailor_hat", "white sailor hat", (40, 20), ["stoffa", "cappello", "piccolo"], "Sailor Hat", "Cappello da Marinaio", "Matrosenmütze", "Gorra de Marinero", "Bonnet de Marin"),
    ("helmet_knight", "medieval knight helmet", (40, 45), ["metallo", "antico", "medio"], "Knight Helmet", "Elmo da Cavaliere", "Ritterhelm", "Yelmo", "Heaume"),
    ("viking_helmet", "horned viking helmet", (45, 40), ["metallo", "antico", "medio"], "Viking Helmet", "Elmo Vichingo", "Wikingerhelm", "Casco Vikingo", "Casque Viking"),
    ("roman_helmet", "roman legionary helmet", (40, 40), ["metallo", "antico", "medio"], "Roman Helmet", "Elmo Romano", "Römerhelm", "Casco Romano", "Casque Romain"),
    ("samurai_mask", "samurai face armour mask", (35, 35), ["metallo", "antico", "piccolo"], "Samurai Mask", "Maschera Samurai", "Samuraimaske", "Máscara Samurái", "Masque de Samouraï"),
    ("sword_medieval", "medieval longsword", (15, 90), ["metallo", "arma", "antico", "grande"], "Longsword", "Spada Medievale", "Langschwert", "Espada Medieval", "Épée Médiévale"),
    ("katana_sheath", "katana in a black sheath", (12, 90), ["metallo", "arma", "antico", "grande"], "Katana", "Katana", "Katana", "Katana", "Katana"),
    ("axe_battle", "double headed battle axe", (40, 80), ["metallo", "arma", "antico", "grande"], "Battle Axe", "Ascia da Guerra", "Streitaxt", "Hacha de Guerra", "Hache de Guerre"),
    ("bow_arrows", "wooden bow with arrows", (35, 80), ["legno", "arma", "antico", "grande"], "Bow and Arrows", "Arco e Frecce", "Pfeil und Bogen", "Arco y Flechas", "Arc et Flèches"),
    ("crossbow", "wooden crossbow", (60, 40), ["legno", "arma", "antico", "medio"], "Crossbow", "Balestra", "Armbrust", "Ballesta", "Arbalète"),
    ("shield_round_wood", "round wooden shield with an iron boss", (50, 50), ["legno", "arma", "antico", "medio"], "Round Shield", "Scudo Rotondo", "Rundschild", "Escudo Redondo", "Bouclier Rond"),
    ("mace_spiked", "spiked iron mace", (25, 60), ["ferro", "arma", "antico", "medio"], "Mace", "Mazza Ferrata", "Streitkolben", "Maza", "Masse d'Armes"),
    ("cannonball", "iron cannonball", (25, 25), ["ferro", "arma", "antico", "piccolo"], "Cannonball", "Palla di Cannone", "Kanonenkugel", "Bala de Cañón", "Boulet"),
    ("musket_old", "old flintlock musket", (90, 20), ["legno", "arma", "antico", "grande"], "Musket", "Moschetto", "Muskete", "Mosquete", "Mousquet"),
    ("powder_horn", "old gunpowder horn", (40, 25), ["osso", "arma", "antico", "piccolo"], "Powder Horn", "Fiaschetta della Polvere", "Pulverhorn", "Polvorera", "Poire à Poudre"),
    ("military_compass", "military lensatic compass", (30, 35), ["metallo", "militare", "piccolo"], "Army Compass", "Bussola Militare", "Marschkompass", "Brújula Militar", "Boussole Militaire"),
    ("ammo_crate", "wooden ammunition crate, stencils unreadable", (55, 35), ["legno", "militare", "contenitore", "medio"], "Ammo Crate", "Cassa di Munizioni", "Munitionskiste", "Caja de Munición", "Caisse de Munitions"),
    ("gas_mask_green_free", "grey military gas mask", (35, 40), ["plastica", "militare", "piccolo"], "Gas Mask", "Maschera Antigas", "Gasmaske", "Máscara de Gas", "Masque à Gaz"),
    ("army_helmet_modern", "modern tan military helmet", (40, 30), ["metallo", "militare", "medio"], "Combat Helmet", "Elmetto da Combattimento", "Gefechtshelm", "Casco de Combate", "Casque de Combat"),
    ("parachute_pack", "parachute backpack", (40, 45), ["stoffa", "militare", "medio"], "Parachute", "Paracadute", "Fallschirm", "Paracaídas", "Parachute"),
    ("radio_field_modern", "military field radio", (40, 40), ["metallo", "militare", "tecnologia", "medio"], "Field Radio", "Radio da Campo", "Feldfunkgerät", "Radio de Campaña", "Radio de Campagne"),
    ("stethoscope_modern", "modern stethoscope", (40, 40), ["metallo", "medicina", "piccolo"], "Stethoscope", "Stetoscopio", "Stethoskop", "Estetoscopio", "Stéthoscope"),
    ("blood_pressure_cuff", "blood pressure monitor cuff", (40, 35), ["plastica", "medicina", "piccolo"], "BP Monitor", "Misuratore di Pressione", "Blutdruckmesser", "Tensiómetro", "Tensiomètre"),
    ("thermometer_digital", "digital medical thermometer", (10, 35), ["plastica", "medicina", "piccolo"], "Thermometer", "Termometro Digitale", "Fieberthermometer", "Termómetro Digital", "Thermomètre"),
    ("syringe_new", "plastic medical syringe", (10, 45), ["plastica", "medicina", "piccolo"], "Syringe", "Siringa", "Spritze", "Jeringa", "Seringue"),
    ("pill_organizer", "weekly pill organizer box", (50, 15), ["plastica", "medicina", "piccolo"], "Pill Box", "Portapillole", "Pillendose", "Pastillero", "Pilulier"),
    ("medicine_bottle_amber", "amber glass medicine bottle with a dropper", (15, 35), ["vetro", "medicina", "piccolo"], "Medicine Bottle", "Flacone di Medicina", "Medizinflasche", "Frasco de Medicina", "Flacon de Médicament"),
    ("xray_film", "x-ray film of a hand", (40, 50), ["plastica", "medicina", "piccolo"], "X-ray", "Radiografia", "Röntgenbild", "Radiografía", "Radiographie"),
    ("crutch_single", "single wooden crutch", (20, 90), ["legno", "medicina", "grande"], "Crutch", "Stampella", "Krücke", "Muleta", "Béquille"),
    ("wheelchair_mini", "wheelchair", (60, 60), ["metallo", "medicina", "grande"], "Wheelchair", "Sedia a Rotelle", "Rollstuhl", "Silla de Ruedas", "Fauteuil Roulant"),
    ("scalpel", "surgical scalpel", (40, 8), ["metallo", "medicina", "piccolo"], "Scalpel", "Bisturi", "Skalpell", "Bisturí", "Scalpel"),
    ("microscope_modern_white", "white modern microscope", (30, 50), ["plastica", "studio", "medio"], "Microscope", "Microscopio", "Mikroskop", "Microscopio", "Microscope"),
    ("telescope_tripod", "telescope on a tripod", (45, 80), ["metallo", "studio", "grande"], "Telescope", "Telescopio", "Teleskop", "Telescopio", "Télescope"),
    ("dna_model", "double helix DNA model", (25, 50), ["plastica", "studio", "piccolo"], "DNA Model", "Modello del DNA", "DNA-Modell", "Modelo de ADN", "Modèle d'ADN"),
    ("atom_model", "ball and stick molecule model", (35, 35), ["plastica", "studio", "piccolo"], "Molecule Model", "Modello Molecolare", "Molekülmodell", "Modelo Molecular", "Modèle Moléculaire"),
    ("solar_system_model", "small solar system model", (50, 40), ["metallo", "studio", "medio"], "Solar System", "Sistema Solare", "Planetenmodell", "Sistema Solar", "Système Solaire"),
    ("erlenmeyer_flask", "erlenmeyer flask with purple liquid", (25, 35), ["vetro", "studio", "piccolo"], "Lab Flask", "Beuta", "Erlenmeyerkolben", "Matraz", "Erlenmeyer"),
    ("test_tube_holder", "test tube in a clamp", (20, 45), ["vetro", "studio", "piccolo"], "Test Tube", "Provetta", "Reagenzglas", "Tubo de Ensayo", "Tube à Essai"),
    ("bunsen_burner", "bunsen burner", (20, 40), ["metallo", "studio", "piccolo"], "Bunsen Burner", "Becco Bunsen", "Bunsenbrenner", "Mechero Bunsen", "Bec Bunsen"),
    ("magnet_bar", "red and blue bar magnet", (40, 12), ["metallo", "studio", "piccolo"], "Bar Magnet", "Magnete", "Stabmagnet", "Imán de Barra", "Aimant"),
    ("tesla_coil_small", "small tesla coil", (25, 45), ["metallo", "tecnologia", "piccolo"], "Tesla Coil", "Bobina di Tesla", "Teslaspule", "Bobina de Tesla", "Bobine Tesla"),
    ("robot_arm_mini", "small robotic arm", (40, 45), ["metallo", "tecnologia", "medio"], "Robot Arm", "Braccio Robotico", "Roboterarm", "Brazo Robótico", "Bras Robotique"),
    ("circuit_board", "green-free blue circuit board", (40, 30), ["tecnologia", "piccolo"], "Circuit Board", "Scheda Elettronica", "Platine", "Placa de Circuito", "Circuit Imprimé"),
    ("solar_panel_small", "small solar panel", (45, 30), ["vetro", "tecnologia", "medio"], "Solar Panel", "Pannello Solare", "Solarpanel", "Panel Solar", "Panneau Solaire"),
    ("satellite_dish_mini", "small satellite dish", (40, 40), ["metallo", "tecnologia", "medio"], "Satellite Dish", "Parabola", "Satellitenschüssel", "Antena Parabólica", "Parabole"),
    ("space_helmet_v2", "white astronaut helmet", (40, 40), ["plastica", "tecnologia", "medio"], "Astronaut Helmet", "Casco da Astronauta", "Astronautenhelm", "Casco de Astronauta", "Casque d'Astronaute"),
    ("rocket_model", "model rocket", (20, 60), ["plastica", "giocattolo", "piccolo"], "Model Rocket", "Razzo Modellino", "Modellrakete", "Cohete", "Fusée"),
    ("ufo_model", "flying saucer model", (45, 25), ["metallo", "giocattolo", "piccolo"], "Flying Saucer", "Disco Volante", "Fliegende Untertasse", "Platillo Volante", "Soucoupe Volante"),
    ("crystal_cluster_blue", "blue crystal cluster", (35, 30), ["natura", "occulto", "piccolo"], "Blue Crystals", "Cristalli Blu", "Blaue Kristalle", "Cristales Azules", "Cristaux Bleus"),
    ("gem_emerald_free", "large cut amethyst gem", (20, 20), ["accessorio", "piccolo"], "Amethyst", "Ametista", "Amethyst", "Amatista", "Améthyste"),
    ("gold_bar_shiny", "shiny gold bar", (40, 20), ["metallo", "piccolo"], "Gold Ingot", "Lingotto", "Goldbarren", "Lingote", "Lingot"),
    ("treasure_chest_open", "open wooden treasure chest with gold coins", (50, 40), ["legno", "metallo", "antico", "medio"], "Treasure Chest", "Forziere", "Schatztruhe", "Cofre del Tesoro", "Coffre au Trésor"),
    ("pirate_hat", "black pirate tricorn hat", (45, 25), ["stoffa", "cappello", "antico", "medio"], "Pirate Hat", "Cappello da Pirata", "Piratenhut", "Sombrero Pirata", "Chapeau de Pirate"),
    ("spyglass_brass_new", "extended brass spyglass", (65, 15), ["ottone", "vetro", "viaggio", "medio"], "Spyglass", "Cannocchiale", "Fernrohr", "Catalejo", "Longue-vue"),
    ("ship_wheel_v2", "wooden ship steering wheel", (50, 50), ["legno", "viaggio", "antico", "medio"], "Ship Wheel", "Timone", "Steuerrad", "Timón", "Barre"),
    ("anchor_brass", "small brass anchor", (35, 45), ["ottone", "viaggio", "decorazione", "medio"], "Brass Anchor", "Ancora d'Ottone", "Messinganker", "Ancla de Latón", "Ancre en Laiton"),
    ("rope_knot_display", "sailor rope knot display", (40, 40), ["stoffa", "viaggio", "decorazione", "piccolo"], "Rope Knots", "Nodi Marinari", "Seemannsknoten", "Nudos Marineros", "Nœuds Marins"),
    ("oil_lamp_aladdin", "brass genie oil lamp", (45, 25), ["ottone", "occulto", "antico", "piccolo"], "Genie Lamp", "Lampada del Genio", "Wunderlampe", "Lámpara Mágica", "Lampe Magique"),
    ("magic_carpet_rolled", "rolled ornate carpet", (60, 20), ["stoffa", "occulto", "medio"], "Ornate Carpet", "Tappeto Decorato", "Prunkteppich", "Alfombra Ornamentada", "Tapis Orné"),
    ("wizard_staff", "tall wooden wizard staff with a crystal", (15, 90), ["legno", "occulto", "grande"], "Wizard Staff", "Bastone del Mago", "Zauberstab", "Báculo", "Bâton de Sorcier"),
    ("spell_scroll_open", "open parchment scroll with symbols", (45, 30), ["carta", "occulto", "piccolo"], "Spell Scroll", "Pergamena Magica", "Zauberrolle", "Pergamino Mágico", "Parchemin Magique"),
    ("cauldron_black", "black iron cauldron", (45, 40), ["ferro", "occulto", "medio"], "Cauldron", "Calderone", "Kessel", "Caldero", "Chaudron"),
    ("broom_witch", "witch broomstick", (25, 90), ["legno", "occulto", "grande"], "Witch Broom", "Scopa della Strega", "Hexenbesen", "Escoba de Bruja", "Balai de Sorcière"),
    ("potion_set", "three potion bottles, red blue gold", (40, 35), ["vetro", "occulto", "piccolo"], "Potions", "Pozioni", "Zaubertränke", "Pociones", "Potions"),
    ("tarot_deck_box", "wooden box of tarot cards", (35, 25), ["legno", "occulto", "piccolo"], "Tarot Box", "Scatola dei Tarocchi", "Tarotbox", "Caja de Tarot", "Boîte de Tarot"),
    ("ouija_board", "wooden spirit board with a planchette, no letters readable", (55, 40), ["legno", "occulto", "horror", "medio"], "Spirit Board", "Tavola Spiritica", "Hexenbrett", "Tablero Ouija", "Planche Ouija"),
    ("pentacle_amulet", "silver star amulet", (25, 30), ["argento", "occulto", "piccolo"], "Star Amulet", "Amuleto a Stella", "Sternamulett", "Amuleto Estrella", "Amulette Étoile"),
    ("skull_human_old", "old human skull", (30, 30), ["osso", "horror", "piccolo"], "Skull", "Teschio", "Schädel", "Calavera", "Crâne"),
    ("bones_pile", "small pile of bones", (40, 25), ["osso", "horror", "piccolo"], "Bones", "Ossa", "Knochen", "Huesos", "Os"),
    ("coffin_small", "small wooden coffin", (35, 70), ["legno", "horror", "grande"], "Coffin", "Bara", "Sarg", "Ataúd", "Cercueil"),
    ("tombstone_small", "small stone tombstone, blank", (35, 45), ["horror", "medio"], "Tombstone", "Lapide", "Grabstein", "Lápida", "Pierre Tombale"),
    ("chains_shackles", "iron shackles with a chain", (40, 35), ["ferro", "horror", "piccolo"], "Shackles", "Catene", "Fesseln", "Grilletes", "Chaînes"),
    ("lantern_haunted", "old rusty lantern with a pale glow", (30, 45), ["metallo", "luce", "horror", "piccolo"], "Haunted Lantern", "Lanterna Spettrale", "Spukelaterne", "Farol Embrujado", "Lanterne Hantée"),
    ("doll_creepy", "old creepy doll with a cracked face", (25, 45), ["ceramica", "horror", "giocattolo", "piccolo"], "Creepy Doll", "Bambola Inquietante", "Gruselpuppe", "Muñeca Siniestra", "Poupée Effrayante"),
    ("raven_stuffed", "stuffed black raven", (35, 35), ["natura", "horror", "piccolo"], "Raven", "Corvo", "Rabe", "Cuervo", "Corbeau"),
    ("spider_web_frame", "fake spider with a web", (35, 35), ["horror", "decorazione", "piccolo"], "Spider Web", "Ragnatela", "Spinnennetz", "Telaraña", "Toile d'Araignée"),
    ("bat_hanging", "hanging bat figure", (30, 35), ["horror", "decorazione", "piccolo"], "Bat", "Pipistrello", "Fledermaus", "Murciélago", "Chauve-souris"),
    ("vintage_car_model", "red vintage car model", (50, 25), ["metallo", "giocattolo", "vintage", "piccolo"], "Vintage Car", "Auto d'Epoca", "Oldtimer", "Coche Antiguo", "Voiture Ancienne"),
    ("motorcycle_model_v2", "small motorcycle model", (45, 30), ["metallo", "giocattolo", "piccolo"], "Motorbike Model", "Modellino di Moto", "Motorradmodell", "Moto en Miniatura", "Moto Miniature"),
    ("bicycle_vintage", "vintage bicycle", (80, 50), ["metallo", "sport", "vintage", "grande"], "Vintage Bike", "Bicicletta d'Epoca", "Altes Fahrrad", "Bicicleta Antigua", "Vélo Ancien"),
    ("scooter_kick", "kick scooter", (40, 70), ["metallo", "giocattolo", "grande"], "Kick Scooter", "Monopattino", "Tretroller", "Patinete", "Trottinette"),
    ("steering_wheel", "car steering wheel", (40, 40), ["plastica", "auto", "medio"], "Steering Wheel", "Volante", "Lenkrad", "Volante", "Volant"),
    ("license_plate_blank", "blank metal license plate", (55, 20), ["metallo", "auto", "piccolo"], "License Plate", "Targa", "Nummernschild", "Matrícula", "Plaque"),
    ("car_tire_small", "single car tire", (45, 45), ["auto", "medio"], "Tire", "Pneumatico", "Reifen", "Neumático", "Pneu"),
    ("gas_pump_nozzle", "fuel pump nozzle", (35, 35), ["metallo", "auto", "piccolo"], "Fuel Nozzle", "Pistola del Carburante", "Zapfpistole", "Surtidor", "Pistolet à Essence"),
    ("traffic_light_small", "small traffic light", (20, 50), ["metallo", "luce", "piccolo"], "Traffic Light", "Semaforo", "Ampel", "Semáforo", "Feu Tricolore"),
    ("road_sign_stop_blank", "red octagonal road sign, blank", (35, 35), ["metallo", "sicurezza", "piccolo"], "Road Sign", "Cartello Stradale", "Verkehrsschild", "Señal de Tráfico", "Panneau Routier"),
    ("sled_wooden", "wooden snow sled", (60, 30), ["legno", "giocattolo", "montagna", "medio"], "Wooden Sled", "Slittino di Legno", "Holzschlitten", "Trineo de Madera", "Luge en Bois"),
]
C = [(r[0], r[1], r[2], r[3], list(r[4:9])) for r in _ROWS]
