"""Forty generic period objects (early 20th century), interchangeable between games.
No character, place, date or readable text. No green objects (chroma key).
"""

_RAW = [
    ("brass_door_plate", "old small blank brass door name plate with two screws", (40, 20), ["ottone", "arredamento", "antico", "piccolo"], ["Door Plate", "Targhetta da Porta", "Türschild", "Placa de Puerta", "Plaque de Porte"]),
    ("wooden_coat_hanger", "old curved wooden coat hanger with a metal hook", (55, 25), ["legno", "arredamento", "vintage", "medio"], ["Coat Hanger", "Gruccia di Legno", "Kleiderbügel", "Percha de Madera", "Cintre en Bois"]),
    ("porcelain_washbowl", "old white porcelain wash basin bowl with a matching jug", (50, 45), ["ceramica", "bagno", "antico", "medio"], ["Washbowl and Jug", "Catino e Brocca", "Waschschüssel", "Palangana y Jarra", "Cuvette et Broc"]),
    ("soap_dish_brass", "old brass soap dish with a bar of soap", (35, 20), ["ottone", "bagno", "vintage", "piccolo"], ["Soap Dish", "Portasapone", "Seifenschale", "Jabonera", "Porte-savon"]),
    ("clothes_brush", "old wooden clothes brush with natural bristles", (45, 20), ["legno", "attrezzo", "vintage", "piccolo"], ["Clothes Brush", "Spazzola per Abiti", "Kleiderbürste", "Cepillo de Ropa", "Brosse à Habits"]),
    ("sewing_tin", "old round biscuit tin used as a sewing box, open with buttons and thread", (45, 30), ["metallo", "stoffa", "contenitore", "vintage", "medio"], ["Sewing Tin", "Scatola da Cucito", "Nähdose", "Lata de Costura", "Boîte à Couture"]),
    ("thimble_silver", "old silver sewing thimble", (15, 15), ["argento", "stoffa", "antico", "piccolo"], ["Thimble", "Ditale", "Fingerhut", "Dedal", "Dé à Coudre"]),
    ("button_jar", "old glass jar full of mixed vintage buttons", (30, 40), ["vetro", "stoffa", "contenitore", "vintage", "piccolo"], ["Button Jar", "Barattolo di Bottoni", "Knopfglas", "Tarro de Botones", "Bocal de Boutons"]),
    ("tape_measure_cloth", "old rolled cloth tailor tape measure", (30, 25), ["stoffa", "attrezzo", "vintage", "piccolo"], ["Tape Measure", "Metro da Sarta", "Maßband", "Cinta Métrica", "Mètre Ruban"]),
    ("flat_iron_small", "small old solid iron sad iron with a flat handle", (35, 25), ["ferro", "arredamento", "antico", "piccolo"], ["Sad Iron", "Ferro da Stiro Pieno", "Plätteisen", "Plancha de Hierro", "Fer Plein"]),
    ("wall_mirror_round", "old small round wall mirror in a gilded frame, slightly tarnished glass", (40, 40), ["vetro", "arredamento", "antico", "medio"], ["Round Mirror", "Specchio Tondo", "Runder Spiegel", "Espejo Redondo", "Miroir Rond"]),
    ("photo_album_leather", "old closed leather photo album with a clasp", (45, 40), ["cuoio", "foto", "libro", "vintage", "medio"], ["Photo Album", "Album Fotografico", "Fotoalbum", "Álbum de Fotos", "Album Photo"]),
    ("magic_lantern_slide", "old glass magic lantern slide in a wooden frame", (45, 20), ["vetro", "legno", "foto", "antico", "piccolo"], ["Lantern Slide", "Diapositiva su Vetro", "Glasdia", "Diapositiva de Vidrio", "Plaque de Lanterne"]),
    ("film_camera_tripod", "old folding wooden camera tripod legs, collapsed", (15, 80), ["legno", "foto", "antico", "medio"], ["Wooden Tripod", "Treppiede di Legno", "Holzstativ", "Trípode de Madera", "Trépied en Bois"]),
    ("radio_valve", "old glass radio vacuum tube valve", (15, 35), ["vetro", "tecnologia", "vintage", "piccolo"], ["Radio Valve", "Valvola Termoionica", "Radioröhre", "Válvula de Radio", "Lampe Radio"]),
    ("crank_telephone_wall", "old wooden wall crank telephone box with a bell pair", (40, 60), ["legno", "tecnologia", "antico", "medio"], ["Crank Telephone", "Telefono a Manovella", "Kurbeltelefon", "Teléfono de Manivela", "Téléphone à Manivelle"]),
    ("electric_fuse_box", "old porcelain electric fuse box with ceramic fuses", (40, 35), ["ceramica", "tecnologia", "antico", "piccolo"], ["Fuse Box", "Scatola dei Fusibili", "Sicherungskasten", "Caja de Fusibles", "Boîte à Fusibles"]),
    ("light_bulb_edison", "old clear edison light bulb with a filament", (15, 30), ["vetro", "luce", "tecnologia", "vintage", "piccolo"], ["Edison Bulb", "Lampadina Edison", "Edison-Glühbirne", "Bombilla Edison", "Ampoule Edison"]),
    ("bakelite_switch", "old round brown bakelite light switch", (25, 25), ["plastica", "tecnologia", "vintage", "piccolo"], ["Bakelite Switch", "Interruttore in Bachelite", "Bakelitschalter", "Interruptor de Baquelita", "Interrupteur en Bakélite"]),
    ("metronome_wooden", "old wooden pyramid metronome", (30, 50), ["legno", "musica", "vintage", "medio"], ["Metronome", "Metronomo", "Metronom", "Metrónomo", "Métronome"]),
    ("tuning_fork", "old steel tuning fork", (12, 45), ["metallo", "musica", "vintage", "piccolo"], ["Tuning Fork", "Diapason", "Stimmgabel", "Diapasón", "Diapason"]),
    ("brass_trumpet", "old dented brass trumpet", (65, 30), ["ottone", "musica", "vintage", "medio"], ["Trumpet", "Tromba", "Trompete", "Trompeta", "Trompette"]),
    ("tambourine", "old wooden tambourine with metal jingles and a worn skin", (40, 40), ["legno", "musica", "vintage", "medio"], ["Tambourine", "Tamburello", "Tamburin", "Pandereta", "Tambourin"]),
    ("chess_knight", "single old carved wooden chess knight piece", (20, 35), ["legno", "gioco", "antico", "piccolo"], ["Chess Knight", "Cavallo degli Scacchi", "Schachpferd", "Caballo de Ajedrez", "Cavalier d'Échecs"]),
    ("dominoes_box", "old wooden box of bone dominoes, open", (45, 30), ["legno", "osso", "gioco", "vintage", "medio"], ["Dominoes", "Scatola del Domino", "Dominosteine", "Caja de Dominó", "Boîte de Dominos"]),
    ("jack_in_the_box", "old tin jack in the box toy, closed", (30, 35), ["metallo", "giocattolo", "vintage", "piccolo"], ["Jack in the Box", "Scatola a Sorpresa", "Schachtelteufel", "Caja Sorpresa", "Diable en Boîte"]),
    ("wooden_yoyo", "old wooden yo-yo with string", (25, 25), ["legno", "giocattolo", "vintage", "piccolo"], ["Yo-yo", "Yo-yo di Legno", "Jo-Jo", "Yoyó", "Yo-yo"]),
    ("kaleidoscope_brass", "old brass kaleidoscope tube", (55, 15), ["ottone", "vetro", "giocattolo", "antico", "medio"], ["Kaleidoscope", "Caleidoscopio", "Kaleidoskop", "Caleidoscopio", "Kaléidoscope"]),
    ("doll_tea_set", "small old porcelain doll tea set: tiny teapot and two cups", (40, 25), ["ceramica", "giocattolo", "vintage", "piccolo"], ["Toy Tea Set", "Servizio da Tè Giocattolo", "Puppenteeservice", "Juego de Té de Juguete", "Dînette"]),
    ("hobby_horse", "old wooden hobby horse head on a stick", (30, 90), ["legno", "giocattolo", "vintage", "grande"], ["Hobby Horse", "Cavallino a Bastone", "Steckenpferd", "Caballito de Palo", "Cheval-bâton"]),
    ("wicker_picnic_basket", "old wicker picnic basket with a lid and leather straps", (55, 40), ["legno", "cuoio", "contenitore", "vintage", "medio"], ["Picnic Basket", "Cesto da Picnic", "Picknickkorb", "Cesta de Picnic", "Panier de Pique-nique"]),
    ("glass_decanter", "old cut glass decanter with a stopper, empty", (30, 55), ["vetro", "bevanda", "bar", "vintage", "medio"], ["Decanter", "Caraffa di Cristallo", "Karaffe", "Licorera", "Carafe"]),
    ("soda_siphon_blue", "old blue glass soda siphon bottle with a metal head", (25, 60), ["vetro", "metallo", "bevanda", "bar", "vintage", "medio"], ["Soda Siphon", "Sifone del Seltz", "Sodasiphon", "Sifón", "Siphon"]),
    ("cocktail_shaker", "old silver cocktail shaker", (25, 50), ["argento", "bar", "bevanda", "vintage", "medio"], ["Cocktail Shaker", "Shaker", "Cocktailshaker", "Coctelera", "Shaker"]),
    ("bottle_opener_iron", "old cast iron wall bottle opener", (25, 35), ["ferro", "bar", "vintage", "piccolo"], ["Bottle Opener", "Apribottiglie", "Flaschenöffner", "Abrebotellas", "Décapsuleur"]),
    ("sugar_cube_box", "small old cardboard box of sugar cubes, open", (35, 25), ["carta", "cibo", "cucina", "vintage", "piccolo"], ["Sugar Cubes", "Zollette di Zucchero", "Würfelzucker", "Terrones de Azúcar", "Sucre en Morceaux"]),
    ("tea_tin_caddy", "old tin tea caddy with a lid, faded pattern", (30, 40), ["metallo", "cibo", "contenitore", "vintage", "piccolo"], ["Tea Caddy", "Barattolo del Tè", "Teedose", "Lata de Té", "Boîte à Thé"]),
    ("egg_timer_sand", "small old sand egg timer in a wooden frame", (20, 35), ["legno", "vetro", "cucina", "vintage", "piccolo"], ["Egg Timer", "Timer da Cucina a Sabbia", "Eieruhr", "Reloj de Huevos", "Sablier de Cuisine"]),
    ("kitchen_scale_weights", "old cast iron kitchen balance scale with a brass pan", (50, 45), ["ferro", "ottone", "bilancia", "cucina", "antico", "medio"], ["Kitchen Balance", "Bilancia da Cucina", "Küchenwaage", "Balanza de Cocina", "Balance de Cuisine"]),
    ("pastry_cutters", "few old tin pastry cookie cutters", (40, 25), ["metallo", "cucina", "vintage", "piccolo"], ["Pastry Cutters", "Formine per Biscotti", "Ausstechformen", "Cortadores de Galletas", "Emporte-pièces"]),
    ("nutcracker_iron", "old cast iron nutcracker", (20, 45), ["ferro", "cucina", "vintage", "piccolo"], ["Nutcracker", "Schiaccianoci", "Nussknacker", "Cascanueces", "Casse-noix"]),
    ("gas_lamp_mantle", "old brass gas wall lamp with a glass shade", (35, 45), ["ottone", "vetro", "luce", "antico", "medio"], ["Gas Lamp", "Lampada a Gas", "Gaslampe", "Lámpara de Gas", "Lampe à Gaz"]),
    ("fire_bellows_small", "small old leather hand bellows with brass nozzle", (30, 50), ["cuoio", "legno", "arredamento", "antico", "medio"], ["Hand Bellows", "Mantice a Mano", "Handblasebalg", "Fuelle de Mano", "Soufflet à Main"]),
    ("umbrella_stand", "old cast iron umbrella stand, empty", (30, 60), ["ferro", "arredamento", "antico", "medio"], ["Umbrella Stand", "Portaombrelli", "Schirmständer", "Paragüero", "Porte-parapluies"]),
    ("barometer_banjo", "old wooden banjo barometer", (25, 70), ["legno", "vetro", "tecnologia", "antico", "medio"], ["Banjo Barometer", "Barometro a Banjo", "Banjobarometer", "Barómetro de Banjo", "Baromètre Banjo"]),
    ("desk_globe_small", "small old tin toy desk globe", (30, 40), ["metallo", "studio", "vintage", "piccolo"], ["Toy Globe", "Mappamondo Giocattolo", "Spielzeugglobus", "Globo de Juguete", "Globe Jouet"]),
    ("pen_nib_box", "small old tin box of steel pen nibs, open", (30, 20), ["metallo", "ufficio", "vintage", "piccolo"], ["Pen Nibs", "Scatola di Pennini", "Federdose", "Caja de Plumillas", "Boîte de Plumes"]),
    ("envelope_stack_tied", "small stack of old blank envelopes tied with twine", (40, 25), ["carta", "ufficio", "vintage", "piccolo"], ["Envelopes", "Pacco di Buste", "Umschläge", "Sobres", "Enveloppes"]),
    ("spirit_level_wood", "old wooden spirit level with brass ends", (65, 15), ["legno", "ottone", "attrezzo", "vintage", "medio"], ["Spirit Level", "Livella di Legno", "Wasserwaage", "Nivel de Burbuja", "Niveau à Bulle"]),
    ("plumb_bob", "old brass plumb bob on a string", (15, 40), ["ottone", "attrezzo", "antico", "piccolo"], ["Plumb Bob", "Filo a Piombo", "Senklot", "Plomada", "Fil à Plomb"]),
]
DROPPED = set(['jack_in_the_box', 'cocktail_shaker', 'metronome_wooden', 'wicker_picnic_basket', 'glass_decanter', 'soda_siphon_blue', 'nutcracker_iron', 'spirit_level_wood', 'tape_measure_cloth', 'desk_globe_small'])  # exist already (concept check)
C = [r for r in _RAW if r[0] not in DROPPED][:40]
