"""400-object batch, part C (100): office, tech, music, toys, games, sport, travel."""

_ROWS = [
    ("typewriter_red", "red vintage portable typewriter", (55, 40), ["metallo", "ufficio", "vintage", "medio"], "Red Typewriter", "Macchina da Scrivere Rossa", "Rote Schreibmaschine", "Máquina de Escribir Roja", "Machine à Écrire Rouge"),
    ("rotary_phone_red", "red rotary dial telephone", (40, 30), ["plastica", "tecnologia", "vintage", "medio"], "Red Phone", "Telefono Rosso", "Rotes Telefon", "Teléfono Rojo", "Téléphone Rouge"),
    ("fax_machine", "old fax machine", (50, 35), ["plastica", "ufficio", "tecnologia", "medio"], "Fax Machine", "Fax", "Faxgerät", "Fax", "Fax"),
    ("printer_desk", "small desktop printer", (55, 35), ["plastica", "ufficio", "tecnologia", "medio"], "Printer", "Stampante", "Drucker", "Impresora", "Imprimante"),
    ("monitor_crt_v2", "old CRT computer monitor, screen off", (50, 45), ["plastica", "tecnologia", "vintage", "medio"], "CRT Monitor", "Monitor a Tubo", "Röhrenmonitor", "Monitor CRT", "Écran Cathodique"),
    ("floppy_disks", "few old floppy disks", (35, 30), ["plastica", "tecnologia", "vintage", "piccolo"], "Floppy Disks", "Floppy Disk", "Disketten", "Disquetes", "Disquettes"),
    ("cd_case_stack", "small stack of CD cases, blank", (30, 30), ["plastica", "musica", "piccolo"], "CD Cases", "Custodie CD", "CD-Hüllen", "Cajas de CD", "Boîtiers CD"),
    ("walkman_cassette", "portable cassette player with headphones, no logo", (35, 30), ["plastica", "musica", "vintage", "piccolo"], "Cassette Player", "Lettore di Cassette", "Kassettenspieler", "Walkman", "Baladeur"),
    ("boombox", "retro boombox radio, no logo", (60, 35), ["plastica", "musica", "vintage", "medio"], "Boombox", "Stereo Portatile", "Ghettoblaster", "Radiocasete", "Radio-cassette"),
    ("record_player", "vintage suitcase record player", (55, 40), ["legno", "musica", "vintage", "medio"], "Record Player", "Giradischi", "Plattenspieler", "Tocadiscos", "Tourne-disque"),
    ("radio_wooden", "old wooden table radio", (50, 35), ["legno", "tecnologia", "vintage", "medio"], "Wooden Radio", "Radio di Legno", "Holzradio", "Radio de Madera", "Radio en Bois"),
    ("video_camera_old", "old VHS camcorder, no logo", (45, 30), ["plastica", "tecnologia", "vintage", "medio"], "Camcorder", "Videocamera", "Camcorder", "Videocámara", "Caméscope"),
    ("instant_camera", "instant camera, no logo", (35, 35), ["plastica", "foto", "piccolo"], "Instant Camera", "Fotocamera Istantanea", "Sofortbildkamera", "Cámara Instantánea", "Appareil Instantané"),
    ("film_roll_canister", "35mm film roll canister", (15, 20), ["plastica", "foto", "piccolo"], "Film Roll", "Rullino", "Filmrolle", "Carrete", "Pellicule"),
    ("slide_viewer", "old slide viewer", (30, 25), ["plastica", "foto", "vintage", "piccolo"], "Slide Viewer", "Visore per Diapositive", "Diabetrachter", "Visor de Diapositivas", "Visionneuse"),
    ("projector_reel", "old film reel", (40, 40), ["metallo", "foto", "vintage", "piccolo"], "Film Reel", "Bobina di Pellicola", "Filmspule", "Bobina", "Bobine"),
    ("clapperboard", "film clapperboard, blank", (40, 35), ["legno", "foto", "piccolo"], "Clapperboard", "Ciak", "Filmklappe", "Claqueta", "Clap"),
    ("microphone_vintage", "vintage chrome microphone on a stand", (25, 50), ["metallo", "musica", "vintage", "medio"], "Vintage Mic", "Microfono Vintage", "Retro-Mikrofon", "Micrófono Vintage", "Micro Vintage"),
    ("electric_guitar_red", "red electric guitar, no logo", (35, 90), ["legno", "musica", "grande"], "Electric Guitar", "Chitarra Elettrica", "E-Gitarre", "Guitarra Eléctrica", "Guitare Électrique"),
    ("acoustic_guitar", "acoustic guitar", (40, 90), ["legno", "musica", "grande"], "Acoustic Guitar", "Chitarra Acustica", "Akustikgitarre", "Guitarra Acústica", "Guitare Acoustique"),
    ("bass_drum_small", "small bass drum", (50, 45), ["legno", "musica", "medio"], "Bass Drum", "Grancassa", "Basstrommel", "Bombo", "Grosse Caisse"),
    ("saxophone", "brass saxophone", (35, 70), ["ottone", "musica", "grande"], "Saxophone", "Sassofono", "Saxophon", "Saxofón", "Saxophone"),
    ("clarinet", "black clarinet", (15, 70), ["legno", "musica", "medio"], "Clarinet", "Clarinetto", "Klarinette", "Clarinete", "Clarinette"),
    ("flute_silver", "silver transverse flute", (80, 10), ["argento", "musica", "medio"], "Flute", "Flauto Traverso", "Querflöte", "Flauta", "Flûte"),
    ("accordion_red", "red accordion", (50, 45), ["musica", "medio"], "Accordion", "Fisarmonica", "Akkordeon", "Acordeón", "Accordéon"),
    ("banjo", "banjo", (35, 85), ["legno", "musica", "grande"], "Banjo", "Banjo", "Banjo", "Banjo", "Banjo"),
    ("harp_small", "small wooden harp", (40, 60), ["legno", "musica", "medio"], "Small Harp", "Arpa", "Harfe", "Arpa", "Harpe"),
    ("triangle_instrument", "musical triangle with a beater", (35, 35), ["metallo", "musica", "piccolo"], "Triangle", "Triangolo", "Triangel", "Triángulo", "Triangle"),
    ("castanets", "pair of wooden castanets", (30, 20), ["legno", "musica", "piccolo"], "Castanets", "Nacchere", "Kastagnetten", "Castañuelas", "Castagnettes"),
    ("bongo_drums", "pair of bongo drums", (45, 30), ["legno", "musica", "medio"], "Bongos", "Bonghi", "Bongos", "Bongós", "Bongos"),
    ("keyboard_toy", "small toy keyboard piano", (55, 20), ["plastica", "musica", "giocattolo", "medio"], "Toy Piano", "Pianola Giocattolo", "Spielzeugklavier", "Piano de Juguete", "Piano Jouet"),
    ("music_notes_sheet", "sheet of music notes on a stand", (35, 45), ["carta", "musica", "piccolo"], "Sheet Music", "Spartito", "Noten", "Partitura", "Partition"),
    ("conductor_baton", "white conductor baton", (50, 8), ["legno", "musica", "piccolo"], "Baton", "Bacchetta del Direttore", "Taktstock", "Batuta", "Baguette"),
    ("chess_board_set", "chess board with pieces set up", (50, 50), ["legno", "gioco", "medio"], "Chess Set", "Scacchiera", "Schachspiel", "Ajedrez", "Échiquier"),
    ("backgammon_board", "open backgammon board", (55, 35), ["legno", "gioco", "medio"], "Backgammon", "Tavola Reale", "Backgammon", "Backgammon", "Backgammon"),
    ("mahjong_tiles", "few mahjong tiles", (40, 25), ["gioco", "piccolo"], "Mahjong Tiles", "Tessere del Mahjong", "Mahjong-Steine", "Fichas de Mahjong", "Tuiles de Mahjong"),
    ("go_stones_bowl", "bowls of black and white go stones", (45, 25), ["legno", "gioco", "piccolo"], "Go Stones", "Pedine del Go", "Go-Steine", "Piedras de Go", "Pierres de Go"),
    ("dice_colorful", "few colourful plastic dice", (30, 20), ["plastica", "gioco", "piccolo"], "Dice", "Dadi Colorati", "Bunte Würfel", "Dados de Colores", "Dés Colorés"),
    ("roulette_wheel_small", "small roulette wheel", (45, 20), ["legno", "gioco", "medio"], "Roulette", "Roulette", "Roulette", "Ruleta", "Roulette"),
    ("slot_machine_mini", "small toy slot machine", (35, 45), ["metallo", "gioco", "piccolo"], "Slot Machine", "Slot Machine", "Spielautomat", "Tragaperras", "Machine à Sous"),
    ("dartboard_v2", "round dartboard", (45, 45), ["gioco", "sport", "medio"], "Dartboard", "Bersaglio per Freccette", "Dartscheibe", "Diana", "Cible"),
    ("billiard_balls", "few billiard balls", (40, 25), ["gioco", "sport", "piccolo"], "Billiard Balls", "Palle da Biliardo", "Billardkugeln", "Bolas de Billar", "Boules de Billard"),
    ("bowling_pin", "white bowling pin", (15, 45), ["sport", "piccolo"], "Bowling Pin", "Birillo", "Kegel", "Bolo", "Quille"),
    ("toy_soldiers_plastic", "few plastic toy soldiers", (35, 25), ["plastica", "giocattolo", "piccolo"], "Toy Soldiers", "Soldatini", "Spielzeugsoldaten", "Soldaditos", "Petits Soldats"),
    ("toy_car_race", "red toy race car", (45, 20), ["metallo", "giocattolo", "piccolo"], "Race Car", "Auto da Corsa Giocattolo", "Rennauto", "Coche de Carreras", "Voiture de Course"),
    ("toy_truck_wood", "wooden toy truck", (50, 30), ["legno", "giocattolo", "piccolo"], "Toy Truck", "Camioncino di Legno", "Holzlaster", "Camión de Madera", "Camion en Bois"),
    ("rocking_horse_small", "small wooden rocking horse", (50, 40), ["legno", "giocattolo", "medio"], "Rocking Horse", "Cavallo a Dondolo", "Schaukelpferd", "Caballo Balancín", "Cheval à Bascule"),
    ("doll_porcelain_new", "porcelain doll in a dress", (25, 50), ["ceramica", "giocattolo", "piccolo"], "Porcelain Doll", "Bambola di Porcellana", "Porzellanpuppe", "Muñeca de Porcelana", "Poupée en Porcelaine"),
    ("dollhouse_small", "small wooden dollhouse", (50, 50), ["legno", "giocattolo", "medio"], "Dollhouse", "Casa delle Bambole", "Puppenhaus", "Casa de Muñecas", "Maison de Poupée"),
    ("stuffed_rabbit", "plush toy rabbit", (30, 45), ["stoffa", "giocattolo", "piccolo"], "Plush Rabbit", "Coniglietto di Peluche", "Plüschhase", "Conejo de Peluche", "Lapin en Peluche"),
    ("stuffed_elephant", "plush toy elephant", (40, 35), ["stoffa", "giocattolo", "piccolo"], "Plush Elephant", "Elefante di Peluche", "Plüschelefant", "Elefante de Peluche", "Éléphant en Peluche"),
    ("puppet_marionette", "wooden string marionette", (30, 60), ["legno", "giocattolo", "medio"], "Marionette", "Marionetta", "Marionette", "Marioneta", "Marionnette"),
    ("kite_diamond_red", "red diamond kite", (40, 55), ["stoffa", "giocattolo", "medio"], "Red Kite", "Aquilone Rosso", "Roter Drachen", "Cometa Roja", "Cerf-volant Rouge"),
    ("hula_hoop", "hula hoop", (60, 60), ["plastica", "giocattolo", "grande"], "Hula Hoop", "Cerchio", "Hula-Hoop", "Aro", "Cerceau"),
    ("bubble_wand", "bubble wand and bottle", (25, 40), ["plastica", "giocattolo", "piccolo"], "Bubbles", "Bolle di Sapone", "Seifenblasen", "Pompas", "Bulles"),
    ("slinky_spring", "metal spring toy", (25, 25), ["metallo", "giocattolo", "piccolo"], "Spring Toy", "Molla Giocattolo", "Spielfeder", "Muelle", "Ressort"),
    ("magic_8_ball", "black fortune ball toy", (25, 25), ["plastica", "giocattolo", "piccolo"], "Fortune Ball", "Palla Magica", "Orakelkugel", "Bola Mágica", "Boule Magique"),
    ("spinning_fidget", "fidget spinner", (25, 25), ["plastica", "giocattolo", "piccolo"], "Fidget Spinner", "Spinner", "Fidget Spinner", "Spinner", "Hand Spinner"),
    ("water_pistol", "plastic water pistol", (40, 25), ["plastica", "giocattolo", "piccolo"], "Water Pistol", "Pistola ad Acqua", "Wasserpistole", "Pistola de Agua", "Pistolet à Eau"),
    ("toy_sword_wood", "wooden toy sword", (15, 60), ["legno", "giocattolo", "piccolo"], "Wooden Sword", "Spada di Legno", "Holzschwert", "Espada de Madera", "Épée en Bois"),
    ("toy_shield", "painted wooden toy shield", (40, 45), ["legno", "giocattolo", "medio"], "Toy Shield", "Scudo Giocattolo", "Spielzeugschild", "Escudo de Juguete", "Bouclier Jouet"),
    ("crown_toy_gold", "golden toy crown with gems", (35, 25), ["metallo", "giocattolo", "piccolo"], "Toy Crown", "Corona Giocattolo", "Spielzeugkrone", "Corona de Juguete", "Couronne Jouet"),
    ("magic_kit_box", "magic trick kit box, plain", (45, 30), ["carta", "giocattolo", "piccolo"], "Magic Kit", "Kit di Magia", "Zauberkasten", "Kit de Magia", "Coffret de Magie"),
    ("tennis_racket_modern", "modern tennis racket", (30, 70), ["plastica", "sport", "medio"], "Tennis Racket", "Racchetta da Tennis", "Tennisschläger", "Raqueta de Tenis", "Raquette de Tennis"),
    ("badminton_racket", "badminton racket", (25, 65), ["metallo", "sport", "medio"], "Badminton Racket", "Racchetta da Badminton", "Federballschläger", "Raqueta de Bádminton", "Raquette de Badminton"),
    ("baseball_glove_new", "leather baseball glove with a ball", (40, 40), ["cuoio", "sport", "medio"], "Baseball Glove", "Guantone da Baseball", "Baseballhandschuh", "Guante de Béisbol", "Gant de Baseball"),
    ("hockey_puck", "black hockey puck", (20, 10), ["plastica", "sport", "piccolo"], "Hockey Puck", "Disco da Hockey", "Puck", "Disco de Hockey", "Palet"),
    ("ski_goggles", "ski goggles", (40, 20), ["plastica", "sport", "montagna", "piccolo"], "Ski Goggles", "Maschera da Sci", "Skibrille", "Gafas de Esquí", "Masque de Ski"),
    ("ski_poles", "pair of ski poles", (20, 90), ["metallo", "sport", "montagna", "grande"], "Ski Poles", "Racchette da Sci", "Skistöcke", "Bastones de Esquí", "Bâtons de Ski"),
    ("ice_skates_white", "white figure ice skates", (45, 40), ["cuoio", "sport", "piccolo"], "Figure Skates", "Pattini Bianchi", "Eiskunstlaufschuhe", "Patines Blancos", "Patins Blancs"),
    ("roller_skates", "retro roller skates", (45, 40), ["cuoio", "sport", "piccolo"], "Roller Skates", "Pattini a Rotelle", "Rollschuhe", "Patines", "Patins à Roulettes"),
    ("surfboard_small", "small surfboard", (25, 90), ["plastica", "sport", "grande"], "Surfboard", "Tavola da Surf", "Surfbrett", "Tabla de Surf", "Planche de Surf"),
    ("oar_wooden", "wooden rowing oar", (15, 90), ["legno", "sport", "grande"], "Oar", "Remo", "Ruder", "Remo", "Rame"),
    ("life_jacket", "orange life jacket", (45, 50), ["stoffa", "sport", "sicurezza", "medio"], "Life Jacket", "Giubbotto Salvagente", "Schwimmweste", "Chaleco Salvavidas", "Gilet de Sauvetage"),
    ("fishing_rod_modern", "fishing rod with a reel", (15, 90), ["metallo", "sport", "grande"], "Fishing Rod", "Canna da Pesca", "Angelrute", "Caña de Pescar", "Canne à Pêche"),
    ("tackle_box", "open fishing tackle box", (45, 30), ["plastica", "sport", "contenitore", "piccolo"], "Tackle Box", "Cassetta da Pesca", "Angelkasten", "Caja de Pesca", "Boîte à Pêche"),
    ("golf_club_v2", "golf club driver", (15, 90), ["metallo", "sport", "grande"], "Golf Club", "Mazza da Golf", "Golfschläger", "Palo de Golf", "Club de Golf"),
    ("boxing_gloves_red", "red boxing gloves", (45, 40), ["cuoio", "sport", "medio"], "Boxing Gloves", "Guantoni Rossi", "Boxhandschuhe", "Guantes de Boxeo", "Gants de Boxe"),
    ("jump_rope_leather", "leather jump rope", (40, 35), ["cuoio", "sport", "piccolo"], "Leather Rope", "Corda di Cuoio", "Lederseil", "Comba de Cuero", "Corde en Cuir"),
    ("water_bottle_sport", "blue plastic sport water bottle", (15, 45), ["plastica", "sport", "piccolo"], "Sport Bottle", "Borraccia Sportiva", "Sportflasche", "Botella Deportiva", "Gourde de Sport"),
    ("sweatband", "white wrist sweatband", (20, 15), ["stoffa", "sport", "piccolo"], "Sweatband", "Polsino", "Schweißband", "Muñequera", "Poignet Éponge"),
    ("gym_bag", "black gym duffel bag", (55, 30), ["stoffa", "sport", "medio"], "Gym Bag", "Borsone", "Sporttasche", "Bolsa de Deporte", "Sac de Sport"),
    ("medal_silver", "silver medal with a ribbon", (25, 40), ["argento", "sport", "piccolo"], "Silver Medal", "Medaglia d'Argento", "Silbermedaille", "Medalla de Plata", "Médaille d'Argent"),
    ("medal_bronze", "bronze medal with a ribbon", (25, 40), ["metallo", "sport", "piccolo"], "Bronze Medal", "Medaglia di Bronzo", "Bronzemedaille", "Medalla de Bronce", "Médaille de Bronze"),
    ("trophy_large", "large golden trophy on a base", (35, 60), ["metallo", "sport", "medio"], "Big Trophy", "Grande Coppa", "Großer Pokal", "Gran Trofeo", "Grand Trophée"),
    ("stopwatch_silver", "silver mechanical stopwatch", (25, 30), ["metallo", "sport", "piccolo"], "Stopwatch", "Cronometro", "Stoppuhr", "Cronómetro", "Chronomètre"),
    ("pennant_flag", "blank triangle sports pennant", (50, 25), ["stoffa", "sport", "piccolo"], "Pennant", "Gagliardetto", "Wimpel", "Banderín", "Fanion"),
    ("globe_travel", "small world globe", (30, 40), ["plastica", "viaggio", "piccolo"], "Small Globe", "Piccolo Mappamondo", "Kleiner Globus", "Globo Pequeño", "Petit Globe"),
    ("road_map_folded", "folded road map", (40, 30), ["carta", "viaggio", "piccolo"], "Road Map", "Carta Stradale", "Straßenkarte", "Mapa de Carreteras", "Carte Routière"),
    ("travel_guide_book", "travel guide book, plain cover", (30, 40), ["carta", "libro", "viaggio", "piccolo"], "Guide Book", "Guida Turistica", "Reiseführer", "Guía de Viaje", "Guide de Voyage"),
    ("camera_bag", "camera shoulder bag", (40, 35), ["stoffa", "viaggio", "foto", "medio"], "Camera Bag", "Borsa Fotografica", "Kameratasche", "Bolsa de Cámara", "Sac Photo"),
    ("luggage_tag_leather", "leather luggage tag", (25, 35), ["cuoio", "viaggio", "piccolo"], "Leather Tag", "Etichetta in Pelle", "Lederanhänger", "Etiqueta de Cuero", "Étiquette en Cuir"),
    ("boarding_pass", "blank boarding pass ticket", (45, 20), ["carta", "viaggio", "piccolo"], "Boarding Pass", "Carta d'Imbarco", "Bordkarte", "Tarjeta de Embarque", "Carte d'Embarquement"),
    ("souvenir_magnet", "souvenir fridge magnet, no text", (25, 20), ["ceramica", "viaggio", "piccolo"], "Souvenir Magnet", "Calamita Souvenir", "Souvenirmagnet", "Imán de Recuerdo", "Magnet Souvenir"),
    ("snow_globe_city", "snow globe with a tiny tower", (30, 35), ["vetro", "viaggio", "decorazione", "piccolo"], "City Snow Globe", "Palla di Neve con Torre", "Schneekugel mit Turm", "Bola de Nieve", "Boule à Neige"),
    ("tent_small", "small dome camping tent", (70, 45), ["stoffa", "viaggio", "grande"], "Tent", "Tenda", "Zelt", "Tienda de Campaña", "Tente"),
    ("folding_chair", "folding camping chair", (45, 55), ["stoffa", "metallo", "viaggio", "medio"], "Folding Chair", "Sedia Pieghevole", "Klappstuhl", "Silla Plegable", "Chaise Pliante"),
    ("cooler_box_v2", "portable cooler box", (50, 35), ["plastica", "contenitore", "viaggio", "medio"], "Cooler", "Borsa Frigo", "Kühlbox", "Nevera", "Glacière"),
    ("hammock_rolled", "rolled hammock", (60, 20), ["stoffa", "viaggio", "medio"], "Hammock", "Amaca", "Hängematte", "Hamaca", "Hamac"),
    ("walking_stick_hiking", "wooden hiking stick", (15, 90), ["legno", "viaggio", "grande"], "Hiking Stick", "Bastone da Trekking", "Wanderstock", "Bastón de Senderismo", "Bâton de Marche"),
]
C = [(r[0], r[1], r[2], r[3], list(r[4:9])) for r in _ROWS]
