"""400-object batch, part A (100): home, kitchen, food, drinks. Variants of existing
objects are allowed (user choice); ids are made unique at import time."""

_ROWS = [
    ("copper_saucepan", "shiny copper saucepan with a brass handle", (55, 30), ["metallo", "cucina", "medio"], "Copper Saucepan", "Casseruola di Rame", "Kupfertopf", "Cazo de Cobre", "Casserole en Cuivre"),
    ("cast_iron_skillet_new", "black cast iron skillet", (60, 30), ["ferro", "cucina", "medio"], "Iron Skillet", "Padella di Ghisa", "Gusseisenpfanne", "Sartén de Hierro", "Poêle en Fonte"),
    ("wok_steel", "carbon steel wok with a wooden handle", (70, 30), ["metallo", "cucina", "medio"], "Wok", "Wok", "Wok", "Wok", "Wok"),
    ("dutch_oven_red", "red enamel dutch oven pot with a lid", (50, 40), ["ferro", "cucina", "medio"], "Dutch Oven", "Casseruola in Ghisa", "Bräter", "Cocotte", "Cocotte"),
    ("pressure_cooker", "stainless steel pressure cooker", (55, 45), ["metallo", "cucina", "medio"], "Pressure Cooker", "Pentola a Pressione", "Schnellkochtopf", "Olla a Presión", "Autocuiseur"),
    ("steamer_bamboo", "round bamboo steamer basket with a lid", (45, 30), ["legno", "cucina", "medio"], "Bamboo Steamer", "Cestello di Bambù", "Bambusdämpfer", "Vaporera de Bambú", "Panier Vapeur"),
    ("mortar_marble", "white marble mortar and pestle", (40, 35), ["cucina", "piccolo"], "Marble Mortar", "Mortaio di Marmo", "Marmormörser", "Mortero de Mármol", "Mortier en Marbre"),
    ("rolling_pin_marble", "white marble rolling pin", (65, 15), ["cucina", "medio"], "Marble Rolling Pin", "Mattarello di Marmo", "Marmor-Nudelholz", "Rodillo de Mármol", "Rouleau en Marbre"),
    ("kitchen_scale_digital", "white digital kitchen scale, display off", (45, 15), ["plastica", "bilancia", "cucina", "piccolo"], "Digital Scale", "Bilancia Digitale", "Digitalwaage", "Báscula Digital", "Balance Numérique"),
    ("mixing_bowls_nested", "nested stainless steel mixing bowls", (50, 30), ["metallo", "cucina", "medio"], "Mixing Bowls", "Ciotole Impilate", "Rührschüsseln", "Boles de Mezcla", "Saladiers"),
    ("sieve_fine_mesh", "fine mesh kitchen sieve", (50, 25), ["metallo", "cucina", "piccolo"], "Fine Sieve", "Colino Fine", "Feines Sieb", "Colador Fino", "Tamis Fin"),
    ("tongs_kitchen", "stainless steel kitchen tongs", (15, 50), ["metallo", "cucina", "piccolo"], "Tongs", "Pinze da Cucina", "Küchenzange", "Pinzas de Cocina", "Pince de Cuisine"),
    ("peeler_vegetable", "vegetable peeler", (12, 40), ["metallo", "cucina", "piccolo"], "Peeler", "Pelapatate", "Sparschäler", "Pelador", "Économe"),
    ("zester_grater", "long microplane zester grater", (60, 12), ["metallo", "cucina", "piccolo"], "Zester", "Grattugia Fine", "Zestenreibe", "Rallador Fino", "Zesteur"),
    ("knife_block", "wooden knife block with knives", (35, 45), ["legno", "metallo", "cucina", "medio"], "Knife Block", "Ceppo dei Coltelli", "Messerblock", "Taco de Cuchillos", "Bloc à Couteaux"),
    ("meat_cleaver", "heavy meat cleaver", (50, 25), ["metallo", "cucina", "medio"], "Cleaver", "Mannaia", "Hackbeil", "Cuchillo de Carnicero", "Couperet"),
    ("oil_bottle_glass", "glass olive oil cruet with a pourer", (15, 45), ["vetro", "cucina", "piccolo"], "Oil Cruet", "Oliera", "Ölflasche", "Aceitera", "Huilier"),
    ("vinegar_bottle", "small glass vinegar bottle with a cork, no label", (15, 40), ["vetro", "cucina", "piccolo"], "Vinegar Bottle", "Bottiglia di Aceto", "Essigflasche", "Botella de Vinagre", "Bouteille de Vinaigre"),
    ("salt_shaker_glass", "glass salt shaker with a metal top", (15, 25), ["vetro", "cucina", "piccolo"], "Salt Shaker", "Saliera di Vetro", "Salzstreuer", "Salero", "Salière"),
    ("pepper_grinder_steel", "stainless steel pepper grinder", (15, 45), ["metallo", "cucina", "piccolo"], "Steel Pepper Mill", "Macinapepe d'Acciaio", "Pfeffermühle aus Stahl", "Molinillo de Acero", "Moulin Inox"),
    ("butter_knife", "silver butter knife", (45, 10), ["argento", "cucina", "piccolo"], "Butter Knife", "Coltello da Burro", "Buttermesser", "Cuchillo de Mantequilla", "Couteau à Beurre"),
    ("cake_server", "silver cake server", (50, 15), ["argento", "cucina", "piccolo"], "Cake Server", "Paletta per Torte", "Tortenheber", "Pala para Tartas", "Pelle à Tarte"),
    ("gravy_ladle_silver", "small silver sauce ladle", (15, 40), ["argento", "cucina", "piccolo"], "Sauce Ladle", "Mestolino per Salse", "Soßenkelle", "Cucharón de Salsa", "Louche à Sauce"),
    ("soup_tureen", "white porcelain soup tureen with a lid", (50, 40), ["ceramica", "cucina", "medio"], "Soup Tureen", "Zuppiera", "Suppenterrine", "Sopera", "Soupière"),
    ("cake_stand_glass", "glass cake stand with a dome", (40, 45), ["vetro", "cucina", "medio"], "Cake Stand", "Alzatina con Campana", "Tortenplatte", "Quesera de Vidrio", "Présentoir à Gâteau"),
    ("fruit_bowl_ceramic", "ceramic fruit bowl with apples and pears", (50, 30), ["ceramica", "cibo", "medio"], "Fruit Bowl", "Fruttiera", "Obstschale", "Frutero", "Coupe de Fruits"),
    ("bread_basket_wicker", "wicker bread basket with bread slices", (45, 25), ["legno", "cibo", "piccolo"], "Bread Basket", "Cestino del Pane", "Brotkorb", "Panera", "Corbeille à Pain"),
    ("tea_set_porcelain", "porcelain tea set: teapot, cup and saucer", (50, 35), ["ceramica", "bevanda", "medio"], "Tea Set", "Servizio da Tè", "Teeservice", "Juego de Té", "Service à Thé"),
    ("espresso_cup_pair", "two small espresso cups with saucers", (40, 20), ["ceramica", "bevanda", "piccolo"], "Espresso Cups", "Tazzine da Caffè", "Espressotassen", "Tazas de Café", "Tasses à Espresso"),
    ("coffee_beans_bag", "burlap bag of coffee beans, open", (35, 40), ["stoffa", "cibo", "piccolo"], "Coffee Beans", "Sacco di Caffè", "Kaffeebohnen", "Saco de Café", "Sac de Café"),
    ("tea_bags_box", "open box of tea bags, plain", (35, 20), ["carta", "bevanda", "piccolo"], "Tea Bags", "Bustine di Tè", "Teebeutel", "Bolsitas de Té", "Sachets de Thé"),
    ("sugar_bowl_ceramic", "white ceramic sugar bowl with a lid", (25, 25), ["ceramica", "cucina", "piccolo"], "Sugar Bowl", "Zuccheriera", "Zuckerdose", "Azucarero", "Sucrier"),
    ("milk_jug_small", "small white porcelain milk jug", (20, 25), ["ceramica", "bevanda", "piccolo"], "Milk Jug", "Lattiera", "Milchkännchen", "Lechera", "Pot à Lait"),
    ("hot_chocolate_mug", "mug of hot chocolate with marshmallows", (30, 30), ["ceramica", "bevanda", "piccolo"], "Hot Chocolate", "Cioccolata Calda", "Heiße Schokolade", "Chocolate Caliente", "Chocolat Chaud"),
    ("lemonade_pitcher", "glass pitcher of lemonade with lemon slices", (30, 45), ["vetro", "bevanda", "medio"], "Lemonade", "Caraffa di Limonata", "Limonade", "Jarra de Limonada", "Citronnade"),
    ("orange_juice_glass", "glass of orange juice", (15, 35), ["vetro", "bevanda", "piccolo"], "Orange Juice", "Spremuta", "Orangensaft", "Zumo de Naranja", "Jus d'Orange"),
    ("milkshake_glass", "tall milkshake with a straw and cream", (20, 45), ["vetro", "bevanda", "piccolo"], "Milkshake", "Frappè", "Milchshake", "Batido", "Milk-shake"),
    ("cocktail_glass_olive", "martini cocktail glass with an olive", (25, 35), ["vetro", "bevanda", "bar", "piccolo"], "Cocktail", "Cocktail", "Cocktail", "Cóctel", "Cocktail"),
    ("wine_glass_white", "glass of white wine", (15, 40), ["vetro", "bevanda", "piccolo"], "White Wine", "Calice di Bianco", "Weißwein", "Vino Blanco", "Vin Blanc"),
    ("beer_mug_foam", "glass beer mug with foam", (30, 40), ["vetro", "bevanda", "bar", "piccolo"], "Beer Mug", "Boccale di Birra", "Bierkrug", "Jarra de Cerveza", "Chope de Bière"),
    ("whiskey_bottle", "square whiskey bottle, amber, no label", (20, 50), ["vetro", "bevanda", "bar", "piccolo"], "Whiskey Bottle", "Bottiglia di Whisky", "Whiskyflasche", "Botella de Whisky", "Bouteille de Whisky"),
    ("champagne_bottle", "dark champagne bottle with a foil top, no label", (20, 60), ["vetro", "bevanda", "piccolo"], "Champagne Bottle", "Bottiglia di Spumante", "Sektflasche", "Botella de Cava", "Bouteille de Champagne"),
    ("sake_set", "ceramic sake bottle with two small cups", (40, 30), ["ceramica", "bevanda", "piccolo"], "Sake Set", "Servizio da Sakè", "Sake-Set", "Juego de Sake", "Service à Saké"),
    ("water_jug_clay", "terracotta water jug", (30, 45), ["ceramica", "bevanda", "medio"], "Clay Jug", "Brocca di Terracotta", "Tonkrug", "Botijo", "Cruche en Terre"),
    ("soda_bottle_glass", "classic glass soda bottle, no label", (15, 45), ["vetro", "bevanda", "piccolo"], "Soda Bottle", "Bottiglietta di Bibita", "Limoflasche", "Botella de Refresco", "Bouteille de Soda"),
    ("juice_box_v2", "small juice box with a straw, plain", (15, 30), ["carta", "bevanda", "piccolo"], "Juice Box", "Succo in Brick", "Saftpackung", "Zumo en Brik", "Brique de Jus"),
    ("baguette_sandwich", "baguette sandwich with ham and lettuce", (60, 20), ["cibo", "piccolo"], "Sandwich", "Panino", "Sandwich", "Bocadillo", "Sandwich"),
    ("club_sandwich", "triangle club sandwich with a toothpick", (30, 30), ["cibo", "piccolo"], "Club Sandwich", "Tramezzino", "Club-Sandwich", "Sándwich Club", "Club Sandwich"),
    ("hot_dog", "hot dog with mustard", (45, 20), ["cibo", "piccolo"], "Hot Dog", "Hot Dog", "Hotdog", "Perrito Caliente", "Hot-dog"),
    ("french_fries", "cone of french fries", (25, 40), ["cibo", "piccolo"], "French Fries", "Patatine Fritte", "Pommes", "Patatas Fritas", "Frites"),
    ("spaghetti_plate", "plate of spaghetti with tomato sauce", (45, 25), ["ceramica", "cibo", "piccolo"], "Spaghetti", "Spaghetti", "Spaghetti", "Espaguetis", "Spaghettis"),
    ("lasagna_dish", "baking dish of lasagna", (50, 30), ["ceramica", "cibo", "medio"], "Lasagna", "Lasagne", "Lasagne", "Lasaña", "Lasagnes"),
    ("roast_chicken", "roast chicken on a plate", (50, 30), ["ceramica", "cibo", "medio"], "Roast Chicken", "Pollo Arrosto", "Brathähnchen", "Pollo Asado", "Poulet Rôti"),
    ("steak_plate", "grilled steak on a wooden board", (45, 25), ["legno", "cibo", "piccolo"], "Steak", "Bistecca", "Steak", "Filete", "Steak"),
    ("fried_egg_pan", "fried egg in a small pan", (40, 20), ["metallo", "cibo", "piccolo"], "Fried Egg", "Uovo Fritto", "Spiegelei", "Huevo Frito", "Œuf au Plat"),
    ("bacon_strips", "few crispy bacon strips", (40, 15), ["cibo", "piccolo"], "Bacon", "Pancetta Croccante", "Speck", "Beicon", "Bacon"),
    ("sausage_links", "few grilled sausages", (40, 20), ["cibo", "piccolo"], "Sausages", "Salsicce", "Würstchen", "Salchichas", "Saucisses"),
    ("ham_leg", "cured ham leg", (60, 30), ["cibo", "medio"], "Cured Ham", "Prosciutto", "Schinken", "Jamón", "Jambon"),
    ("salmon_fillet", "raw salmon fillet on paper", (45, 20), ["cibo", "piccolo"], "Salmon", "Filetto di Salmone", "Lachsfilet", "Salmón", "Saumon"),
    ("shrimp_bowl", "bowl of cooked shrimp", (35, 20), ["ceramica", "cibo", "piccolo"], "Shrimp", "Gamberi", "Garnelen", "Gambas", "Crevettes"),
    ("lobster_red", "cooked red lobster", (55, 30), ["cibo", "medio"], "Lobster", "Aragosta", "Hummer", "Langosta", "Homard"),
    ("oysters_plate", "few oysters on ice", (40, 25), ["cibo", "piccolo"], "Oysters", "Ostriche", "Austern", "Ostras", "Huîtres"),
    ("fish_whole", "whole fresh fish", (55, 20), ["cibo", "natura", "piccolo"], "Fresh Fish", "Pesce Fresco", "Frischer Fisch", "Pescado Fresco", "Poisson Frais"),
    ("cheese_wedge_holes", "wedge of cheese with holes", (35, 25), ["cibo", "piccolo"], "Cheese Wedge", "Spicchio di Formaggio", "Käsestück", "Cuña de Queso", "Part de Fromage"),
    ("brie_round", "round of brie cheese cut", (35, 20), ["cibo", "piccolo"], "Brie", "Brie", "Brie", "Brie", "Brie"),
    ("mozzarella_ball", "ball of fresh mozzarella", (25, 20), ["cibo", "piccolo"], "Mozzarella", "Mozzarella", "Mozzarella", "Mozzarella", "Mozzarella"),
    ("butter_block", "block of butter on paper", (30, 15), ["cibo", "piccolo"], "Butter", "Panetto di Burro", "Butter", "Mantequilla", "Beurre"),
    ("yogurt_cup", "cup of yogurt with a spoon, plain", (20, 25), ["plastica", "cibo", "piccolo"], "Yogurt", "Yogurt", "Joghurt", "Yogur", "Yaourt"),
    ("cake_slice_chocolate", "slice of chocolate cake", (30, 25), ["cibo", "piccolo"], "Chocolate Cake", "Fetta di Torta", "Schokoladenkuchen", "Tarta de Chocolate", "Gâteau au Chocolat"),
    ("pie_apple", "whole apple pie with a lattice crust", (45, 20), ["cibo", "piccolo"], "Apple Pie", "Crostata di Mele", "Apfelkuchen", "Tarta de Manzana", "Tarte aux Pommes"),
    ("cookies_plate", "plate of chocolate chip cookies", (40, 20), ["ceramica", "cibo", "piccolo"], "Cookies", "Biscotti", "Kekse", "Galletas", "Cookies"),
    ("brownie_square", "square chocolate brownie", (25, 15), ["cibo", "piccolo"], "Brownie", "Brownie", "Brownie", "Brownie", "Brownie"),
    ("eclair", "chocolate eclair pastry", (35, 12), ["cibo", "piccolo"], "Eclair", "Bignè Allungato", "Eclair", "Pepito", "Éclair"),
    ("cannoli", "two italian cannoli pastries", (40, 15), ["cibo", "piccolo"], "Cannoli", "Cannoli", "Cannoli", "Cannoli", "Cannoli"),
    ("tiramisu_glass", "tiramisu in a glass", (20, 30), ["vetro", "cibo", "piccolo"], "Tiramisu", "Tiramisù", "Tiramisu", "Tiramisú", "Tiramisu"),
    ("gelato_cup", "cup of gelato with a spoon", (20, 25), ["cibo", "piccolo"], "Gelato", "Coppetta di Gelato", "Eisbecher", "Helado", "Glace"),
    ("chocolate_box", "open box of assorted chocolates", (45, 25), ["carta", "cibo", "piccolo"], "Chocolate Box", "Scatola di Cioccolatini", "Pralinenschachtel", "Caja de Bombones", "Boîte de Chocolats"),
    ("candy_cane", "red and white candy cane", (15, 45), ["cibo", "piccolo"], "Candy Cane", "Bastoncino di Zucchero", "Zuckerstange", "Bastón de Caramelo", "Sucre d'Orge"),
    ("gingerbread_man", "gingerbread man cookie", (25, 30), ["cibo", "piccolo"], "Gingerbread", "Omino di Pan di Zenzero", "Lebkuchenmann", "Galleta de Jengibre", "Bonhomme en Pain d'Épices"),
    ("honey_pot_ceramic", "ceramic honey pot with a dipper", (25, 30), ["ceramica", "cibo", "piccolo"], "Honey Pot", "Vasetto del Miele", "Honigtopf", "Tarro de Miel", "Pot à Miel"),
    ("jam_toast", "slice of toast with jam", (30, 25), ["cibo", "piccolo"], "Toast", "Fetta Tostata", "Toast", "Tostada", "Tartine"),
    ("cinnamon_rolls", "two cinnamon rolls", (35, 20), ["cibo", "piccolo"], "Cinnamon Rolls", "Girelle alla Cannella", "Zimtschnecken", "Rollos de Canela", "Roulés à la Cannelle"),
    ("bagel", "sesame bagel", (25, 25), ["cibo", "piccolo"], "Bagel", "Bagel", "Bagel", "Bagel", "Bagel"),
    ("muffin_blueberry", "blueberry muffin", (25, 25), ["cibo", "piccolo"], "Muffin", "Muffin", "Muffin", "Magdalena", "Muffin"),
    ("rice_bowl", "bowl of white rice with chopsticks", (35, 20), ["ceramica", "cibo", "piccolo"], "Rice Bowl", "Ciotola di Riso", "Reisschale", "Cuenco de Arroz", "Bol de Riz"),
    ("ramen_bowl", "bowl of ramen noodles with an egg", (40, 25), ["ceramica", "cibo", "piccolo"], "Ramen", "Ramen", "Ramen", "Ramen", "Ramen"),
    ("dumplings_plate", "plate of dumplings", (40, 20), ["ceramica", "cibo", "piccolo"], "Dumplings", "Ravioli al Vapore", "Teigtaschen", "Empanadillas", "Raviolis"),
    ("spring_rolls", "few fried spring rolls", (40, 15), ["cibo", "piccolo"], "Spring Rolls", "Involtini Primavera", "Frühlingsrollen", "Rollitos", "Nems"),
    ("curry_bowl", "bowl of curry with rice", (40, 25), ["ceramica", "cibo", "piccolo"], "Curry", "Curry", "Curry", "Curry", "Curry"),
    ("burrito", "wrapped burrito cut in half", (40, 20), ["cibo", "piccolo"], "Burrito", "Burrito", "Burrito", "Burrito", "Burrito"),
    ("nachos_plate", "plate of nachos with cheese", (40, 20), ["cibo", "piccolo"], "Nachos", "Nachos", "Nachos", "Nachos", "Nachos"),
    ("paella_pan", "pan of paella", (55, 20), ["metallo", "cibo", "medio"], "Paella", "Paella", "Paella", "Paella", "Paella"),
    ("pizza_whole", "whole margherita pizza", (50, 15), ["cibo", "medio"], "Pizza", "Pizza Margherita", "Pizza", "Pizza", "Pizza"),
    ("kebab_skewers", "few grilled meat skewers", (50, 15), ["cibo", "piccolo"], "Skewers", "Spiedini", "Spieße", "Brochetas", "Brochettes"),
    ("salad_bowl_green_free", "bowl of salad with tomatoes and cheese", (40, 25), ["ceramica", "cibo", "piccolo"], "Salad", "Insalata", "Salat", "Ensalada", "Salade"),
    ("soup_bowl_tomato", "bowl of tomato soup", (35, 20), ["ceramica", "cibo", "piccolo"], "Tomato Soup", "Zuppa di Pomodoro", "Tomatensuppe", "Sopa de Tomate", "Soupe de Tomates"),
    ("porridge_bowl", "bowl of porridge with berries", (35, 20), ["ceramica", "cibo", "piccolo"], "Porridge", "Porridge", "Haferbrei", "Gachas", "Porridge"),
    ("pickled_jar_cucumber", "jar of pickled cucumbers", (25, 40), ["vetro", "cibo", "piccolo"], "Pickles", "Cetrioli Sottaceto", "Essiggurken", "Pepinillos", "Cornichons"),
    ("peanut_butter_jar", "jar of peanut butter, plain", (25, 30), ["vetro", "cibo", "piccolo"], "Peanut Butter", "Burro d'Arachidi", "Erdnussbutter", "Mantequilla de Cacahuete", "Beurre de Cacahuète"),
    ("spice_sack_chili", "small sack of red chili peppers", (35, 30), ["stoffa", "cibo", "piccolo"], "Chili Sack", "Sacchetto di Peperoncini", "Chilisack", "Saco de Chiles", "Sac de Piments"),
]
C = [(r[0], r[1], r[2], r[3], list(r[4:9])) for r in _ROWS]
