"""Two hundred generic objects for the global real catalog, any period and setting.
Compact rows: (id, prompt, (w, h), tags, en, it, de, es, fr). No character, brand,
place or readable text; no green objects. Duplicates of the catalogs are dropped
by the check below, then the first 200 kept.
"""

_ROWS = [
    # kitchen and table
    ("salad_bowl_wood", "wooden salad bowl with servers", (50, 30), ["legno", "cucina", "medio"], "Salad Bowl", "Insalatiera", "Salatschüssel", "Ensaladera", "Saladier"),
    ("soup_ladle_steel", "stainless steel soup ladle", (20, 55), ["metallo", "cucina", "piccolo"], "Soup Ladle", "Mestolo", "Suppenkelle", "Cucharón", "Louche"),
    ("spatula_wooden", "wooden cooking spatula", (15, 55), ["legno", "cucina", "piccolo"], "Wooden Spatula", "Spatola di Legno", "Holzspatel", "Espátula de Madera", "Spatule en Bois"),
    ("frying_pan_nonstick", "black non stick frying pan", (70, 35), ["metallo", "cucina", "medio"], "Frying Pan", "Padella Antiaderente", "Bratpfanne", "Sartén", "Poêle"),
    ("stock_pot_steel", "stainless steel stock pot with a lid", (50, 45), ["metallo", "cucina", "medio"], "Stock Pot", "Pentola", "Suppentopf", "Olla", "Marmite"),
    ("tea_kettle_red", "red enamel stovetop tea kettle", (40, 40), ["metallo", "cucina", "medio"], "Tea Kettle", "Bollitore Rosso", "Teekessel", "Tetera Roja", "Bouilloire Rouge"),
    ("wine_bottle_red", "dark glass red wine bottle with a cork, no label", (20, 60), ["vetro", "bevanda", "piccolo"], "Wine Bottle", "Bottiglia di Vino", "Weinflasche", "Botella de Vino", "Bouteille de Vin"),
    ("beer_bottle_brown", "brown glass beer bottle, no label", (15, 45), ["vetro", "bevanda", "piccolo"], "Beer Bottle", "Bottiglia di Birra", "Bierflasche", "Botella de Cerveza", "Bouteille de Bière"),
    ("champagne_flute", "empty crystal champagne flute", (15, 45), ["vetro", "bevanda", "piccolo"], "Champagne Flute", "Flute", "Sektglas", "Copa de Champán", "Flûte"),
    ("tumbler_glass", "empty heavy whisky tumbler glass", (25, 25), ["vetro", "bevanda", "piccolo"], "Tumbler", "Bicchiere da Whisky", "Whiskyglas", "Vaso Bajo", "Verre à Whisky"),
    ("ice_bucket_steel", "stainless steel ice bucket with tongs", (35, 35), ["metallo", "bar", "piccolo"], "Ice Bucket", "Secchiello del Ghiaccio", "Eiskübel", "Cubo de Hielo", "Seau à Glace"),
    ("cheese_board_knife", "small wooden cheese board with a cheese knife", (50, 30), ["legno", "cucina", "medio"], "Cheese Board", "Tagliere dei Formaggi", "Käsebrett", "Tabla de Quesos", "Plateau à Fromage"),
    ("bread_knife", "serrated bread knife with a wooden handle", (70, 15), ["metallo", "cucina", "medio"], "Bread Knife", "Coltello da Pane", "Brotmesser", "Cuchillo de Pan", "Couteau à Pain"),
    ("garlic_press", "stainless steel garlic press", (40, 15), ["metallo", "cucina", "piccolo"], "Garlic Press", "Spremiaglio", "Knoblauchpresse", "Prensa de Ajos", "Presse-ail"),
    ("can_opener", "manual can opener with red handles", (40, 20), ["metallo", "cucina", "piccolo"], "Can Opener", "Apriscatole", "Dosenöffner", "Abrelatas", "Ouvre-boîte"),
    ("kitchen_timer_egg", "white plastic egg shaped kitchen timer", (20, 25), ["plastica", "cucina", "piccolo"], "Kitchen Timer", "Timer da Cucina", "Küchenwecker", "Temporizador", "Minuteur"),
    ("honey_dipper", "wooden honey dipper", (12, 40), ["legno", "cucina", "piccolo"], "Honey Dipper", "Mestolino del Miele", "Honiglöffel", "Cuchara de Miel", "Cuillère à Miel"),
    ("sugar_jar_glass", "glass sugar jar with a metal lid", (25, 35), ["vetro", "cucina", "piccolo"], "Sugar Jar", "Barattolo dello Zucchero", "Zuckerglas", "Azucarero de Vidrio", "Pot à Sucre"),
    ("spice_jars_rack", "small wooden rack with three spice jars", (45, 30), ["legno", "vetro", "cucina", "piccolo"], "Spice Rack", "Portaspezie", "Gewürzregal", "Especiero", "Étagère à Épices"),
    ("pizza_cutter", "pizza cutter wheel", (15, 40), ["metallo", "cucina", "piccolo"], "Pizza Cutter", "Rotella per Pizza", "Pizzaschneider", "Cortapizzas", "Roulette à Pizza"),
    ("ice_cream_scoop", "stainless steel ice cream scoop", (15, 45), ["metallo", "cucina", "piccolo"], "Ice Cream Scoop", "Porzionatore da Gelato", "Eisportionierer", "Cuchara de Helado", "Cuillère à Glace"),
    ("baking_tray", "dark metal baking tray", (65, 20), ["metallo", "cucina", "medio"], "Baking Tray", "Teglia", "Backblech", "Bandeja de Horno", "Plaque de Cuisson"),
    ("muffin_tin", "metal six cup muffin tin", (55, 20), ["metallo", "cucina", "medio"], "Muffin Tin", "Stampo per Muffin", "Muffinform", "Molde de Magdalenas", "Moule à Muffins"),
    ("thermos_modern", "modern stainless steel thermos flask", (15, 50), ["metallo", "bevanda", "piccolo"], "Thermos", "Termos", "Thermoskanne", "Termo", "Thermos"),
    ("paper_coffee_cup", "plain paper takeaway coffee cup with a lid", (20, 30), ["carta", "bevanda", "piccolo"], "Coffee Cup", "Bicchiere del Caffè", "Kaffeebecher", "Vaso de Café", "Gobelet"),
    ("drinking_straws", "few striped paper drinking straws", (15, 45), ["carta", "bevanda", "piccolo"], "Straws", "Cannucce", "Strohhalme", "Pajitas", "Pailles"),
    ("napkin_holder", "metal napkin holder with napkins", (30, 25), ["metallo", "cucina", "piccolo"], "Napkin Holder", "Portatovaglioli", "Serviettenhalter", "Servilletero", "Porte-serviettes"),
    ("toothpick_holder", "small wooden toothpick holder", (15, 20), ["legno", "cucina", "piccolo"], "Toothpick Holder", "Portastuzzicadenti", "Zahnstocherhalter", "Palillero", "Porte-cure-dents"),
    ("olive_bowl", "small ceramic bowl of green-black olives", (30, 20), ["ceramica", "cibo", "piccolo"], "Bowl of Olives", "Ciotola di Olive", "Olivenschale", "Cuenco de Aceitunas", "Bol d'Olives"),
    ("croissant", "golden croissant", (35, 20), ["cibo", "piccolo"], "Croissant", "Cornetto", "Croissant", "Cruasán", "Croissant"),
    ("baguette", "french baguette bread", (80, 15), ["cibo", "medio"], "Baguette", "Baguette", "Baguette", "Barra de Pan", "Baguette"),
    ("pretzel", "soft baked pretzel with salt", (35, 30), ["cibo", "piccolo"], "Pretzel", "Pretzel", "Brezel", "Pretzel", "Bretzel"),
    ("donut_glazed", "glazed ring donut", (30, 30), ["cibo", "piccolo"], "Donut", "Ciambella", "Donut", "Dónut", "Beignet"),
    ("cupcake", "cupcake with white frosting", (25, 30), ["cibo", "piccolo"], "Cupcake", "Cupcake", "Cupcake", "Magdalena", "Cupcake"),
    ("chocolate_bar", "bar of dark chocolate partly unwrapped, plain foil", (40, 20), ["cibo", "piccolo"], "Chocolate Bar", "Tavoletta di Cioccolato", "Schokoladentafel", "Tableta de Chocolate", "Tablette de Chocolat"),
    ("lemon_fruit", "single yellow lemon", (25, 20), ["cibo", "natura", "piccolo"], "Lemon", "Limone", "Zitrone", "Limón", "Citron"),
    ("orange_fruit", "single orange fruit", (25, 25), ["cibo", "natura", "piccolo"], "Orange", "Arancia", "Orange", "Naranja", "Orange"),
    ("banana_bunch", "small bunch of ripe bananas", (45, 30), ["cibo", "natura", "piccolo"], "Bananas", "Banane", "Bananen", "Plátanos", "Bananes"),
    ("grapes_bunch_red", "bunch of red grapes", (30, 40), ["cibo", "natura", "piccolo"], "Grapes", "Grappolo d'Uva", "Weintrauben", "Uvas", "Raisins"),
    ("pomegranate", "whole pomegranate", (25, 25), ["cibo", "natura", "piccolo"], "Pomegranate", "Melagrana", "Granatapfel", "Granada", "Grenade"),
    ("coconut", "whole brown coconut", (30, 30), ["cibo", "natura", "piccolo"], "Coconut", "Noce di Cocco", "Kokosnuss", "Coco", "Noix de Coco"),
    ("pumpkin_small", "small orange pumpkin", (35, 30), ["cibo", "natura", "autunno", "piccolo"], "Pumpkin", "Zucca", "Kürbis", "Calabaza", "Citrouille"),
    ("corn_cob", "ear of corn partly husked", (20, 50), ["cibo", "natura", "piccolo"], "Corn Cob", "Pannocchia", "Maiskolben", "Mazorca", "Épi de Maïs"),
    ("carrot_bunch", "bunch of orange carrots with tops cut", (45, 25), ["cibo", "natura", "piccolo"], "Carrots", "Carote", "Karotten", "Zanahorias", "Carottes"),
    ("egg_carton", "cardboard egg carton open with six eggs", (45, 25), ["carta", "cibo", "piccolo"], "Egg Carton", "Confezione di Uova", "Eierkarton", "Huevera de Cartón", "Boîte d'Œufs"),
    ("milk_carton", "plain white milk carton, no text", (20, 40), ["carta", "bevanda", "piccolo"], "Milk Carton", "Cartone del Latte", "Milchtüte", "Cartón de Leche", "Brique de Lait"),
    ("cereal_bowl", "bowl of cereal with a spoon", (35, 25), ["ceramica", "cibo", "piccolo"], "Cereal Bowl", "Tazza di Cereali", "Müslischale", "Tazón de Cereales", "Bol de Céréales"),
    ("sushi_plate", "small plate of sushi rolls with chopsticks", (45, 25), ["ceramica", "cibo", "piccolo"], "Sushi", "Piatto di Sushi", "Sushi", "Sushi", "Sushi"),
    ("chopsticks_pair", "pair of wooden chopsticks on a rest", (50, 10), ["legno", "cucina", "piccolo"], "Chopsticks", "Bacchette", "Essstäbchen", "Palillos", "Baguettes"),
    ("teapot_cast_iron", "black cast iron asian teapot", (35, 30), ["ferro", "cucina", "bevanda", "piccolo"], "Iron Teapot", "Teiera di Ghisa", "Gusseisen-Teekanne", "Tetera de Hierro", "Théière en Fonte"),
    # home and furniture
    ("table_lamp_modern", "modern white table lamp with a fabric shade", (35, 55), ["luce", "arredamento", "medio"], "Modern Lamp", "Lampada Moderna", "Moderne Lampe", "Lámpara Moderna", "Lampe Moderne"),
    ("floor_vase_ceramic", "tall grey ceramic floor vase, empty", (30, 70), ["ceramica", "arredamento", "medio"], "Tall Vase", "Vaso Alto", "Bodenvase", "Jarrón Alto", "Grand Vase"),
    ("picture_frame_blank", "empty wooden picture frame", (40, 50), ["legno", "arredamento", "medio"], "Empty Frame", "Cornice Vuota", "Leerer Rahmen", "Marco Vacío", "Cadre Vide"),
    ("wall_clock_modern", "modern round wall clock with a white face", (40, 40), ["plastica", "arredamento", "medio"], "Wall Clock", "Orologio da Muro", "Wanduhr", "Reloj de Pared", "Horloge"),
    ("door_mat", "brown coir door mat, plain", (60, 35), ["arredamento", "medio"], "Door Mat", "Zerbino", "Fußmatte", "Felpudo", "Paillasson"),
    ("coat_hook_modern", "wall coat hook rail with three hooks", (55, 20), ["metallo", "arredamento", "piccolo"], "Coat Rail", "Appendiabiti a Muro", "Garderobenleiste", "Perchero", "Portemanteau"),
    ("storage_basket_woven", "woven storage basket", (45, 35), ["legno", "arredamento", "contenitore", "medio"], "Woven Basket", "Cesto Intrecciato", "Flechtkorb", "Cesta Tejida", "Panier Tressé"),
    ("laundry_basket", "plastic laundry basket with clothes", (55, 40), ["plastica", "contenitore", "medio"], "Laundry Basket", "Cesta del Bucato", "Wäschekorb", "Cesto de Ropa", "Panier à Linge"),
    ("clothes_pegs", "few wooden clothes pegs", (35, 20), ["legno", "piccolo"], "Clothes Pegs", "Mollette", "Wäscheklammern", "Pinzas", "Pinces à Linge"),
    ("iron_modern", "modern steam clothes iron", (45, 25), ["plastica", "tecnologia", "medio"], "Steam Iron", "Ferro a Vapore", "Dampfbügeleisen", "Plancha de Vapor", "Fer à Vapeur"),
    ("broom_straw", "straw broom", (25, 90), ["legno", "attrezzo", "grande"], "Broom", "Scopa", "Besen", "Escoba", "Balai"),
    ("dustpan_brush", "dustpan and small brush", (45, 25), ["plastica", "attrezzo", "piccolo"], "Dustpan", "Paletta e Scopino", "Kehrschaufel", "Recogedor", "Pelle et Balayette"),
    ("mop_bucket_small", "mop with a small bucket", (40, 70), ["plastica", "attrezzo", "medio"], "Mop", "Mocio", "Wischmopp", "Fregona", "Serpillière"),
    ("rubber_gloves_yellow", "pair of yellow rubber cleaning gloves", (40, 40), ["plastica", "bagno", "piccolo"], "Yellow Gloves", "Guanti Gialli", "Gelbe Handschuhe", "Guantes Amarillos", "Gants Jaunes"),
    ("trash_can_pedal", "stainless steel pedal trash can", (35, 50), ["metallo", "contenitore", "medio"], "Trash Can", "Pattumiera", "Mülleimer", "Cubo de Basura", "Poubelle"),
    ("light_switch_modern", "modern white light switch plate", (20, 25), ["plastica", "tecnologia", "piccolo"], "Light Switch", "Interruttore", "Lichtschalter", "Interruptor", "Interrupteur"),
    ("smoke_detector", "white ceiling smoke detector", (30, 30), ["plastica", "sicurezza", "piccolo"], "Smoke Detector", "Rilevatore di Fumo", "Rauchmelder", "Detector de Humo", "Détecteur de Fumée"),
    ("door_key_modern", "modern silver door key", (12, 35), ["metallo", "chiave", "piccolo"], "House Key", "Chiave di Casa", "Hausschlüssel", "Llave de Casa", "Clé de Maison"),
    ("padlock_brass_new", "shiny brass padlock", (25, 30), ["ottone", "sicurezza", "piccolo"], "Brass Padlock", "Lucchetto d'Ottone", "Messingschloss", "Candado de Latón", "Cadenas en Laiton"),
    ("wind_chime", "metal wind chime", (30, 60), ["metallo", "decorazione", "medio"], "Wind Chime", "Scacciapensieri", "Windspiel", "Carillón de Viento", "Carillon"),
    ("dream_catcher", "dream catcher with feathers", (35, 60), ["decorazione", "medio"], "Dream Catcher", "Acchiappasogni", "Traumfänger", "Atrapasueños", "Attrape-rêves"),
    ("snow_globe_winter", "glass snow globe with a tiny winter house", (30, 35), ["vetro", "decorazione", "piccolo"], "Snow Globe", "Palla di Neve", "Schneekugel", "Bola de Nieve", "Boule à Neige"),
    ("figurine_cat", "small ceramic cat figurine", (25, 35), ["ceramica", "decorazione", "piccolo"], "Cat Figurine", "Statuina di Gatto", "Katzenfigur", "Figura de Gato", "Figurine Chat"),
    ("wooden_elephant", "small carved wooden elephant", (35, 30), ["legno", "decorazione", "piccolo"], "Wooden Elephant", "Elefantino di Legno", "Holzelefant", "Elefante de Madera", "Éléphant en Bois"),
    ("incense_holder", "incense stick holder with a burning stick", (40, 15), ["legno", "decorazione", "piccolo"], "Incense Holder", "Portaincenso", "Räucherstäbchenhalter", "Incensario", "Porte-encens"),
    ("essential_oil_bottle", "small amber essential oil bottle with a dropper", (12, 30), ["vetro", "bellezza", "piccolo"], "Oil Dropper", "Contagocce", "Duftölfläschchen", "Gotero", "Flacon Compte-gouttes"),
    ("bonsai_tree", "small bonsai tree in a ceramic pot", (35, 35), ["ceramica", "natura", "piccolo"], "Bonsai", "Bonsai", "Bonsai", "Bonsái", "Bonsaï"),
    ("succulent_pot_trio", "three small succulents in pots", (45, 25), ["ceramica", "natura", "piccolo"], "Succulents", "Piante Grasse", "Sukkulenten", "Suculentas", "Plantes Grasses"),
    ("watering_can_metal", "galvanized metal watering can", (45, 40), ["metallo", "attrezzo", "medio"], "Metal Watering Can", "Annaffiatoio di Metallo", "Gießkanne", "Regadera", "Arrosoir"),
    ("garden_gloves", "pair of garden gloves", (40, 35), ["stoffa", "attrezzo", "piccolo"], "Garden Gloves", "Guanti da Giardino", "Gartenhandschuhe", "Guantes de Jardín", "Gants de Jardin"),
    ("bird_feeder", "wooden bird feeder with seeds", (35, 45), ["legno", "natura", "medio"], "Bird Feeder", "Mangiatoia", "Vogelfutterhaus", "Comedero", "Mangeoire"),
    ("flower_bouquet", "small bouquet of mixed flowers tied with twine", (30, 50), ["natura", "piccolo"], "Bouquet", "Mazzo di Fiori", "Blumenstrauß", "Ramo de Flores", "Bouquet"),
    ("sunflower", "single sunflower", (30, 60), ["natura", "piccolo"], "Sunflower", "Girasole", "Sonnenblume", "Girasol", "Tournesol"),
    ("rose_red", "single red rose", (15, 50), ["natura", "piccolo"], "Red Rose", "Rosa Rossa", "Rote Rose", "Rosa Roja", "Rose Rouge"),
    # office, school, tech
    ("desk_lamp_led", "modern black LED desk lamp", (35, 50), ["metallo", "luce", "ufficio", "medio"], "LED Desk Lamp", "Lampada LED", "LED-Schreibtischlampe", "Lámpara LED", "Lampe LED"),
    ("laptop_closed", "closed silver laptop, no logo", (60, 10), ["metallo", "tecnologia", "medio"], "Laptop", "Portatile", "Laptop", "Portátil", "Ordinateur Portable"),
    ("tablet_blank", "tablet computer with a black screen", (45, 60), ["tecnologia", "medio"], "Tablet", "Tablet", "Tablet", "Tableta", "Tablette"),
    ("smartphone_black", "black smartphone with a dark screen, no logo", (20, 40), ["tecnologia", "piccolo"], "Smartphone", "Smartphone", "Smartphone", "Teléfono Móvil", "Smartphone"),
    ("phone_charger", "white phone wall charger with cable", (30, 30), ["plastica", "tecnologia", "piccolo"], "Charger", "Caricatore", "Ladegerät", "Cargador", "Chargeur"),
    ("usb_stick", "silver USB flash drive", (15, 30), ["metallo", "tecnologia", "piccolo"], "USB Stick", "Chiavetta USB", "USB-Stick", "Memoria USB", "Clé USB"),
    ("external_hard_drive", "black external hard drive", (30, 40), ["plastica", "tecnologia", "piccolo"], "Hard Drive", "Disco Esterno", "Festplatte", "Disco Duro", "Disque Dur"),
    ("gaming_controller_black", "black game controller, no logo", (40, 25), ["plastica", "tecnologia", "gioco", "piccolo"], "Gamepad", "Gamepad", "Gamepad", "Mando", "Manette"),
    ("vr_headset", "white virtual reality headset", (45, 30), ["plastica", "tecnologia", "medio"], "VR Headset", "Visore VR", "VR-Brille", "Gafas VR", "Casque VR"),
    ("drone_small", "small grey camera drone", (50, 40), ["plastica", "tecnologia", "medio"], "Drone", "Drone", "Drohne", "Dron", "Drone"),
    ("action_camera", "small black action camera", (25, 20), ["plastica", "tecnologia", "piccolo"], "Action Camera", "Action Cam", "Actionkamera", "Cámara Deportiva", "Caméra Sport"),
    ("dslr_camera", "black DSLR camera with a lens, no logo", (45, 35), ["tecnologia", "foto", "medio"], "DSLR Camera", "Reflex", "Spiegelreflexkamera", "Cámara Réflex", "Appareil Reflex"),
    ("camera_lens", "black camera lens", (30, 35), ["vetro", "tecnologia", "foto", "piccolo"], "Camera Lens", "Obiettivo", "Objektiv", "Objetivo", "Objectif"),
    ("bluetooth_speaker", "small round bluetooth speaker", (30, 30), ["plastica", "tecnologia", "musica", "piccolo"], "Speaker", "Cassa Bluetooth", "Lautsprecher", "Altavoz", "Enceinte"),
    ("headphones_over_ear", "black over ear headphones", (45, 40), ["plastica", "tecnologia", "musica", "medio"], "Headphones", "Cuffie", "Kopfhörer", "Auriculares", "Casque Audio"),
    ("microphone_desk", "desk podcast microphone on a stand", (25, 50), ["metallo", "tecnologia", "musica", "medio"], "Desk Mic", "Microfono da Tavolo", "Tischmikrofon", "Micrófono de Mesa", "Micro de Bureau"),
    ("electric_toothbrush", "white electric toothbrush", (10, 50), ["plastica", "bagno", "tecnologia", "piccolo"], "Electric Toothbrush", "Spazzolino Elettrico", "Elektrische Zahnbürste", "Cepillo Eléctrico", "Brosse Électrique"),
    ("hair_clipper", "black electric hair clipper", (20, 45), ["plastica", "bellezza", "tecnologia", "piccolo"], "Hair Clipper", "Tagliacapelli", "Haarschneider", "Cortapelos", "Tondeuse"),
    ("calculator_scientific", "scientific calculator, blank display", (30, 50), ["plastica", "studio", "tecnologia", "piccolo"], "Scientific Calculator", "Calcolatrice Scientifica", "Taschenrechner", "Calculadora Científica", "Calculatrice Scientifique"),
    ("globe_desk_modern", "modern desk globe on a metal stand", (35, 45), ["metallo", "studio", "medio"], "Desk Globe", "Mappamondo da Scrivania", "Tischglobus", "Globo de Escritorio", "Globe de Bureau"),
    ("pencil_sharpener", "metal pencil sharpener", (15, 10), ["metallo", "studio", "piccolo"], "Sharpener", "Temperamatite", "Spitzer", "Sacapuntas", "Taille-crayon"),
    ("eraser_pink", "pink rubber eraser", (20, 10), ["plastica", "studio", "piccolo"], "Eraser", "Gomma", "Radiergummi", "Goma", "Gomme"),
    ("colored_pencils", "few colored pencils", (45, 20), ["legno", "arte", "studio", "piccolo"], "Colored Pencils", "Matite Colorate", "Buntstifte", "Lápices de Colores", "Crayons de Couleur"),
    ("watercolor_box", "open box of watercolor paints with a brush", (45, 25), ["arte", "piccolo"], "Watercolors", "Acquerelli", "Wasserfarben", "Acuarelas", "Aquarelles"),
    ("sketchbook", "closed black sketchbook with an elastic", (40, 50), ["carta", "arte", "medio"], "Sketchbook", "Album da Disegno", "Skizzenbuch", "Cuaderno de Dibujo", "Carnet de Croquis"),
    ("envelope_brown", "brown kraft envelope, blank", (45, 30), ["carta", "ufficio", "piccolo"], "Envelope", "Busta", "Umschlag", "Sobre", "Enveloppe"),
    ("cardboard_box_small", "small closed cardboard box with tape", (45, 35), ["carta", "contenitore", "medio"], "Cardboard Box", "Scatola di Cartone", "Pappkarton", "Caja de Cartón", "Carton"),
    ("bubble_wrap_roll", "roll of bubble wrap", (35, 35), ["plastica", "piccolo"], "Bubble Wrap", "Pluriball", "Luftpolsterfolie", "Plástico de Burbujas", "Papier Bulle"),
    ("packing_tape_roll", "roll of brown packing tape", (25, 25), ["plastica", "ufficio", "piccolo"], "Packing Tape", "Nastro da Pacchi", "Paketband", "Cinta de Embalar", "Ruban Adhésif"),
    ("hole_punch_modern", "black two hole paper punch", (35, 20), ["metallo", "ufficio", "piccolo"], "Paper Punch", "Perforatrice", "Locher", "Perforadora", "Perforatrice"),
    ("clipboard", "wooden clipboard with a blank sheet", (35, 45), ["legno", "carta", "ufficio", "medio"], "Clipboard", "Portablocco", "Klemmbrett", "Portapapeles", "Porte-bloc"),
    ("rubber_bands", "few coloured rubber bands", (25, 20), ["plastica", "ufficio", "piccolo"], "Rubber Bands", "Elastici", "Gummibänder", "Gomas Elásticas", "Élastiques"),
    ("pushpins_box", "small box of coloured push pins", (25, 20), ["plastica", "ufficio", "piccolo"], "Push Pins", "Puntine", "Pinnnadeln", "Chinchetas", "Punaises"),
    ("name_badge_blank", "blank name badge with a clip", (30, 20), ["plastica", "ufficio", "piccolo"], "Name Badge", "Badge", "Namensschild", "Identificador", "Badge"),
    ("id_lanyard", "blue lanyard with a blank card holder", (25, 50), ["stoffa", "ufficio", "piccolo"], "Lanyard", "Cordino Porta Badge", "Umhängeband", "Cinta Porta Tarjeta", "Tour de Cou"),
    # tools, garage, safety
    ("hammer_claw", "claw hammer with a wooden handle", (30, 55), ["metallo", "legno", "attrezzo", "medio"], "Claw Hammer", "Martello da Carpentiere", "Klauenhammer", "Martillo", "Marteau"),
    ("screwdriver_set", "set of screwdrivers with red handles", (45, 35), ["metallo", "attrezzo", "piccolo"], "Screwdrivers", "Cacciaviti", "Schraubendreher", "Destornilladores", "Tournevis"),
    ("pliers_red", "pliers with red handles", (20, 45), ["metallo", "attrezzo", "piccolo"], "Pliers", "Pinze", "Zange", "Alicates", "Pince"),
    ("allen_keys", "set of allen hex keys", (35, 30), ["metallo", "attrezzo", "piccolo"], "Allen Keys", "Chiavi a Brugola", "Inbusschlüssel", "Llaves Allen", "Clés Allen"),
    ("tape_measure_yellow", "yellow tape measure", (25, 25), ["plastica", "attrezzo", "piccolo"], "Tape Measure", "Metro a Nastro", "Maßband", "Flexómetro", "Mètre Ruban"),
    ("utility_knife_yellow", "yellow box cutter utility knife", (40, 15), ["plastica", "metallo", "attrezzo", "piccolo"], "Box Cutter", "Taglierino", "Cuttermesser", "Cúter", "Cutter"),
    ("cordless_drill", "yellow cordless drill, no logo", (45, 45), ["plastica", "attrezzo", "tecnologia", "medio"], "Cordless Drill", "Trapano Avvitatore", "Akkuschrauber", "Taladro", "Perceuse"),
    ("paint_roller_tray", "paint roller in a tray", (50, 30), ["plastica", "attrezzo", "medio"], "Paint Roller", "Rullo con Vaschetta", "Farbroller", "Rodillo", "Rouleau"),
    ("duct_tape_grey", "roll of grey duct tape", (25, 25), ["plastica", "attrezzo", "piccolo"], "Duct Tape", "Nastro Americano", "Gewebeband", "Cinta Americana", "Ruban Adhésif Gris"),
    ("work_gloves", "pair of leather work gloves", (40, 35), ["cuoio", "attrezzo", "piccolo"], "Work Gloves", "Guanti da Lavoro", "Arbeitshandschuhe", "Guantes de Trabajo", "Gants de Travail"),
    ("safety_goggles", "clear safety goggles", (40, 20), ["plastica", "sicurezza", "piccolo"], "Safety Goggles", "Occhiali Protettivi", "Schutzbrille", "Gafas de Seguridad", "Lunettes de Protection"),
    ("hard_hat_yellow", "yellow construction hard hat", (40, 30), ["plastica", "sicurezza", "medio"], "Hard Hat", "Casco da Cantiere", "Bauhelm", "Casco de Obra", "Casque de Chantier"),
    ("traffic_cone_small", "small orange traffic cone", (30, 40), ["plastica", "sicurezza", "piccolo"], "Traffic Cone", "Cono Stradale", "Leitkegel", "Cono", "Cône"),
    ("fire_blanket", "red fire blanket pouch", (30, 40), ["stoffa", "sicurezza", "piccolo"], "Fire Blanket", "Coperta Antifiamma", "Löschdecke", "Manta Ignífuga", "Couverture Anti-feu"),
    ("first_aid_box", "white first aid box with a red cross", (40, 30), ["plastica", "medicina", "sicurezza", "piccolo"], "First Aid Box", "Cassetta del Pronto Soccorso", "Verbandskasten", "Botiquín", "Trousse de Secours"),
    ("jerry_can", "red metal jerry can", (35, 45), ["metallo", "contenitore", "auto", "medio"], "Jerry Can", "Tanica", "Benzinkanister", "Bidón", "Jerrican"),
    ("car_keys", "car key with a fob and a ring, no logo", (25, 35), ["metallo", "chiave", "auto", "piccolo"], "Car Keys", "Chiavi dell'Auto", "Autoschlüssel", "Llaves del Coche", "Clés de Voiture"),
    ("jumper_cables", "coiled red and black jumper cables", (45, 35), ["metallo", "auto", "attrezzo", "medio"], "Jumper Cables", "Cavi per Batteria", "Starthilfekabel", "Cables de Arranque", "Câbles de Démarrage"),
    ("tire_valve_caps", "few metal tire valve caps", (20, 15), ["metallo", "auto", "piccolo"], "Valve Caps", "Tappi delle Valvole", "Ventilkappen", "Tapones de Válvula", "Bouchons de Valve"),
    ("bike_helmet", "blue bicycle helmet", (40, 30), ["plastica", "sport", "sicurezza", "medio"], "Bike Helmet", "Casco da Bici", "Fahrradhelm", "Casco de Bici", "Casque de Vélo"),
    ("bike_lock_chain", "bicycle chain lock with a padlock", (40, 35), ["metallo", "sicurezza", "sport", "piccolo"], "Bike Lock", "Catena per Bici", "Fahrradschloss", "Candado de Bici", "Antivol"),
    # sport and leisure
    ("soccer_ball", "classic black and white soccer ball", (30, 30), ["plastica", "sport", "piccolo"], "Soccer Ball", "Pallone da Calcio", "Fußball", "Balón de Fútbol", "Ballon de Foot"),
    ("basketball", "orange basketball", (30, 30), ["plastica", "sport", "piccolo"], "Basketball", "Pallone da Basket", "Basketball", "Balón de Baloncesto", "Ballon de Basket"),
    ("volleyball", "white volleyball", (30, 30), ["plastica", "sport", "piccolo"], "Volleyball", "Pallone da Pallavolo", "Volleyball", "Balón de Voleibol", "Ballon de Volley"),
    ("golf_ball_tee", "golf ball on a wooden tee", (20, 30), ["sport", "piccolo"], "Golf Ball", "Pallina da Golf", "Golfball", "Pelota de Golf", "Balle de Golf"),
    ("ping_pong_ball", "white ping pong ball", (15, 15), ["plastica", "sport", "piccolo"], "Ping Pong Ball", "Pallina da Ping Pong", "Tischtennisball", "Pelota de Ping Pong", "Balle de Ping-pong"),
    ("whistle_referee", "black plastic referee whistle on a lanyard", (25, 25), ["plastica", "sport", "piccolo"], "Referee Whistle", "Fischietto dell'Arbitro", "Schiedsrichterpfeife", "Silbato de Árbitro", "Sifflet d'Arbitre"),
    ("medal_gold_sport", "gold sport medal with a ribbon", (25, 40), ["metallo", "sport", "piccolo"], "Gold Medal", "Medaglia d'Oro", "Goldmedaille", "Medalla de Oro", "Médaille d'Or"),
    ("trophy_cup", "small golden trophy cup", (30, 45), ["metallo", "sport", "piccolo"], "Trophy", "Coppa", "Pokal", "Trofeo", "Trophée"),
    ("skipping_rope_speed", "thin speed rope with black handles", (40, 35), ["plastica", "sport", "piccolo"], "Speed Rope", "Corda Veloce", "Speed Rope", "Comba Rápida", "Corde Rapide"),
    ("resistance_band", "coiled red resistance band", (35, 30), ["plastica", "sport", "piccolo"], "Resistance Band", "Elastico Fitness", "Widerstandsband", "Banda Elástica", "Bande Élastique"),
    ("kettlebell", "black kettlebell", (30, 35), ["ferro", "sport", "piccolo"], "Kettlebell", "Kettlebell", "Kettlebell", "Pesa Rusa", "Kettlebell"),
    ("yoga_mat_rolled", "rolled purple yoga mat", (20, 55), ["plastica", "sport", "medio"], "Yoga Mat", "Tappetino Yoga", "Yogamatte", "Esterilla", "Tapis de Yoga"),
    ("fishing_lure", "colourful fishing lure with hooks", (35, 15), ["plastica", "sport", "piccolo"], "Fishing Lure", "Esca Artificiale", "Angelköder", "Señuelo", "Leurre"),
    ("compass_orienteering", "clear orienteering compass", (25, 35), ["plastica", "viaggio", "piccolo"], "Map Compass", "Bussola da Orientamento", "Kartenkompass", "Brújula de Mapa", "Boussole"),
    ("binoculars_modern", "black modern binoculars", (40, 30), ["tecnologia", "viaggio", "medio"], "Binoculars", "Binocolo", "Fernglas", "Prismáticos", "Jumelles"),
    ("sleeping_bag_rolled", "rolled green-free blue sleeping bag", (45, 30), ["stoffa", "viaggio", "medio"], "Sleeping Bag", "Sacco a Pelo", "Schlafsack", "Saco de Dormir", "Sac de Couchage"),
    ("camping_stove_gas", "small camping gas stove", (35, 30), ["metallo", "viaggio", "piccolo"], "Camp Stove", "Fornelletto", "Campingkocher", "Hornillo", "Réchaud"),
    ("lantern_led", "modern LED camping lantern", (25, 40), ["plastica", "luce", "viaggio", "piccolo"], "LED Lantern", "Lanterna LED", "LED-Laterne", "Farol LED", "Lanterne LED"),
    ("marshmallow_stick", "marshmallows on a roasting stick", (60, 15), ["cibo", "viaggio", "piccolo"], "Marshmallows", "Marshmallow", "Marshmallows", "Nubes", "Guimauves"),
    ("beach_towel_rolled", "rolled striped beach towel", (45, 25), ["stoffa", "viaggio", "piccolo"], "Beach Towel", "Telo Mare", "Strandtuch", "Toalla de Playa", "Serviette de Plage"),
    ("sunscreen_bottle", "plain white sunscreen bottle, no text", (15, 40), ["plastica", "bellezza", "piccolo"], "Sunscreen", "Crema Solare", "Sonnencreme", "Protector Solar", "Crème Solaire"),
    ("flip_flops", "pair of blue flip flops", (40, 45), ["plastica", "abbigliamento", "piccolo"], "Flip Flops", "Infradito", "Flip-Flops", "Chanclas", "Tongs"),
    ("straw_hat", "woven straw sun hat", (50, 20), ["abbigliamento", "cappello", "medio"], "Straw Hat", "Cappello di Paglia", "Strohhut", "Sombrero de Paja", "Chapeau de Paille"),
    ("sand_bucket_toy", "plastic sand bucket with a shovel", (30, 35), ["plastica", "giocattolo", "piccolo"], "Sand Bucket", "Secchiello", "Sandeimer", "Cubo de Arena", "Seau de Plage"),
    ("inflatable_ring", "inflatable swim ring, red and white", (45, 45), ["plastica", "giocattolo", "medio"], "Swim Ring", "Salvagente", "Schwimmring", "Flotador", "Bouée"),
    ("postcard_blank", "blank white postcard", (40, 25), ["carta", "viaggio", "piccolo"], "Postcard", "Cartolina", "Postkarte", "Postal", "Carte Postale"),
    ("passport_holder", "leather passport holder, closed", (30, 40), ["cuoio", "viaggio", "piccolo"], "Passport Holder", "Portapassaporto", "Passhülle", "Portapasaporte", "Porte-passeport"),
    ("suitcase_hardshell", "grey hard shell suitcase", (40, 60), ["plastica", "viaggio", "medio"], "Suitcase", "Valigia Rigida", "Hartschalenkoffer", "Maleta Rígida", "Valise Rigide"),
    ("travel_adapter", "white universal travel plug adapter", (25, 25), ["plastica", "tecnologia", "viaggio", "piccolo"], "Plug Adapter", "Adattatore da Viaggio", "Reiseadapter", "Adaptador", "Adaptateur"),
    # clothes and accessories
    ("sneakers_white", "pair of white sneakers", (55, 30), ["abbigliamento", "medio"], "White Sneakers", "Scarpe da Ginnastica", "Turnschuhe", "Zapatillas Blancas", "Baskets Blanches"),
    ("high_heels_black", "pair of black high heel shoes", (50, 35), ["cuoio", "abbigliamento", "medio"], "High Heels", "Scarpe col Tacco", "High Heels", "Tacones", "Talons Hauts"),
    ("leather_boots_brown", "pair of brown leather ankle boots", (50, 45), ["cuoio", "abbigliamento", "medio"], "Ankle Boots", "Stivaletti", "Stiefeletten", "Botines", "Bottines"),
    ("wool_beanie", "grey knitted wool beanie", (35, 30), ["stoffa", "abbigliamento", "cappello", "piccolo"], "Beanie", "Berretto di Lana", "Mütze", "Gorro", "Bonnet"),
    ("denim_jacket_folded", "folded denim jacket", (45, 40), ["stoffa", "abbigliamento", "medio"], "Denim Jacket", "Giacca di Jeans", "Jeansjacke", "Chaqueta Vaquera", "Veste en Jean"),
    ("t_shirt_folded", "folded plain white t-shirt", (40, 30), ["stoffa", "abbigliamento", "piccolo"], "T-shirt", "Maglietta", "T-Shirt", "Camiseta", "T-shirt"),
    ("belt_rolled", "rolled brown leather belt", (30, 30), ["cuoio", "abbigliamento", "piccolo"], "Belt", "Cintura", "Gürtel", "Cinturón", "Ceinture"),
    ("tie_silk_blue", "blue silk necktie", (15, 60), ["stoffa", "abbigliamento", "piccolo"], "Tie", "Cravatta", "Krawatte", "Corbata", "Cravate"),
    ("wallet_leather_black", "black leather wallet, closed", (35, 25), ["cuoio", "accessorio", "piccolo"], "Wallet", "Portafoglio", "Geldbörse", "Cartera", "Portefeuille"),
    ("handbag_red", "red leather handbag", (45, 40), ["cuoio", "accessorio", "medio"], "Handbag", "Borsetta", "Handtasche", "Bolso", "Sac à Main"),
    ("clutch_evening", "gold sequin evening clutch", (40, 25), ["accessorio", "piccolo"], "Clutch", "Pochette", "Clutch", "Cartera de Mano", "Pochette"),
    ("umbrella_open_black", "open black umbrella", (70, 45), ["stoffa", "accessorio", "grande"], "Open Umbrella", "Ombrello Aperto", "Offener Schirm", "Paraguas Abierto", "Parapluie Ouvert"),
    ("hair_clip", "tortoise hair claw clip", (25, 20), ["plastica", "bellezza", "piccolo"], "Hair Clip", "Pinza per Capelli", "Haarklammer", "Pinza de Pelo", "Pince à Cheveux"),
    ("lip_balm", "small lip balm tube, no text", (10, 30), ["plastica", "bellezza", "piccolo"], "Lip Balm", "Burrocacao", "Lippenbalsam", "Bálsamo Labial", "Baume à Lèvres"),
    ("nail_polish", "bottle of red nail polish", (12, 25), ["vetro", "bellezza", "piccolo"], "Nail Polish", "Smalto", "Nagellack", "Esmalte", "Vernis"),
    ("makeup_brush_set", "few makeup brushes", (35, 35), ["bellezza", "piccolo"], "Makeup Brushes", "Pennelli da Trucco", "Schminkpinsel", "Brochas", "Pinceaux de Maquillage"),
    ("perfume_bottle_modern", "modern square glass perfume bottle, no text", (25, 35), ["vetro", "bellezza", "piccolo"], "Perfume", "Profumo", "Parfüm", "Perfume", "Parfum"),
    ("wristwatch_steel", "steel wristwatch with a metal band", (25, 45), ["metallo", "accessorio", "piccolo"], "Steel Watch", "Orologio d'Acciaio", "Stahluhr", "Reloj de Acero", "Montre en Acier"),
    ("earrings_pearl", "pair of pearl stud earrings", (20, 15), ["accessorio", "piccolo"], "Pearl Earrings", "Orecchini di Perle", "Perlenohrringe", "Pendientes de Perla", "Boucles d'Oreilles"),
    ("bracelet_gold", "thin gold bangle bracelet", (30, 30), ["metallo", "accessorio", "piccolo"], "Gold Bracelet", "Bracciale d'Oro", "Goldarmband", "Pulsera de Oro", "Bracelet en Or"),
    ("ring_diamond", "gold ring with a diamond", (15, 15), ["metallo", "accessorio", "piccolo"], "Diamond Ring", "Anello con Diamante", "Diamantring", "Anillo de Diamante", "Bague Diamant"),
    # toys, games, music
    ("rubik_cube", "colourful puzzle cube", (25, 25), ["plastica", "gioco", "piccolo"], "Puzzle Cube", "Cubo Rompicapo", "Zauberwürfel", "Cubo Rompecabezas", "Cube Casse-tête"),
    ("teddy_bear_new", "soft brown teddy bear", (35, 45), ["stoffa", "giocattolo", "piccolo"], "Teddy Bear", "Orsetto di Peluche", "Teddybär", "Osito", "Nounours"),
    ("toy_robot", "small tin toy robot", (25, 40), ["metallo", "giocattolo", "piccolo"], "Toy Robot", "Robot Giocattolo", "Spielzeugroboter", "Robot de Juguete", "Robot Jouet"),
    ("toy_dinosaur", "plastic toy dinosaur", (45, 30), ["plastica", "giocattolo", "piccolo"], "Toy Dinosaur", "Dinosauro Giocattolo", "Spielzeugdinosaurier", "Dinosaurio de Juguete", "Dinosaure Jouet"),
    ("toy_train_wooden", "small wooden toy train", (55, 25), ["legno", "giocattolo", "piccolo"], "Wooden Train", "Trenino di Legno", "Holzeisenbahn", "Tren de Madera", "Train en Bois"),
    ("building_bricks", "few colourful toy building bricks", (35, 25), ["plastica", "giocattolo", "piccolo"], "Toy Bricks", "Mattoncini", "Bausteine", "Bloques", "Briques"),
    ("spinning_top_metal", "colourful metal spinning top", (25, 30), ["metallo", "giocattolo", "piccolo"], "Metal Top", "Trottola di Metallo", "Blechkreisel", "Peonza de Metal", "Toupie en Métal"),
    ("marble_single_blue", "single large blue glass marble", (15, 15), ["vetro", "giocattolo", "piccolo"], "Glass Marble", "Biglia", "Murmel", "Canica", "Bille"),
    ("toy_airplane", "small toy propeller airplane", (50, 40), ["metallo", "giocattolo", "piccolo"], "Toy Plane", "Aeroplanino", "Spielzeugflugzeug", "Avión de Juguete", "Avion Jouet"),
    ("play_cards_deck", "boxed deck of playing cards, plain box", (25, 35), ["carta", "gioco", "piccolo"], "Card Deck", "Mazzo di Carte", "Kartenspiel", "Baraja", "Jeu de Cartes"),
    ("poker_chips", "small stack of poker chips", (25, 25), ["plastica", "gioco", "piccolo"], "Poker Chips", "Fiches", "Pokerchips", "Fichas de Póquer", "Jetons"),
    ("hand_bell_toy", "small toy hand bell", (20, 30), ["metallo", "giocattolo", "piccolo"], "Toy Bell", "Campanellino", "Glöckchen", "Campanita", "Clochette"),
    ("recorder_flute", "plastic recorder flute", (10, 60), ["plastica", "musica", "piccolo"], "Recorder", "Flauto Dolce", "Blockflöte", "Flauta Dulce", "Flûte à Bec"),
    ("harmonica_modern", "chrome harmonica", (40, 12), ["metallo", "musica", "piccolo"], "Harmonica", "Armonica a Bocca", "Mundharmonika", "Armónica", "Harmonica"),
    ("guitar_pick", "few guitar picks", (20, 15), ["plastica", "musica", "piccolo"], "Guitar Picks", "Plettri", "Plektren", "Púas", "Médiators"),
    ("drumsticks", "pair of wooden drumsticks", (60, 15), ["legno", "musica", "piccolo"], "Drumsticks", "Bacchette da Batteria", "Drumsticks", "Baquetas", "Baguettes"),
    ("violin_bow", "violin bow", (80, 10), ["legno", "musica", "medio"], "Violin Bow", "Archetto", "Geigenbogen", "Arco de Violín", "Archet"),
    ("sheet_music_stand", "folding black music stand", (35, 70), ["metallo", "musica", "medio"], "Music Stand", "Leggio Musicale", "Notenständer", "Atril de Música", "Pupitre"),
    ("tambourine_modern", "modern tambourine", (35, 35), ["plastica", "musica", "piccolo"], "Modern Tambourine", "Tamburello Moderno", "Schellenkranz", "Pandereta Moderna", "Tambourin Moderne"),
    ("vinyl_record_sleeve", "black vinyl record partly out of a plain sleeve", (45, 45), ["plastica", "musica", "medio"], "Vinyl Record", "Disco in Vinile", "Schallplatte", "Disco de Vinilo", "Vinyle"),
    ("cassette_tape_blank", "cassette tape with a blank label", (35, 20), ["plastica", "musica", "piccolo"], "Cassette", "Musicassetta", "Kassette", "Casete", "Cassette"),
    # nature, science, curiosities
    ("magnifier_modern", "modern magnifying glass with a black handle", (25, 50), ["vetro", "studio", "piccolo"], "Magnifier", "Lente", "Lupe", "Lupa", "Loupe"),
    ("petri_dish", "glass petri dish", (30, 15), ["vetro", "studio", "piccolo"], "Petri Dish", "Capsula di Petri", "Petrischale", "Placa de Petri", "Boîte de Petri"),
    ("beaker_glass", "glass laboratory beaker", (25, 35), ["vetro", "studio", "piccolo"], "Beaker", "Becher", "Becherglas", "Vaso de Precipitado", "Bécher"),
    ("fossil_ammonite", "spiral ammonite fossil", (30, 30), ["natura", "studio", "piccolo"], "Ammonite", "Ammonite", "Ammonit", "Amonites", "Ammonite"),
    ("geode_amethyst", "split geode with purple amethyst", (35, 30), ["natura", "piccolo"], "Geode", "Geode", "Geode", "Geoda", "Géode"),
    ("meteorite_rock", "small dark meteorite rock", (30, 25), ["natura", "piccolo"], "Meteorite", "Meteorite", "Meteorit", "Meteorito", "Météorite"),
    ("butterfly_blue", "single blue butterfly specimen", (30, 25), ["natura", "piccolo"], "Blue Butterfly", "Farfalla Blu", "Blauer Schmetterling", "Mariposa Azul", "Papillon Bleu"),
    ("beetle_specimen", "large beetle specimen", (25, 30), ["natura", "piccolo"], "Beetle", "Scarabeo", "Käfer", "Escarabajo", "Scarabée"),
    ("peacock_feather", "single peacock feather", (20, 60), ["natura", "piccolo"], "Peacock Feather", "Piuma di Pavone", "Pfauenfeder", "Pluma de Pavo Real", "Plume de Paon"),
    ("pine_branch_snow", "small pine branch with snow", (50, 30), ["natura", "piccolo"], "Pine Branch", "Rametto di Pino", "Tannenzweig", "Rama de Pino", "Branche de Pin"),
    ("seashell_scallop", "scallop seashell", (30, 30), ["natura", "piccolo"], "Scallop Shell", "Capasanta", "Jakobsmuschel", "Vieira", "Coquille Saint-Jacques"),
    ("coral_red", "piece of red coral", (35, 35), ["natura", "piccolo"], "Red Coral", "Corallo Rosso", "Rote Koralle", "Coral Rojo", "Corail Rouge"),
    ("hourglass_modern", "modern glass hourglass with white sand", (20, 40), ["vetro", "piccolo"], "Hourglass", "Clessidra Moderna", "Moderne Sanduhr", "Reloj de Arena", "Sablier"),
    ("model_ship_wooden", "small wooden sailing ship model", (50, 45), ["legno", "decorazione", "medio"], "Ship Model", "Modellino di Veliero", "Schiffsmodell", "Maqueta de Barco", "Maquette de Voilier"),
    ("puzzle_box_wooden", "wooden puzzle box", (35, 25), ["legno", "gioco", "piccolo"], "Puzzle Box", "Scatola Rompicapo", "Rätselbox", "Caja Rompecabezas", "Boîte Mystère"),
    ("time_capsule_tin", "small metal time capsule tube", (20, 45), ["metallo", "contenitore", "piccolo"], "Time Capsule", "Capsula del Tempo", "Zeitkapsel", "Cápsula del Tiempo", "Capsule Temporelle"),
    ("treasure_map_rolled", "rolled old parchment map tied with string", (55, 20), ["carta", "viaggio", "antico", "piccolo"], "Rolled Map", "Mappa Arrotolata", "Aufgerollte Karte", "Mapa Enrollado", "Carte Roulée"),
    ("skeleton_hand_model", "plastic skeleton hand model", (30, 45), ["plastica", "horror", "piccolo"], "Skeleton Hand", "Mano Scheletrica", "Skeletthand", "Mano de Esqueleto", "Main Squelette"),
    ("candle_skull", "skull shaped candle", (25, 30), ["luce", "horror", "piccolo"], "Skull Candle", "Candela a Teschio", "Totenkopfkerze", "Vela Calavera", "Bougie Crâne"),
    ("gargoyle_small", "small stone gargoyle statue", (30, 35), ["decorazione", "horror", "piccolo"], "Gargoyle", "Gargoyle", "Wasserspeier", "Gárgola", "Gargouille"),
    ("black_cat_statue", "small black cat statue", (20, 35), ["ceramica", "decorazione", "piccolo"], "Black Cat", "Gatto Nero", "Schwarze Katze", "Gato Negro", "Chat Noir"),
    ("wax_seal_red", "single red wax seal disc", (20, 20), ["ufficio", "antico", "piccolo"], "Wax Seal", "Sigillo di Ceralacca", "Wachssiegel", "Sello de Lacre", "Sceau de Cire"),
    ("key_skeleton_iron", "large black iron skeleton key", (15, 45), ["ferro", "chiave", "antico", "piccolo"], "Skeleton Key", "Chiave Antica", "Bartschlüssel", "Llave Antigua", "Clé Ancienne"),
    # third round
    ("measuring_jug", "clear plastic measuring jug", (35, 40), ["plastica", "cucina", "piccolo"], "Measuring Jug", "Caraffa Graduata", "Messbecher", "Jarra Medidora", "Verre Doseur"),
    ("salad_spinner", "salad spinner", (45, 35), ["plastica", "cucina", "medio"], "Salad Spinner", "Centrifuga per Insalata", "Salatschleuder", "Centrifugadora", "Essoreuse"),
    ("rice_cooker", "white rice cooker", (40, 40), ["plastica", "cucina", "tecnologia", "medio"], "Rice Cooker", "Cuociriso", "Reiskocher", "Arrocera", "Cuiseur à Riz"),
    ("blender_glass", "kitchen blender with a glass jar", (30, 55), ["vetro", "cucina", "tecnologia", "medio"], "Blender", "Frullatore", "Mixer", "Batidora", "Mixeur"),
    ("waffle_plate", "plate with a waffle and syrup", (40, 20), ["ceramica", "cibo", "piccolo"], "Waffle", "Waffle", "Waffel", "Gofre", "Gaufre"),
    ("pancake_stack", "stack of pancakes on a plate", (40, 30), ["ceramica", "cibo", "piccolo"], "Pancakes", "Pancake", "Pfannkuchen", "Tortitas", "Pancakes"),
    ("burger", "hamburger with cheese and lettuce", (35, 30), ["cibo", "piccolo"], "Burger", "Hamburger", "Burger", "Hamburguesa", "Burger"),
    ("pizza_slice", "slice of pizza", (35, 30), ["cibo", "piccolo"], "Pizza Slice", "Trancio di Pizza", "Pizzastück", "Porción de Pizza", "Part de Pizza"),
    ("taco", "taco with filling", (35, 25), ["cibo", "piccolo"], "Taco", "Taco", "Taco", "Taco", "Taco"),
    ("ice_cream_cone_scoop", "ice cream cone with two scoops", (20, 45), ["cibo", "piccolo"], "Ice Cream", "Cono Gelato", "Eistüte", "Cucurucho", "Cornet de Glace"),
    ("lollipop_swirl", "swirl lollipop", (25, 45), ["cibo", "piccolo"], "Lollipop", "Lecca-lecca", "Lutscher", "Piruleta", "Sucette"),
    ("candy_wrapped", "few wrapped candies", (35, 25), ["cibo", "piccolo"], "Candies", "Caramelle", "Bonbons", "Caramelos", "Bonbons"),
    ("popcorn_box", "striped box of popcorn, no text", (30, 40), ["carta", "cibo", "piccolo"], "Popcorn", "Popcorn", "Popcorn", "Palomitas", "Pop-corn"),
    ("macarons", "few pastel macarons", (40, 20), ["cibo", "piccolo"], "Macarons", "Macaron", "Macarons", "Macarons", "Macarons"),
    ("peanut_jar", "glass jar of peanuts", (25, 35), ["vetro", "cibo", "piccolo"], "Peanuts", "Barattolo di Arachidi", "Erdnussglas", "Tarro de Cacahuetes", "Bocal de Cacahuètes"),
    ("strawberry_basket", "small basket of strawberries", (35, 25), ["cibo", "natura", "piccolo"], "Strawberries", "Cestino di Fragole", "Erdbeerkorb", "Cesta de Fresas", "Panier de Fraises"),
    ("watermelon_slice", "slice of red watermelon", (40, 25), ["cibo", "natura", "piccolo"], "Watermelon", "Fetta di Anguria", "Wassermelone", "Sandía", "Pastèque"),
    ("pineapple_whole", "whole pineapple", (30, 55), ["cibo", "natura", "piccolo"], "Pineapple", "Ananas", "Ananas", "Piña", "Ananas"),
    ("avocado_half", "avocado cut in half", (30, 25), ["cibo", "natura", "piccolo"], "Avocado", "Avocado", "Avocado", "Aguacate", "Avocat"),
    ("tomato_vine", "cluster of red tomatoes on the vine", (40, 30), ["cibo", "natura", "piccolo"], "Tomatoes", "Pomodori", "Tomaten", "Tomates", "Tomates"),
    ("eggplant", "single purple eggplant", (40, 20), ["cibo", "natura", "piccolo"], "Eggplant", "Melanzana", "Aubergine", "Berenjena", "Aubergine"),
    ("mushroom_button_pile", "few white button mushrooms", (30, 20), ["cibo", "natura", "piccolo"], "Mushrooms", "Champignon", "Champignons", "Champiñones", "Champignons"),
    ("baby_bottle", "baby feeding bottle", (15, 40), ["plastica", "piccolo"], "Baby Bottle", "Biberon", "Babyflasche", "Biberón", "Biberon"),
    ("pacifier", "baby pacifier", (20, 20), ["plastica", "piccolo"], "Pacifier", "Ciuccio", "Schnuller", "Chupete", "Tétine"),
    ("baby_rattle", "wooden baby rattle", (20, 40), ["legno", "giocattolo", "piccolo"], "Rattle", "Sonaglio", "Rassel", "Sonajero", "Hochet"),
    ("dog_collar", "leather dog collar with a tag", (35, 30), ["cuoio", "accessorio", "piccolo"], "Dog Collar", "Collare", "Hundehalsband", "Collar de Perro", "Collier de Chien"),
    ("pet_bowl", "steel pet food bowl", (35, 15), ["metallo", "piccolo"], "Pet Bowl", "Ciotola per Animali", "Futternapf", "Comedero", "Gamelle"),
    ("dog_bone_toy", "rubber dog bone toy", (40, 15), ["plastica", "giocattolo", "piccolo"], "Dog Toy", "Osso Giocattolo", "Hundeknochen", "Hueso de Juguete", "Os Jouet"),
    ("cat_toy_mouse", "grey fabric toy mouse", (30, 15), ["stoffa", "giocattolo", "piccolo"], "Cat Toy", "Topolino Giocattolo", "Spielmaus", "Ratón de Juguete", "Souris Jouet"),
    ("fish_bowl", "empty round glass fish bowl with pebbles", (35, 35), ["vetro", "arredamento", "piccolo"], "Fish Bowl", "Boccia per Pesci", "Goldfischglas", "Pecera", "Bocal à Poisson"),
    ("hamster_wheel", "small hamster wheel", (30, 30), ["plastica", "piccolo"], "Hamster Wheel", "Ruota per Criceti", "Hamsterrad", "Rueda de Hámster", "Roue de Hamster"),
    ("horse_brush", "wooden horse grooming brush", (40, 20), ["legno", "attrezzo", "piccolo"], "Horse Brush", "Striglia", "Pferdebürste", "Cepillo de Caballo", "Brosse à Cheval"),
    ("chalkboard_sign", "small blank chalkboard sign", (40, 45), ["legno", "arredamento", "medio"], "Chalkboard", "Lavagnetta", "Kreidetafel", "Pizarra", "Ardoise"),
    ("neon_sign_heart", "small pink neon heart sign, unlit", (40, 35), ["vetro", "luce", "decorazione", "piccolo"], "Neon Heart", "Neon a Cuore", "Neonherz", "Neón Corazón", "Néon Cœur"),
    ("string_lights", "coiled string fairy lights", (40, 30), ["luce", "decorazione", "piccolo"], "Fairy Lights", "Lucine", "Lichterkette", "Guirnalda de Luces", "Guirlande"),
    ("gift_box_red", "red gift box with a gold ribbon", (35, 30), ["carta", "decorazione", "piccolo"], "Gift Box", "Pacco Regalo", "Geschenkbox", "Caja de Regalo", "Boîte Cadeau"),
    ("party_hat", "striped party hat", (25, 35), ["carta", "decorazione", "piccolo"], "Party Hat", "Cappellino da Festa", "Partyhut", "Gorro de Fiesta", "Chapeau de Fête"),
    ("confetti_popper", "party confetti popper", (15, 40), ["carta", "decorazione", "piccolo"], "Party Popper", "Sparacoriandoli", "Konfettikanone", "Lanzador de Confeti", "Canon à Confettis"),
    ("christmas_ornament", "red glass christmas ornament", (25, 30), ["vetro", "decorazione", "piccolo"], "Ornament", "Pallina di Natale", "Christbaumkugel", "Bola de Navidad", "Boule de Noël"),
    ("easter_egg_painted", "painted decorated easter egg", (20, 25), ["decorazione", "piccolo"], "Painted Egg", "Uovo Decorato", "Osterei", "Huevo Pintado", "Œuf Décoré"),
    ("carved_pumpkin_lantern", "carved pumpkin lantern", (35, 30), ["decorazione", "horror", "piccolo"], "Carved Pumpkin", "Zucca Intagliata", "Kürbislaterne", "Calabaza Tallada", "Citrouille Sculptée"),
    ("witch_hat", "black pointed witch hat", (45, 45), ["stoffa", "cappello", "occulto", "medio"], "Witch Hat", "Cappello da Strega", "Hexenhut", "Sombrero de Bruja", "Chapeau de Sorcière"),
    ("vampire_fangs", "plastic vampire fangs", (25, 15), ["plastica", "horror", "piccolo"], "Vampire Fangs", "Denti da Vampiro", "Vampirzähne", "Colmillos", "Dents de Vampire"),
    ("magic_top_hat", "black magician top hat", (40, 35), ["stoffa", "cappello", "medio"], "Top Hat", "Cilindro", "Zylinder", "Sombrero de Copa", "Haut-de-forme"),
    ("carnival_mask_gold", "gold carnival eye mask", (40, 25), ["accessorio", "decorazione", "piccolo"], "Carnival Mask", "Maschera di Carnevale", "Karnevalsmaske", "Máscara de Carnaval", "Masque de Carnaval"),
]

C_ALL = [(r[0], r[1], r[2], r[3], list(r[4:9])) for r in _ROWS]
DROPPED = set(['pizza_slice', 'popcorn_box', 'watermelon_slice', 'lollipop_swirl', 'ice_cream_cone_scoop', 'pineapple_whole', 'tomato_vine', 'eggplant', 'strawberry_basket', 'baguette', 'banana_bunch', 'basketball', 'belt_rolled', 'binoculars_modern', 'broom_straw', 'camping_stove_gas', 'candle_skull', 'cassette_tape_blank', 'chocolate_bar', 'coconut', 'donut_glazed', 'drone_small', 'dustpan_brush', 'first_aid_box', 'flip_flops', 'frying_pan_nonstick', 'grapes_bunch_red', 'hammer_claw', 'hand_bell_toy', 'handbag_red', 'harmonica_modern', 'hourglass_modern', 'ice_bucket_steel', 'key_skeleton_iron', 'lemon_fruit', 'milk_carton', 'model_ship_wooden', 'mop_bucket_small', 'paint_roller_tray', 'perfume_bottle_modern', 'pliers_red', 'postcard_blank', 'pumpkin_small', 'recorder_flute', 'rose_red', 'rubber_gloves_yellow', 'screwdriver_set', 'seashell_scallop', 'skipping_rope_speed', 'sleeping_bag_rolled', 'smartphone_black', 'snow_globe_winter', 'soup_ladle_steel', 'spatula_wooden', 'spinning_top_metal', 'table_lamp_modern', 'tambourine_modern', 'tape_measure_yellow', 'teddy_bear_new', 'tie_silk_blue', 'toy_robot', 'toy_train_wooden', 'traffic_cone_small', 'trash_can_pedal', 'umbrella_open_black', 'utility_knife_yellow', 'vr_headset', 'wallet_leather_black', 'watering_can_metal', 'wax_seal_red', 'whistle_referee', 'wristwatch_steel'])  # already in real style
C = [r for r in C_ALL if r[0] not in DROPPED][:200]
