"""400-object batch, part B (100): furniture, decor, bathroom, cleaning, tools, garden."""

_ROWS = [
    ("armchair_leather", "brown leather club armchair", (60, 60), ["cuoio", "arredamento", "grande"], "Leather Armchair", "Poltrona di Pelle", "Ledersessel", "Sillón de Cuero", "Fauteuil en Cuir"),
    ("rocking_chair", "wooden rocking chair", (55, 70), ["legno", "arredamento", "grande"], "Rocking Chair", "Sedia a Dondolo", "Schaukelstuhl", "Mecedora", "Rocking-chair"),
    ("bar_stool_metal", "metal bar stool", (35, 70), ["metallo", "arredamento", "grande"], "Bar Stool", "Sgabello da Bar", "Barhocker", "Taburete", "Tabouret de Bar"),
    ("side_table_round", "small round wooden side table", (45, 55), ["legno", "arredamento", "medio"], "Side Table", "Tavolino", "Beistelltisch", "Mesita", "Guéridon"),
    ("bookshelf_small", "small wooden bookshelf with a few books", (50, 70), ["legno", "arredamento", "grande"], "Small Bookshelf", "Libreria", "Bücherregal", "Estantería", "Bibliothèque"),
    ("folding_screen", "three panel folding room screen", (70, 70), ["legno", "stoffa", "arredamento", "grande"], "Folding Screen", "Paravento", "Paravent", "Biombo", "Paravent"),
    ("coat_stand_wooden", "wooden coat stand with a hat", (35, 90), ["legno", "arredamento", "grande"], "Coat Stand", "Appendiabiti", "Garderobenständer", "Perchero", "Portemanteau"),
    ("chest_of_drawers_small", "small three drawer wooden chest", (50, 50), ["legno", "arredamento", "medio"], "Chest of Drawers", "Cassettiera", "Kommode", "Cómoda", "Commode"),
    ("jewelry_armoire", "small standing jewellery cabinet", (35, 55), ["legno", "arredamento", "medio"], "Jewellery Cabinet", "Portagioie a Colonna", "Schmuckschrank", "Joyero de Pie", "Armoire à Bijoux"),
    ("magazine_rack", "wooden magazine rack with magazines, no text", (45, 40), ["legno", "arredamento", "medio"], "Magazine Rack", "Portariviste", "Zeitschriftenständer", "Revistero", "Porte-revues"),
    ("floor_lamp_brass", "brass floor lamp with a white shade", (35, 90), ["ottone", "luce", "arredamento", "grande"], "Floor Lamp", "Lampada da Terra", "Stehlampe", "Lámpara de Pie", "Lampadaire"),
    ("chandelier_small", "small crystal chandelier", (50, 50), ["vetro", "metallo", "luce", "arredamento", "medio"], "Chandelier", "Lampadario", "Kronleuchter", "Araña", "Lustre"),
    ("candelabra_silver", "three arm silver candelabra with candles", (40, 50), ["argento", "luce", "arredamento", "medio"], "Candelabra", "Candelabro", "Kandelaber", "Candelabro", "Candélabre"),
    ("lava_lamp", "lava lamp with orange wax", (20, 50), ["vetro", "luce", "arredamento", "piccolo"], "Lava Lamp", "Lampada Lava", "Lavalampe", "Lámpara de Lava", "Lampe à Lave"),
    ("paper_lantern_white", "white round paper lantern", (40, 40), ["carta", "luce", "decorazione", "medio"], "Paper Lantern", "Lanterna di Carta", "Papierlaterne", "Farolillo de Papel", "Lanterne en Papier"),
    ("mirror_ornate_gold", "ornate gold framed mirror", (45, 60), ["vetro", "arredamento", "medio"], "Ornate Mirror", "Specchio Dorato", "Prunkspiegel", "Espejo Dorado", "Miroir Doré"),
    ("tapestry_rolled", "rolled woven tapestry rug", (70, 20), ["stoffa", "arredamento", "medio"], "Rolled Rug", "Tappeto Arrotolato", "Gerollter Teppich", "Alfombra Enrollada", "Tapis Roulé"),
    ("vase_blue_white", "blue and white porcelain vase", (30, 50), ["ceramica", "decorazione", "medio"], "Porcelain Vase", "Vaso di Porcellana", "Porzellanvase", "Jarrón de Porcelana", "Vase en Porcelaine"),
    ("vase_glass_flowers", "glass vase with tulips", (25, 55), ["vetro", "natura", "decorazione", "medio"], "Tulip Vase", "Vaso di Tulipani", "Tulpenvase", "Jarrón de Tulipanes", "Vase de Tulipes"),
    ("urn_bronze", "small bronze urn with handles", (30, 45), ["metallo", "decorazione", "antico", "medio"], "Bronze Urn", "Urna di Bronzo", "Bronzeurne", "Urna de Bronce", "Urne en Bronze"),
    ("bust_plaster", "white plaster bust of a classical figure", (35, 50), ["decorazione", "arte", "medio"], "Plaster Bust", "Busto in Gesso", "Gipsbüste", "Busto de Yeso", "Buste en Plâtre"),
    ("statuette_bronze", "small bronze statuette of a horse", (40, 35), ["metallo", "decorazione", "piccolo"], "Bronze Horse", "Cavallo di Bronzo", "Bronzepferd", "Caballo de Bronce", "Cheval en Bronze"),
    ("globe_lamp", "illuminated globe lamp", (35, 45), ["vetro", "luce", "studio", "medio"], "Globe Lamp", "Mappamondo Luminoso", "Leuchtglobus", "Globo Luminoso", "Globe Lumineux"),
    ("wall_plate_decorative", "decorative painted wall plate", (40, 40), ["ceramica", "decorazione", "medio"], "Decorative Plate", "Piatto Decorativo", "Wandteller", "Plato Decorativo", "Assiette Décorative"),
    ("clock_mantel_gold", "gilded mantel clock", (40, 40), ["metallo", "arredamento", "antico", "medio"], "Gilded Clock", "Orologio Dorato", "Goldene Uhr", "Reloj Dorado", "Pendule Dorée"),
    ("cuckoo_clock_small", "small wooden cuckoo clock", (35, 50), ["legno", "arredamento", "medio"], "Cuckoo Clock", "Orologio a Cucù", "Kuckucksuhr", "Reloj de Cuco", "Coucou"),
    ("grandfather_clock_mini", "tall wooden grandfather clock", (35, 90), ["legno", "arredamento", "grande"], "Grandfather Clock", "Pendola", "Standuhr", "Reloj de Pie", "Horloge Comtoise"),
    ("hourglass_brass_large", "large brass hourglass", (30, 50), ["ottone", "vetro", "arredamento", "medio"], "Large Hourglass", "Grande Clessidra", "Große Sanduhr", "Reloj de Arena Grande", "Grand Sablier"),
    ("music_box_ballerina_new", "open music box with a small dancer", (40, 35), ["legno", "musica", "decorazione", "piccolo"], "Dancer Music Box", "Carillon con Ballerina", "Spieluhr", "Caja de Música", "Boîte à Musique"),
    ("photo_frame_silver", "silver photo frame with a blank photo", (30, 40), ["argento", "foto", "arredamento", "piccolo"], "Silver Frame", "Cornice d'Argento", "Silberrahmen", "Marco de Plata", "Cadre en Argent"),
    ("pillow_embroidered", "embroidered decorative pillow", (45, 45), ["stoffa", "arredamento", "medio"], "Embroidered Pillow", "Cuscino Ricamato", "Besticktes Kissen", "Cojín Bordado", "Coussin Brodé"),
    ("blanket_knitted", "folded chunky knitted blanket", (50, 30), ["stoffa", "arredamento", "medio"], "Knitted Blanket", "Coperta a Maglia", "Strickdecke", "Manta de Punto", "Plaid Tricoté"),
    ("quilt_patchwork", "folded patchwork quilt", (50, 30), ["stoffa", "arredamento", "medio"], "Patchwork Quilt", "Trapunta Patchwork", "Patchworkdecke", "Colcha de Patchwork", "Courtepointe"),
    ("curtain_tieback", "velvet curtain tassel tieback", (20, 50), ["stoffa", "arredamento", "piccolo"], "Curtain Tassel", "Nappa per Tende", "Vorhangquaste", "Alzapaños", "Embrasse"),
    ("door_knob_crystal", "glass crystal door knob", (20, 25), ["vetro", "arredamento", "piccolo"], "Crystal Knob", "Pomolo di Cristallo", "Kristallknauf", "Pomo de Cristal", "Bouton en Cristal"),
    ("keyhole_plate", "ornate brass keyhole plate", (20, 35), ["ottone", "arredamento", "antico", "piccolo"], "Keyhole Plate", "Bocchetta della Serratura", "Schlüssellochschild", "Bocallave", "Entrée de Serrure"),
    ("hinge_brass", "brass door hinge", (30, 35), ["ottone", "arredamento", "piccolo"], "Brass Hinge", "Cerniera d'Ottone", "Messingscharnier", "Bisagra de Latón", "Charnière en Laiton"),
    ("drawer_pull_brass", "brass drawer pull handle", (35, 15), ["ottone", "arredamento", "piccolo"], "Drawer Pull", "Maniglia del Cassetto", "Schubladengriff", "Tirador", "Poignée de Tiroir"),
    ("bathtub_duck_set", "three rubber ducks of different colours", (45, 25), ["plastica", "bagno", "giocattolo", "piccolo"], "Rubber Ducks", "Paperelle", "Quietscheentchen", "Patitos", "Canards en Caoutchouc"),
    ("bath_salts_jar", "glass jar of pink bath salts", (25, 35), ["vetro", "bagno", "bellezza", "piccolo"], "Bath Salts", "Sali da Bagno", "Badesalz", "Sales de Baño", "Sels de Bain"),
    ("loofah", "natural loofah sponge", (30, 20), ["natura", "bagno", "piccolo"], "Loofah", "Luffa", "Luffa", "Lufa", "Luffa"),
    ("shower_cap", "floral shower cap", (35, 20), ["plastica", "bagno", "piccolo"], "Shower Cap", "Cuffia da Doccia", "Duschhaube", "Gorro de Ducha", "Charlotte"),
    ("shampoo_bottle", "plain white shampoo bottle, no text", (15, 45), ["plastica", "bagno", "bellezza", "piccolo"], "Shampoo", "Shampoo", "Shampoo", "Champú", "Shampoing"),
    ("hair_dryer_pink", "pink hair dryer", (40, 40), ["plastica", "bellezza", "tecnologia", "medio"], "Hair Dryer", "Asciugacapelli", "Föhn", "Secador", "Sèche-cheveux"),
    ("razor_safety", "chrome safety razor", (15, 40), ["metallo", "bellezza", "piccolo"], "Safety Razor", "Rasoio di Sicurezza", "Rasierhobel", "Maquinilla", "Rasoir de Sûreté"),
    ("cotton_swabs_jar", "glass jar of cotton swabs", (20, 30), ["vetro", "bagno", "piccolo"], "Cotton Swabs", "Cotton Fioc", "Wattestäbchen", "Bastoncillos", "Cotons-tiges"),
    ("toilet_paper_roll", "single toilet paper roll", (20, 20), ["carta", "bagno", "piccolo"], "Toilet Roll", "Rotolo di Carta Igienica", "Toilettenpapier", "Rollo de Papel", "Rouleau de Papier"),
    ("tissue_box", "box of tissues, plain", (35, 20), ["carta", "bagno", "piccolo"], "Tissue Box", "Scatola di Fazzoletti", "Taschentuchbox", "Caja de Pañuelos", "Boîte de Mouchoirs"),
    ("scale_bathroom_retro", "retro dial bathroom scale", (40, 15), ["metallo", "bilancia", "bagno", "piccolo"], "Bathroom Scale", "Pesapersone", "Personenwaage", "Báscula de Baño", "Pèse-personne"),
    ("clothespin_bag", "cloth peg bag with pegs", (30, 35), ["stoffa", "piccolo"], "Peg Bag", "Sacchetto delle Mollette", "Klammerbeutel", "Bolsa de Pinzas", "Sac à Pinces"),
    ("bucket_galvanized", "galvanized steel bucket", (35, 40), ["metallo", "contenitore", "medio"], "Metal Bucket", "Secchio di Latta", "Zinkeimer", "Cubo de Metal", "Seau en Métal"),
    ("scrub_brush", "wooden scrub brush", (35, 15), ["legno", "attrezzo", "piccolo"], "Scrub Brush", "Spazzolone", "Schrubber", "Cepillo de Fregar", "Brosse à Récurer"),
    ("feather_duster_new", "colourful feather duster", (20, 60), ["attrezzo", "piccolo"], "Feather Duster", "Piumino", "Staubwedel", "Plumero", "Plumeau"),
    ("dust_cloth", "folded yellow dust cloth", (30, 25), ["stoffa", "attrezzo", "piccolo"], "Dust Cloth", "Panno per la Polvere", "Staubtuch", "Paño", "Chiffon"),
    ("vacuum_cleaner_small", "small handheld vacuum cleaner", (40, 25), ["plastica", "tecnologia", "attrezzo", "piccolo"], "Hand Vacuum", "Aspirapolvere Portatile", "Handstaubsauger", "Aspiradora de Mano", "Aspirateur à Main"),
    ("sewing_machine_modern", "modern white sewing machine", (55, 40), ["plastica", "tecnologia", "medio"], "Sewing Machine", "Macchina da Cucire", "Nähmaschine", "Máquina de Coser", "Machine à Coudre"),
    ("pin_cushion_tomato", "tomato shaped pin cushion", (25, 20), ["stoffa", "piccolo"], "Tomato Pincushion", "Puntaspilli a Pomodoro", "Nadelkissen", "Acerico", "Pelote à Épingles"),
    ("yarn_basket", "basket of colourful yarn balls", (45, 30), ["stoffa", "legno", "medio"], "Yarn Basket", "Cesto di Gomitoli", "Wollkorb", "Cesta de Lana", "Panier de Laine"),
    ("spool_rack", "small rack of thread spools", (40, 30), ["legno", "stoffa", "piccolo"], "Spool Rack", "Portarocchetti", "Garnrollenhalter", "Portabobinas", "Porte-bobines"),
    ("measuring_tape_tailor", "rolled tailor measuring tape", (25, 25), ["stoffa", "piccolo"], "Tailor Tape", "Metro da Sarto", "Schneidermaßband", "Cinta de Sastre", "Mètre de Couturière"),
    ("dress_form", "tailor dress form mannequin", (40, 90), ["stoffa", "legno", "grande"], "Dress Form", "Manichino da Sarta", "Schneiderpuppe", "Maniquí de Costura", "Mannequin de Couture"),
    ("fabric_roll", "roll of patterned fabric", (70, 20), ["stoffa", "medio"], "Fabric Roll", "Rotolo di Stoffa", "Stoffrolle", "Rollo de Tela", "Rouleau de Tissu"),
    ("level_tool_modern", "yellow spirit level", (70, 12), ["plastica", "attrezzo", "medio"], "Level", "Livella", "Wasserwaage", "Nivel", "Niveau"),
    ("hand_saw_new", "hand saw with a plastic handle", (70, 25), ["metallo", "attrezzo", "medio"], "Hand Saw", "Sega a Mano", "Handsäge", "Serrucho", "Scie"),
    ("wrench_set_chrome", "set of chrome combination wrenches", (50, 30), ["metallo", "attrezzo", "medio"], "Wrench Set", "Set di Chiavi", "Schlüsselsatz", "Juego de Llaves", "Jeu de Clés"),
    ("toolbox_red", "red metal toolbox", (55, 35), ["metallo", "attrezzo", "contenitore", "medio"], "Toolbox", "Cassetta degli Attrezzi", "Werkzeugkasten", "Caja de Herramientas", "Boîte à Outils"),
    ("nails_box", "small box of nails", (30, 20), ["metallo", "attrezzo", "piccolo"], "Nails", "Scatola di Chiodi", "Nägel", "Clavos", "Clous"),
    ("screws_assorted", "few assorted screws and bolts", (35, 20), ["metallo", "attrezzo", "piccolo"], "Screws", "Viti e Bulloni", "Schrauben", "Tornillos", "Vis"),
    ("sandpaper_sheets", "few sheets of sandpaper", (35, 30), ["carta", "attrezzo", "piccolo"], "Sandpaper", "Carta Vetrata", "Schleifpapier", "Papel de Lija", "Papier de Verre"),
    ("paint_brush_wide", "wide paint brush", (20, 50), ["legno", "attrezzo", "piccolo"], "Wide Brush", "Pennellessa", "Flachpinsel", "Brocha", "Brosse Plate"),
    ("paint_bucket_white", "bucket of white paint, open", (35, 35), ["plastica", "attrezzo", "piccolo"], "Paint Bucket", "Secchio di Pittura", "Farbeimer", "Cubo de Pintura", "Pot de Peinture"),
    ("caulk_gun", "caulking gun", (60, 20), ["metallo", "attrezzo", "medio"], "Caulk Gun", "Pistola per Silicone", "Kartuschenpistole", "Pistola de Silicona", "Pistolet à Silicone"),
    ("stud_finder", "handheld stud finder", (20, 35), ["plastica", "attrezzo", "piccolo"], "Stud Finder", "Rilevatore", "Ortungsgerät", "Detector", "Détecteur"),
    ("extension_cord_reel", "extension cord reel", (40, 40), ["plastica", "tecnologia", "medio"], "Cord Reel", "Avvolgicavo", "Kabeltrommel", "Enrollador", "Enrouleur"),
    ("work_lamp_cage", "caged work lamp with a hook", (25, 45), ["metallo", "luce", "attrezzo", "piccolo"], "Work Lamp", "Lampada da Lavoro", "Arbeitsleuchte", "Lámpara de Trabajo", "Baladeuse"),
    ("ladder_step", "small aluminium step ladder", (40, 70), ["metallo", "attrezzo", "grande"], "Step Ladder", "Scaletta", "Trittleiter", "Escalerilla", "Escabeau"),
    ("wheelbarrow_small", "small metal wheelbarrow", (70, 45), ["metallo", "attrezzo", "grande"], "Wheelbarrow", "Carriola", "Schubkarre", "Carretilla", "Brouette"),
    ("garden_hose_reel", "coiled garden hose on a reel", (45, 40), ["plastica", "attrezzo", "medio"], "Hose Reel", "Tubo da Giardino", "Schlauchtrommel", "Manguera", "Tuyau d'Arrosage"),
    ("rake_garden", "metal garden rake", (30, 90), ["metallo", "attrezzo", "grande"], "Garden Rake", "Rastrello", "Rechen", "Rastrillo", "Râteau"),
    ("hoe_garden", "garden hoe", (25, 90), ["metallo", "legno", "attrezzo", "grande"], "Hoe", "Zappa", "Hacke", "Azada", "Houe"),
    ("pitchfork", "pitchfork", (25, 90), ["metallo", "legno", "attrezzo", "grande"], "Pitchfork", "Forcone", "Mistgabel", "Horca", "Fourche"),
    ("shovel_garden", "garden spade shovel", (25, 90), ["metallo", "legno", "attrezzo", "grande"], "Spade", "Vanga", "Spaten", "Pala", "Bêche"),
    ("hand_cultivator", "small hand cultivator fork", (15, 45), ["metallo", "attrezzo", "piccolo"], "Hand Fork", "Forchetta da Giardino", "Handgrubber", "Escarificador", "Griffe"),
    ("plant_mister", "glass plant mister", (15, 35), ["vetro", "attrezzo", "piccolo"], "Plant Mister", "Nebulizzatore", "Sprüher", "Pulverizador", "Brumisateur"),
    ("seed_tray", "black plastic seedling tray with soil", (50, 25), ["plastica", "natura", "medio"], "Seed Tray", "Semenzaio", "Anzuchtschale", "Semillero", "Plateau de Semis"),
    ("garden_gnome_new", "garden gnome figurine", (25, 45), ["ceramica", "decorazione", "piccolo"], "Garden Gnome", "Nano da Giardino", "Gartenzwerg", "Gnomo de Jardín", "Nain de Jardin"),
    ("bird_bath", "small stone bird bath", (40, 45), ["natura", "decorazione", "medio"], "Bird Bath", "Vasca per Uccelli", "Vogelbad", "Bebedero", "Bain d'Oiseaux"),
    ("scarecrow_small", "small straw scarecrow", (40, 70), ["stoffa", "decorazione", "grande"], "Scarecrow", "Spaventapasseri", "Vogelscheuche", "Espantapájaros", "Épouvantail"),
    ("hay_bale_small", "small bale of hay", (50, 35), ["natura", "medio"], "Hay Bale", "Balla di Fieno", "Heuballen", "Fardo de Heno", "Botte de Foin"),
    ("flower_crate", "wooden crate of potted flowers", (50, 35), ["legno", "natura", "medio"], "Flower Crate", "Cassetta di Fiori", "Blumenkiste", "Caja de Flores", "Caisse de Fleurs"),
    ("terracotta_planter", "rectangular terracotta planter with herbs", (55, 25), ["ceramica", "natura", "medio"], "Planter", "Fioriera", "Pflanzkasten", "Jardinera", "Jardinière"),
    ("hanging_basket", "hanging basket of red flowers", (40, 45), ["natura", "decorazione", "medio"], "Hanging Basket", "Cesto Pensile", "Hängekorb", "Cesta Colgante", "Suspension"),
    ("lantern_garden_solar", "garden solar lantern", (25, 45), ["metallo", "luce", "piccolo"], "Garden Lantern", "Lanterna da Giardino", "Gartenlaterne", "Farol de Jardín", "Lanterne de Jardin"),
    ("wind_vane_rooster", "metal rooster weather vane", (45, 50), ["metallo", "decorazione", "medio"], "Weather Vane", "Banderuola", "Wetterhahn", "Veleta", "Girouette"),
    ("mailbox_metal", "metal mailbox with a flag", (35, 40), ["metallo", "contenitore", "medio"], "Mailbox", "Cassetta della Posta", "Briefkasten", "Buzón", "Boîte aux Lettres"),
    ("doorbell_button", "brass doorbell push button", (15, 25), ["ottone", "arredamento", "piccolo"], "Doorbell", "Campanello", "Klingel", "Timbre", "Sonnette"),
    ("house_number_plate", "house number plate with a blank tile", (30, 25), ["ceramica", "arredamento", "piccolo"], "House Number", "Numero Civico", "Hausnummer", "Número de Casa", "Numéro de Maison"),
    ("welcome_sign_wood", "blank wooden hanging sign", (45, 30), ["legno", "decorazione", "piccolo"], "Wooden Sign", "Insegna di Legno", "Holzschild", "Cartel de Madera", "Panneau en Bois"),
    ("birdcage_ornate", "ornate white metal birdcage, empty", (40, 60), ["metallo", "decorazione", "medio"], "Ornate Birdcage", "Gabbia Decorativa", "Zierkäfig", "Jaula Decorativa", "Cage Décorative"),
    ("wind_chime_bamboo", "bamboo wind chime", (30, 55), ["legno", "decorazione", "piccolo"], "Bamboo Chime", "Scacciapensieri di Bambù", "Bambus-Windspiel", "Carillón de Bambú", "Carillon en Bambou"),
]
C = [(r[0], r[1], r[2], r[3], list(r[4:9])) for r in _ROWS]
