"""Eighty generic objects, interchangeable between games (no character, place, date or
readable text; no green objects). Longer than 80: duplicates dropped, first 80 kept.
"""

_RAW = [
    # garden and outdoor
    ("garden_trowel", "old garden trowel with a wooden handle, soil on the blade", (20, 50), ["metallo", "legno", "attrezzo", "vintage", "piccolo"], ["Garden Trowel", "Paletta da Giardino", "Pflanzkelle", "Pala de Jardín", "Transplantoir"]),
    ("pruning_shears_old", "old iron pruning shears with wooden grips", (25, 45), ["ferro", "legno", "attrezzo", "vintage", "piccolo"], ["Pruning Shears", "Forbici da Potatura", "Rosenschere", "Tijeras de Podar", "Sécateur"]),
    ("clay_flower_pot", "old empty terracotta flower pot, chipped", (35, 35), ["ceramica", "natura", "vintage", "medio"], ["Flower Pot", "Vaso di Terracotta", "Blumentopf", "Maceta de Barro", "Pot en Terre"]),
    ("seed_packets", "few old paper seed packets, faded, no readable text", (35, 30), ["carta", "natura", "vintage", "piccolo"], ["Seed Packets", "Bustine di Semi", "Samentüten", "Sobres de Semillas", "Sachets de Graines"]),
    ("wooden_rake_head", "old wooden hay rake head without the long handle", (60, 20), ["legno", "attrezzo", "antico", "medio"], ["Rake Head", "Testa di Rastrello", "Rechenkopf", "Cabeza de Rastrillo", "Tête de Râteau"]),
    ("bird_nest_eggs", "small bird nest with three speckled eggs", (35, 25), ["natura", "piccolo"], ["Bird Nest", "Nido con Uova", "Vogelnest", "Nido con Huevos", "Nid d'Oiseau"]),
    ("feather_quill_white", "single long white goose feather", (15, 55), ["natura", "piccolo"], ["White Feather", "Piuma Bianca", "Weiße Feder", "Pluma Blanca", "Plume Blanche"]),
    ("butterfly_frame", "old glass frame with a pinned brown moth, entomology display", (40, 35), ["vetro", "legno", "natura", "studio", "vintage", "medio"], ["Moth Display", "Teca con Falena", "Falterschaukasten", "Vitrina de Polilla", "Cadre à Papillon"]),
    ("snail_shell", "empty brown snail shell", (20, 20), ["natura", "piccolo"], ["Snail Shell", "Guscio di Lumaca", "Schneckenhaus", "Concha de Caracol", "Coquille d'Escargot"]),
    ("acorns_oak", "few acorns with an oak leaf, autumn brown", (30, 25), ["natura", "autunno", "piccolo"], ["Acorns", "Ghiande", "Eicheln", "Bellotas", "Glands"]),
    ("walnut_pile", "small pile of whole walnuts", (30, 25), ["cibo", "natura", "piccolo"], ["Walnuts", "Noci", "Walnüsse", "Nueces", "Noix"]),
    ("apple_red_old", "single red apple with a leaf", (25, 25), ["cibo", "natura", "piccolo"], ["Red Apple", "Mela Rossa", "Roter Apfel", "Manzana Roja", "Pomme Rouge"]),
    ("onion_braid", "braid of dried red onions", (30, 65), ["cibo", "cucina", "medio"], ["Onion Braid", "Treccia di Cipolle", "Zwiebelzopf", "Ristra de Cebollas", "Tresse d'Oignons"]),
    ("cheese_wheel_small", "small round wheel of aged cheese with a cut wedge", (45, 30), ["cibo", "cucina", "medio"], ["Cheese Wheel", "Forma di Formaggio", "Käselaib", "Rueda de Queso", "Meule de Fromage"]),
    ("dried_herb_bundle", "small bundle of dried brown herbs tied with string", (25, 50), ["natura", "cucina", "piccolo"], ["Dried Herbs", "Mazzetto di Erbe Secche", "Getrocknete Kräuter", "Hierbas Secas", "Herbes Séchées"]),
    ("jam_jar_cloth", "glass jar of red jam with a checked cloth lid", (30, 40), ["vetro", "cibo", "cucina", "piccolo"], ["Jam Jar", "Barattolo di Marmellata", "Marmeladenglas", "Tarro de Mermelada", "Pot de Confiture"]),
    ("pickle_jar", "old glass jar of pickled vegetables with a metal lid", (30, 45), ["vetro", "cibo", "cucina", "piccolo"], ["Pickle Jar", "Barattolo di Sottaceti", "Einmachglas", "Tarro de Encurtidos", "Bocal de Cornichons"]),
    ("olive_oil_can", "old tin olive oil can with a spout, faded", (35, 45), ["metallo", "cibo", "contenitore", "vintage", "medio"], ["Oil Tin", "Latta d'Olio", "Ölkanister", "Lata de Aceite", "Bidon d'Huile"]),
    ("grain_scoop", "old wooden grain scoop", (40, 25), ["legno", "cucina", "antico", "piccolo"], ["Grain Scoop", "Sessola", "Mehlschaufel", "Pala de Grano", "Pelle à Grain"]),
    ("potato_masher", "old wooden and iron potato masher", (20, 50), ["legno", "ferro", "cucina", "vintage", "piccolo"], ["Potato Masher", "Schiacciapatate", "Kartoffelstampfer", "Pisapapas", "Presse-purée"]),
    ("whisk_wire", "old wire balloon whisk with a wooden handle", (20, 50), ["metallo", "legno", "cucina", "vintage", "piccolo"], ["Whisk", "Frusta", "Schneebesen", "Batidor", "Fouet"]),
    ("tin_colander", "old enamel colander with handles", (50, 30), ["metallo", "cucina", "vintage", "medio"], ["Colander", "Colino", "Sieb", "Colador", "Passoire"]),
    ("meat_grinder", "old cast iron hand crank meat grinder", (40, 45), ["ferro", "cucina", "antico", "medio"], ["Meat Grinder", "Tritacarne", "Fleischwolf", "Picadora de Carne", "Hachoir"]),
    ("waffle_iron", "old cast iron waffle iron with long handles, closed", (70, 25), ["ferro", "cucina", "antico", "medio"], ["Waffle Iron", "Ferro per Cialde", "Waffeleisen", "Gofrera", "Gaufrier"]),
    ("cake_tin_round", "old round tin cake mold with a fluted edge", (40, 25), ["metallo", "cucina", "vintage", "piccolo"], ["Cake Mold", "Stampo per Dolci", "Kuchenform", "Molde de Pastel", "Moule à Gâteau"]),
    ("teaspoon_set", "few old tarnished silver teaspoons", (35, 25), ["argento", "cucina", "vintage", "piccolo"], ["Teaspoons", "Cucchiaini", "Teelöffel", "Cucharillas", "Petites Cuillères"]),
    ("gravy_boat", "old white porcelain gravy boat with a saucer", (40, 25), ["ceramica", "cucina", "vintage", "piccolo"], ["Gravy Boat", "Salsiera", "Sauciere", "Salsera", "Saucière"]),
    ("cheese_grater_box", "old tin box cheese grater", (25, 40), ["metallo", "cucina", "vintage", "piccolo"], ["Box Grater", "Grattugia", "Reibe", "Rallador", "Râpe"]),
    ("butter_dish", "old porcelain butter dish with a lid", (40, 25), ["ceramica", "cucina", "vintage", "piccolo"], ["Butter Dish", "Burriera", "Butterdose", "Mantequera", "Beurrier"]),
    ("egg_cup", "old porcelain egg cup with a boiled egg", (20, 25), ["ceramica", "cucina", "cibo", "vintage", "piccolo"], ["Egg Cup", "Portauovo", "Eierbecher", "Huevera", "Coquetier"]),
    # workshop and trades
    ("cobbler_last", "old iron cobbler shoe last stand", (40, 45), ["ferro", "attrezzo", "antico", "medio"], ["Cobbler's Last", "Forma da Calzolaio", "Schusterleisten", "Horma de Zapatero", "Pied de Cordonnier"]),
    ("awl_tool", "old wooden handled leather awl", (12, 45), ["metallo", "legno", "attrezzo", "vintage", "piccolo"], ["Awl", "Lesina", "Ahle", "Lezna", "Alêne"]),
    ("leather_offcuts", "few old brown leather offcuts", (40, 30), ["cuoio", "attrezzo", "piccolo"], ["Leather Scraps", "Ritagli di Cuoio", "Lederreste", "Retales de Cuero", "Chutes de Cuir"]),
    ("anvil_small", "small old iron jeweller anvil", (40, 30), ["ferro", "attrezzo", "antico", "medio"], ["Small Anvil", "Incudine", "Kleiner Amboss", "Yunque", "Enclume"]),
    ("blacksmith_tongs", "old blacksmith tongs, black iron", (20, 70), ["ferro", "attrezzo", "antico", "medio"], ["Forge Tongs", "Tenaglie da Fabbro", "Schmiedezange", "Tenazas de Herrero", "Pinces de Forgeron"]),
    ("hand_bellows_forge", "old wooden forge bellows with leather", (45, 60), ["legno", "cuoio", "attrezzo", "antico", "medio"], ["Forge Bellows", "Mantice da Forgia", "Schmiedeblasebalg", "Fuelle de Fragua", "Soufflet de Forge"]),
    ("carpenter_pencil", "old flat carpenter pencil", (50, 10), ["legno", "attrezzo", "piccolo"], ["Carpenter's Pencil", "Matita da Falegname", "Zimmermannsbleistift", "Lápiz de Carpintero", "Crayon de Charpentier"]),
    ("wood_clamp", "old wooden hand screw clamp", (50, 30), ["legno", "attrezzo", "antico", "medio"], ["Wood Clamp", "Morsetto di Legno", "Holzzwinge", "Sargento de Madera", "Serre-joint en Bois"]),
    ("bit_brace_bits", "few old auger drill bits", (40, 30), ["metallo", "attrezzo", "vintage", "piccolo"], ["Drill Bits", "Punte da Trapano", "Bohrer", "Brocas", "Mèches"]),
    ("glue_pot", "old iron hide glue pot with a brush", (30, 35), ["ferro", "attrezzo", "antico", "piccolo"], ["Glue Pot", "Pentolino della Colla", "Leimtopf", "Cola de Carpintero", "Pot à Colle"]),
    ("paint_can_old", "old dented paint tin with drips", (30, 35), ["metallo", "attrezzo", "vintage", "piccolo"], ["Paint Tin", "Barattolo di Vernice", "Farbdose", "Lata de Pintura", "Pot de Peinture"]),
    ("paint_palette", "old wooden artist palette with dried paint", (50, 40), ["legno", "arte", "vintage", "medio"], ["Paint Palette", "Tavolozza", "Palette", "Paleta de Pintor", "Palette"]),
    ("paint_brushes_jar", "old glass jar with paint brushes", (25, 50), ["vetro", "legno", "arte", "vintage", "piccolo"], ["Brushes in a Jar", "Pennelli nel Barattolo", "Pinselglas", "Pinceles en Tarro", "Pinceaux en Bocal"]),
    ("sculptor_chisel_mallet", "old round sculptor mallet", (30, 45), ["legno", "arte", "attrezzo", "vintage", "piccolo"], ["Sculptor's Mallet", "Mazzuolo da Scultore", "Bildhauerknüpfel", "Mazo de Escultor", "Maillet de Sculpteur"]),
    ("clay_bust_small", "small unfinished clay sculpture bust, no face details", (30, 45), ["ceramica", "arte", "piccolo"], ["Clay Bust", "Busto d'Argilla", "Tonbüste", "Busto de Arcilla", "Buste en Argile"]),
    ("easel_small", "small old wooden table easel", (35, 50), ["legno", "arte", "vintage", "medio"], ["Table Easel", "Cavalletto da Tavolo", "Tischstaffelei", "Caballete de Mesa", "Chevalet de Table"]),
    ("charcoal_sticks", "few sticks of drawing charcoal on a paper", (35, 20), ["arte", "piccolo"], ["Drawing Charcoal", "Carboncini", "Zeichenkohle", "Carboncillos", "Fusains"]),
    # study and science
    ("brass_microscope_old", "old small brass microscope", (30, 55), ["ottone", "vetro", "studio", "antico", "medio"], ["Brass Microscope", "Microscopio d'Ottone", "Messingmikroskop", "Microscopio de Latón", "Microscope en Laiton"]),
    ("test_tube_rack", "old wooden rack with glass test tubes", (45, 35), ["legno", "vetro", "studio", "vintage", "medio"], ["Test Tubes", "Provette", "Reagenzgläser", "Tubos de Ensayo", "Tubes à Essai"]),
    ("alcohol_burner", "old glass spirit burner with a wick", (25, 30), ["vetro", "studio", "vintage", "piccolo"], ["Spirit Burner", "Fornellino ad Alcol", "Spiritusbrenner", "Mechero de Alcohol", "Lampe à Alcool"]),
    ("specimen_jar", "old glass specimen jar with a cork, empty with a faded blank label", (25, 40), ["vetro", "studio", "vintage", "piccolo"], ["Specimen Jar", "Vaso per Campioni", "Präparateglas", "Frasco de Muestras", "Bocal à Spécimens"]),
    ("mineral_collection", "old small wooden tray with mineral samples", (50, 35), ["legno", "natura", "studio", "vintage", "medio"], ["Mineral Samples", "Collezione di Minerali", "Mineraliensammlung", "Colección de Minerales", "Collection de Minéraux"]),
    ("anatomical_skull_model", "old plaster anatomical skull model, cream colour", (30, 35), ["ceramica", "studio", "medicina", "vintage", "piccolo"], ["Skull Model", "Modello di Teschio", "Schädelmodell", "Modelo de Cráneo", "Modèle de Crâne"]),
    ("sundial_small", "small old brass pocket sundial", (30, 30), ["ottone", "studio", "antico", "piccolo"], ["Pocket Sundial", "Meridiana Tascabile", "Taschensonnenuhr", "Reloj de Sol", "Cadran Solaire"]),
    ("armillary_sphere", "small old brass armillary sphere on a stand", (35, 45), ["ottone", "studio", "antico", "medio"], ["Armillary Sphere", "Sfera Armillare", "Armillarsphäre", "Esfera Armilar", "Sphère Armillaire"]),
    ("prism_glass", "old triangular glass prism", (35, 20), ["vetro", "studio", "piccolo"], ["Glass Prism", "Prisma di Vetro", "Glasprisma", "Prisma de Vidrio", "Prisme"]),
    ("tuning_bell_jar", "old glass bell jar dome, empty, on a wooden base", (35, 50), ["vetro", "legno", "studio", "antico", "medio"], ["Bell Jar", "Campana di Vetro", "Glasglocke", "Campana de Vidrio", "Cloche en Verre"]),
    ("chalk_box", "old small box of white school chalk", (35, 20), ["carta", "studio", "vintage", "piccolo"], ["Chalk Box", "Scatola di Gessetti", "Kreideschachtel", "Caja de Tizas", "Boîte de Craies"]),
    ("school_ruler_wood", "old wooden school ruler", (70, 10), ["legno", "studio", "vintage", "piccolo"], ["Wooden Ruler", "Righello di Legno", "Holzlineal", "Regla de Madera", "Règle en Bois"]),
    ("pencil_case_wooden", "old sliding wooden pencil case", (50, 15), ["legno", "studio", "vintage", "piccolo"], ["Pencil Case", "Astuccio di Legno", "Federkasten", "Estuche de Madera", "Plumier"]),
    ("school_bell_hand", "old brass school hand bell with a black wooden handle", (25, 45), ["ottone", "legno", "studio", "vintage", "piccolo"], ["School Bell", "Campanella della Scuola", "Schulglocke", "Campana Escolar", "Cloche d'École"]),
    ("reading_stand", "small old wooden book reading stand", (40, 40), ["legno", "libro", "studio", "vintage", "medio"], ["Book Stand", "Leggio", "Lesepult", "Atril", "Lutrin"]),
    ("bookends_brass", "pair of old brass bookends", (40, 30), ["ottone", "libro", "arredamento", "vintage", "piccolo"], ["Bookends", "Fermalibri", "Buchstützen", "Sujetalibros", "Serre-livres"]),
    ("dictionary_thick", "old very thick closed dictionary, worn spine", (35, 45), ["carta", "libro", "studio", "vintage", "medio"], ["Dictionary", "Dizionario", "Wörterbuch", "Diccionario", "Dictionnaire"]),
    # personal
    ("pocket_mirror_round", "small old round pocket mirror", (20, 20), ["metallo", "vetro", "bellezza", "vintage", "piccolo"], ["Pocket Mirror", "Specchietto Tascabile", "Taschenspiegel", "Espejito", "Miroir de Poche"]),
    ("hair_curlers", "few old metal hair curlers", (35, 25), ["metallo", "bellezza", "vintage", "piccolo"], ["Hair Curlers", "Bigodini", "Lockenwickler", "Rulos", "Bigoudis"]),
    ("cologne_bottle", "old glass cologne bottle, no label text", (20, 45), ["vetro", "bellezza", "vintage", "piccolo"], ["Cologne Bottle", "Flacone di Colonia", "Kölnischwasserflasche", "Frasco de Colonia", "Flacon d'Eau de Cologne"]),
    ("manicure_set", "old leather manicure case open with tools", (40, 30), ["cuoio", "metallo", "bellezza", "vintage", "piccolo"], ["Manicure Set", "Set da Manicure", "Maniküreset", "Estuche de Manicura", "Nécessaire de Manucure"]),
    ("pocket_watch_stand", "old small wooden pocket watch display stand, empty", (25, 35), ["legno", "arredamento", "vintage", "piccolo"], ["Watch Stand", "Portaorologio", "Uhrenständer", "Soporte de Reloj", "Porte-montre"]),
    ("jewelry_box_velvet", "old small wooden jewellery box with red velvet lining, open", (45, 30), ["legno", "stoffa", "contenitore", "vintage", "medio"], ["Jewellery Box", "Portagioie", "Schmuckkästchen", "Joyero", "Boîte à Bijoux"]),
    ("silver_locket", "old silver locket on a chain, closed", (20, 30), ["argento", "accessorio", "antico", "piccolo"], ["Locket", "Medaglione", "Medaillon", "Guardapelo", "Médaillon"]),
    ("pocket_knife_bone", "old small folding knife with a bone handle, closed", (40, 12), ["osso", "metallo", "attrezzo", "vintage", "piccolo"], ["Folding Knife", "Temperino d'Osso", "Klappmesser", "Navaja de Hueso", "Couteau Pliant"]),
    ("keyring_old", "old iron ring with three small keys", (30, 30), ["ferro", "chiave", "vintage", "piccolo"], ["Key Ring", "Mazzo di Chiavi", "Schlüsselbund", "Llavero", "Trousseau de Clés"]),
    ("wristwatch_leather", "old wristwatch with a worn leather strap", (25, 50), ["cuoio", "metallo", "accessorio", "vintage", "piccolo"], ["Wristwatch", "Orologio da Polso", "Armbanduhr", "Reloj de Pulsera", "Montre-bracelet"]),
    ("reading_glasses_case", "old folded reading glasses on a leather case", (40, 20), ["cuoio", "vetro", "accessorio", "vintage", "piccolo"], ["Reading Glasses", "Occhiali da Lettura", "Lesebrille", "Gafas de Lectura", "Lunettes de Lecture"]),
    ("hand_fan_feather", "old black feather hand fan", (45, 40), ["accessorio", "vintage", "medio"], ["Feather Fan", "Ventaglio di Piume", "Federfächer", "Abanico de Plumas", "Éventail en Plumes"]),
    ("lace_gloves", "pair of old white lace gloves", (40, 35), ["stoffa", "abbigliamento", "vintage", "piccolo"], ["Lace Gloves", "Guanti di Pizzo", "Spitzenhandschuhe", "Guantes de Encaje", "Gants en Dentelle"]),
    ("brooch_flower", "old enamel flower brooch", (25, 25), ["metallo", "accessorio", "vintage", "piccolo"], ["Flower Brooch", "Spilla a Fiore", "Blumenbrosche", "Broche de Flor", "Broche Fleur"]),
    ("beret_wool", "old dark wool beret", (40, 20), ["stoffa", "abbigliamento", "cappello", "vintage", "piccolo"], ["Beret", "Basco", "Baskenmütze", "Boina", "Béret"]),
    ("flat_cap", "old tweed flat cap", (45, 25), ["stoffa", "abbigliamento", "cappello", "vintage", "medio"], ["Flat Cap", "Coppola", "Schiebermütze", "Gorra Plana", "Casquette Plate"]),
    ("waistcoat_folded", "old folded tweed waistcoat", (45, 45), ["stoffa", "abbigliamento", "vintage", "medio"], ["Waistcoat", "Panciotto", "Weste", "Chaleco", "Gilet"]),
    ("neck_tie_striped", "old striped silk neck tie, rolled", (35, 25), ["stoffa", "abbigliamento", "vintage", "piccolo"], ["Neck Tie", "Cravatta a Righe", "Krawatte", "Corbata", "Cravate"]),
    ("handkerchief_folded", "old folded white linen handkerchief with lace edge", (30, 25), ["stoffa", "accessorio", "vintage", "piccolo"], ["Handkerchief", "Fazzoletto", "Taschentuch", "Pañuelo", "Mouchoir"]),
    ("umbrella_folded_red", "old folded dark red umbrella with a wooden handle", (15, 70), ["stoffa", "legno", "accessorio", "vintage", "medio"], ["Red Umbrella", "Ombrello Rosso", "Roter Schirm", "Paraguas Rojo", "Parapluie Rouge"]),
    ("travel_flask_leather", "old leather covered glass travel flask", (25, 40), ["cuoio", "vetro", "bevanda", "vintage", "piccolo"], ["Leather Flask", "Borraccia in Cuoio", "Lederflasche", "Botella de Cuero", "Gourde en Cuir"]),
    ("binocular_case", "old brown leather binocular case with a strap, closed", (40, 35), ["cuoio", "viaggio", "vintage", "medio"], ["Binocular Case", "Custodia del Binocolo", "Fernglasetui", "Funda de Prismáticos", "Étui à Jumelles"]),
    ("tin_toy_car", "old tin toy car, red, chipped paint", (45, 25), ["metallo", "giocattolo", "vintage", "piccolo"], ["Tin Car", "Macchinina di Latta", "Blechauto", "Coche de Hojalata", "Voiture en Fer-blanc"]),
    ("wooden_blocks_toy", "few old painted wooden toy blocks", (40, 30), ["legno", "giocattolo", "vintage", "piccolo"], ["Toy Blocks", "Cubi di Legno", "Holzklötze", "Bloques de Madera", "Cubes en Bois"]),
    ("paper_windmill", "old paper pinwheel on a wooden stick", (30, 55), ["carta", "legno", "giocattolo", "vintage", "piccolo"], ["Pinwheel", "Girandola", "Windrad", "Molinillo", "Moulin à Vent"]),
    ("toy_drum_small", "small old toy drum with sticks", (35, 30), ["legno", "musica", "giocattolo", "vintage", "piccolo"], ["Toy Drum", "Tamburo Giocattolo", "Spielzeugtrommel", "Tambor de Juguete", "Tambour Jouet"]),
    ("puppet_wooden_hand", "old wooden hand puppet head with cloth body, no face paint", (30, 45), ["legno", "stoffa", "giocattolo", "vintage", "piccolo"], ["Hand Puppet", "Burattino", "Handpuppe", "Títere", "Marionnette à Main"]),
    ("skipping_rope", "old skipping rope with wooden handles, coiled", (40, 35), ["legno", "giocattolo", "vintage", "piccolo"], ["Skipping Rope", "Corda per Saltare", "Springseil", "Comba", "Corde à Sauter"]),
    ("board_game_box", "old closed cardboard board game box, faded, no readable text", (50, 35), ["carta", "gioco", "vintage", "medio"], ["Board Game", "Gioco da Tavolo", "Brettspiel", "Juego de Mesa", "Jeu de Société"]),
    ("checkers_pieces", "few old wooden checkers pieces, black and white", (35, 25), ["legno", "gioco", "vintage", "piccolo"], ["Checkers", "Pedine della Dama", "Damesteine", "Fichas de Damas", "Pions de Dames"]),
    ("playing_dice_wood", "pair of old wooden dice", (25, 20), ["legno", "gioco", "vintage", "piccolo"], ["Wooden Dice", "Dadi di Legno", "Holzwürfel", "Dados de Madera", "Dés en Bois"]),
    ("jigsaw_pieces", "few old wooden jigsaw puzzle pieces", (35, 25), ["legno", "gioco", "vintage", "piccolo"], ["Puzzle Pieces", "Tessere di Puzzle", "Puzzleteile", "Piezas de Puzle", "Pièces de Puzzle"]),
    ("toy_boat_wood", "old small wooden toy sailing boat", (40, 40), ["legno", "stoffa", "giocattolo", "vintage", "medio"], ["Toy Boat", "Barchetta di Legno", "Holzboot", "Barco de Juguete", "Bateau Jouet"]),
    ("glass_float_net", "old glass fishing float in a rope net", (30, 30), ["vetro", "decorazione", "vintage", "piccolo"], ["Glass Float", "Galleggiante di Vetro", "Glasschwimmer", "Boya de Vidrio", "Flotteur en Verre"]),
    ("fishing_reel", "old brass and wood fishing reel", (35, 35), ["ottone", "legno", "sport", "vintage", "piccolo"], ["Fishing Reel", "Mulinello", "Angelrolle", "Carrete de Pesca", "Moulinet"]),
    ("fishing_creel", "old wicker fishing creel basket with a strap", (45, 40), ["legno", "cuoio", "sport", "vintage", "medio"], ["Fishing Creel", "Cestino da Pesca", "Fischkorb", "Cesta de Pesca", "Panier de Pêche"]),
    ("tennis_racket_wood", "old wooden tennis racket in a press", (35, 85), ["legno", "sport", "vintage", "grande"], ["Wooden Racket", "Racchetta di Legno", "Holzschläger", "Raqueta de Madera", "Raquette en Bois"]),
    ("leather_football_old", "old brown leather laced football", (35, 35), ["cuoio", "sport", "vintage", "medio"], ["Leather Ball", "Pallone di Cuoio", "Lederball", "Balón de Cuero", "Ballon en Cuir"]),
    ("boxing_gloves_old", "pair of old brown leather boxing gloves", (50, 40), ["cuoio", "sport", "vintage", "medio"], ["Old Boxing Gloves", "Guantoni d'Epoca", "Alte Boxhandschuhe", "Guantes de Boxeo Antiguos", "Vieux Gants de Boxe"]),
    ("bicycle_pump_old", "old brass bicycle hand pump", (15, 60), ["ottone", "sport", "vintage", "piccolo"], ["Bicycle Pump", "Pompa della Bici", "Fahrradpumpe", "Bomba de Bicicleta", "Pompe à Vélo"]),
    ("bicycle_lamp_carbide", "old black bicycle carbide lamp", (30, 35), ["metallo", "luce", "sport", "vintage", "piccolo"], ["Bicycle Lamp", "Fanale della Bici", "Fahrradlampe", "Farol de Bicicleta", "Phare de Vélo"]),
]
DROPPED = set(['garden_trowel', 'bird_nest_eggs', 'apple_red_old', 'cheese_wheel_small', 'olive_oil_can', 'whisk_wire', 'cheese_grater_box', 'paint_palette', 'brass_microscope_old', 'school_ruler_wood', 'bookends_brass', 'dictionary_thick', 'silver_locket', 'wristwatch_leather', 'wooden_blocks_toy', 'tennis_racket_wood', 'leather_football_old', 'boxing_gloves_old', 'keyring_old', 'pruning_shears_old', 'paint_brushes_jar', 'meat_grinder', 'sculptor_chisel_mallet', 'carpenter_pencil', 'playing_dice_wood'])  # exist already (concept check)
C = [r for r in _RAW if r[0] not in DROPPED][:80]
