"""Eighty generic objects of any period and setting, for the global real catalog.
No character, brand, place or readable text; no green objects (chroma key).
"""

_RAW = [
    # modern home
    ("ceramic_coffee_mug_white", "plain white ceramic coffee mug, empty", (30, 30), ["ceramica", "cucina", "bevanda", "piccolo"], ["White Mug", "Tazza Bianca", "Weiße Tasse", "Taza Blanca", "Tasse Blanche"]),
    ("french_press", "glass french press coffee maker with a steel frame", (30, 50), ["vetro", "metallo", "cucina", "bevanda", "medio"], ["French Press", "Caffettiera a Pistone", "French Press", "Cafetera de Émbolo", "Cafetière à Piston"]),
    ("electric_kettle_steel", "modern stainless steel electric kettle", (40, 45), ["metallo", "cucina", "tecnologia", "medio"], ["Electric Kettle", "Bollitore Elettrico", "Wasserkocher", "Hervidor Eléctrico", "Bouilloire Électrique"]),
    ("toaster_chrome", "chrome two slice toaster", (45, 35), ["metallo", "cucina", "tecnologia", "medio"], ["Toaster", "Tostapane", "Toaster", "Tostadora", "Grille-pain"]),
    ("cutting_board_wood", "wooden kitchen cutting board with a handle", (60, 35), ["legno", "cucina", "medio"], ["Cutting Board", "Tagliere", "Schneidebrett", "Tabla de Cortar", "Planche à Découper"]),
    ("chef_whisk_steel", "stainless steel balloon whisk", (20, 50), ["metallo", "cucina", "piccolo"], ["Steel Whisk", "Frusta d'Acciaio", "Edelstahl-Schneebesen", "Batidor de Acero", "Fouet Inox"]),
    ("pepper_mill_wood", "tall wooden pepper mill", (15, 50), ["legno", "cucina", "piccolo"], ["Pepper Mill", "Macinapepe", "Pfeffermühle", "Molinillo de Pimienta", "Moulin à Poivre"]),
    ("oven_mitt_red", "red quilted oven mitt", (35, 45), ["stoffa", "cucina", "piccolo"], ["Oven Mitt", "Presina", "Ofenhandschuh", "Manopla de Cocina", "Gant de Cuisine"]),
    ("measuring_cups", "set of stainless steel measuring cups nested", (40, 25), ["metallo", "cucina", "piccolo"], ["Measuring Cups", "Misurini", "Messbecher", "Tazas Medidoras", "Tasses à Mesurer"]),
    ("glass_water_carafe", "clear glass water carafe, empty", (25, 50), ["vetro", "cucina", "bevanda", "medio"], ["Water Carafe", "Caraffa d'Acqua", "Wasserkaraffe", "Jarra de Agua", "Carafe d'Eau"]),
    ("dish_rack_small", "small metal dish drying rack with two plates", (50, 35), ["metallo", "cucina", "medio"], ["Dish Rack", "Scolapiatti", "Abtropfgestell", "Escurreplatos", "Égouttoir"]),
    ("sponge_kitchen", "yellow kitchen sponge with a scrub side", (25, 15), ["plastica", "cucina", "piccolo"], ["Sponge", "Spugna", "Schwamm", "Esponja", "Éponge"]),
    ("spray_bottle_plastic", "plain white plastic spray bottle, no label", (20, 45), ["plastica", "bagno", "piccolo"], ["Spray Bottle", "Spruzzino", "Sprühflasche", "Pulverizador", "Vaporisateur"]),
    ("toilet_brush", "white toilet brush in its holder", (20, 50), ["plastica", "bagno", "piccolo"], ["Toilet Brush", "Scopino", "Klobürste", "Escobilla", "Brosse WC"]),
    ("bath_towel_folded", "folded white bath towel", (45, 25), ["stoffa", "bagno", "medio"], ["Folded Towel", "Asciugamano Piegato", "Handtuch", "Toalla Doblada", "Serviette Pliée"]),
    ("rubber_bath_mat", "small blue rubber bath mat with suction cups", (55, 35), ["plastica", "bagno", "medio"], ["Bath Mat", "Tappetino da Bagno", "Badematte", "Alfombrilla de Baño", "Tapis de Bain"]),
    ("toothbrush_holder", "ceramic toothbrush holder cup with two toothbrushes", (20, 40), ["ceramica", "bagno", "piccolo"], ["Toothbrush Cup", "Portaspazzolini", "Zahnputzbecher", "Vaso de Cepillos", "Gobelet à Brosses"]),
    ("hand_soap_pump", "plain glass hand soap pump bottle", (15, 35), ["vetro", "bagno", "piccolo"], ["Soap Pump", "Dispenser di Sapone", "Seifenspender", "Dispensador de Jabón", "Distributeur de Savon"]),
    ("desk_plant_cactus", "small cactus in a white ceramic pot", (25, 35), ["ceramica", "natura", "piccolo"], ["Cactus Pot", "Cactus in Vaso", "Kaktus", "Cactus en Maceta", "Cactus en Pot"]),
    ("scented_candle_jar", "scented candle in a glass jar, lit", (25, 30), ["vetro", "luce", "arredamento", "piccolo"], ["Jar Candle", "Candela in Vasetto", "Glaskerze", "Vela en Tarro", "Bougie en Pot"]),
    ("throw_cushion_grey", "grey fabric throw cushion", (45, 45), ["stoffa", "arredamento", "medio"], ["Cushion", "Cuscino Grigio", "Kissen", "Cojín", "Coussin"]),
    ("table_clock_digital", "small black digital alarm clock, screen off", (35, 20), ["plastica", "tecnologia", "piccolo"], ["Digital Clock", "Sveglia Digitale", "Digitalwecker", "Reloj Digital", "Réveil Numérique"]),
    ("tv_remote", "black TV remote control", (15, 45), ["plastica", "tecnologia", "piccolo"], ["TV Remote", "Telecomando", "Fernbedienung", "Mando a Distancia", "Télécommande"]),
    ("power_strip", "white power strip with switch", (60, 15), ["plastica", "tecnologia", "piccolo"], ["Power Strip", "Ciabatta Elettrica", "Steckdosenleiste", "Regleta", "Multiprise"]),
    ("usb_cable_coiled", "coiled white usb charging cable", (35, 30), ["plastica", "tecnologia", "piccolo"], ["USB Cable", "Cavo USB", "USB-Kabel", "Cable USB", "Câble USB"]),
    ("flashlight_black", "black aluminium flashlight torch", (15, 55), ["metallo", "luce", "tecnologia", "piccolo"], ["Flashlight", "Torcia", "Taschenlampe", "Linterna", "Lampe Torche"]),
    ("computer_mouse", "plain black computer mouse", (20, 30), ["plastica", "tecnologia", "piccolo"], ["Computer Mouse", "Mouse", "Computermaus", "Ratón", "Souris"]),
    ("keyboard_compact", "compact black computer keyboard", (70, 25), ["plastica", "tecnologia", "medio"], ["Keyboard", "Tastiera", "Tastatur", "Teclado", "Clavier"]),
    ("webcam_small", "small black webcam on a clip", (25, 25), ["plastica", "tecnologia", "piccolo"], ["Webcam", "Webcam", "Webcam", "Cámara Web", "Webcam"]),
    ("sd_card", "small memory card", (15, 20), ["plastica", "tecnologia", "piccolo"], ["Memory Card", "Scheda di Memoria", "Speicherkarte", "Tarjeta de Memoria", "Carte Mémoire"]),
    ("smartwatch_black", "black smartwatch with a blank screen", (20, 45), ["plastica", "tecnologia", "accessorio", "piccolo"], ["Smartwatch", "Smartwatch", "Smartwatch", "Reloj Inteligente", "Montre Connectée"]),
    ("earbuds_case", "white wireless earbuds charging case, open", (25, 25), ["plastica", "tecnologia", "piccolo"], ["Earbuds", "Auricolari", "Ohrhörer", "Auriculares", "Écouteurs"]),
    ("desk_calculator", "grey desk calculator, display off", (30, 40), ["plastica", "ufficio", "tecnologia", "piccolo"], ["Calculator", "Calcolatrice", "Taschenrechner", "Calculadora", "Calculatrice"]),
    ("sticky_notes_pad", "pad of yellow sticky notes, blank", (25, 25), ["carta", "ufficio", "piccolo"], ["Sticky Notes", "Foglietti Adesivi", "Haftnotizen", "Notas Adhesivas", "Post-it"]),
    ("stapler_black", "black desk stapler", (40, 20), ["metallo", "ufficio", "piccolo"], ["Stapler", "Pinzatrice", "Hefter", "Grapadora", "Agrafeuse"]),
    ("paper_clips_pile", "small pile of silver paper clips", (25, 20), ["metallo", "ufficio", "piccolo"], ["Paper Clips", "Graffette", "Büroklammern", "Clips", "Trombones"]),
    ("binder_clips", "few black binder clips", (30, 20), ["metallo", "ufficio", "piccolo"], ["Binder Clips", "Fermacarte a Molla", "Foldback-Klammern", "Pinzas", "Pinces"]),
    ("highlighter_pens", "three highlighter pens, orange pink blue", (40, 25), ["plastica", "ufficio", "piccolo"], ["Highlighters", "Evidenziatori", "Textmarker", "Rotuladores", "Surligneurs"]),
    ("spiral_notebook", "spiral notebook with a blank grey cover", (35, 45), ["carta", "ufficio", "piccolo"], ["Spiral Notebook", "Quaderno a Spirale", "Spiralblock", "Cuaderno", "Cahier à Spirale"]),
    ("ring_binder_blue", "blue ring binder folder, closed", (40, 50), ["plastica", "ufficio", "medio"], ["Ring Binder", "Raccoglitore", "Ordner", "Carpeta de Anillas", "Classeur"]),
    ("tape_dispenser", "desk tape dispenser with a roll of tape", (35, 20), ["plastica", "ufficio", "piccolo"], ["Tape Dispenser", "Portanastro", "Klebebandabroller", "Portacelo", "Dévidoir"]),
    ("scissors_office", "office scissors with black handles", (20, 45), ["metallo", "plastica", "ufficio", "piccolo"], ["Scissors", "Forbici", "Schere", "Tijeras", "Ciseaux"]),
    # outdoor, travel, sport
    ("water_bottle_steel", "stainless steel insulated water bottle", (15, 50), ["metallo", "bevanda", "sport", "piccolo"], ["Steel Bottle", "Borraccia d'Acciaio", "Edelstahlflasche", "Botella de Acero", "Gourde Inox"]),
    ("backpack_hiking", "blue hiking backpack, closed", (45, 60), ["stoffa", "viaggio", "sport", "medio"], ["Hiking Backpack", "Zaino da Escursione", "Wanderrucksack", "Mochila de Montaña", "Sac de Randonnée"]),
    ("sunglasses_aviator", "aviator sunglasses with gold frame", (40, 15), ["metallo", "vetro", "accessorio", "piccolo"], ["Aviator Sunglasses", "Occhiali da Aviatore", "Pilotenbrille", "Gafas de Aviador", "Lunettes Aviateur"]),
    ("baseball_cap_blue", "plain navy blue baseball cap", (40, 25), ["stoffa", "abbigliamento", "cappello", "piccolo"], ["Baseball Cap", "Cappellino", "Baseballkappe", "Gorra", "Casquette"]),
    ("travel_pillow", "grey neck travel pillow", (40, 35), ["stoffa", "viaggio", "medio"], ["Travel Pillow", "Cuscino da Viaggio", "Nackenkissen", "Almohada de Viaje", "Coussin de Voyage"]),
    ("luggage_lock", "small combination luggage padlock", (20, 25), ["metallo", "viaggio", "sicurezza", "piccolo"], ["Luggage Lock", "Lucchetto a Combinazione", "Kofferschloss", "Candado de Maleta", "Cadenas de Valise"]),
    ("tent_pegs", "few metal tent pegs", (35, 25), ["metallo", "attrezzatura", "piccolo"], ["Tent Pegs", "Picchetti", "Heringe", "Piquetas", "Sardines"]),
    ("camping_mug_enamel", "blue enamel camping mug", (30, 25), ["metallo", "bevanda", "attrezzatura", "piccolo"], ["Camp Mug", "Tazza da Campeggio", "Campingbecher", "Taza de Camping", "Tasse de Camping"]),
    ("headlamp_modern", "modern LED headlamp with an elastic band", (35, 30), ["plastica", "luce", "attrezzatura", "piccolo"], ["LED Headlamp", "Lampada Frontale", "Stirnlampe", "Linterna Frontal", "Lampe Frontale"]),
    ("carabiner_orange", "orange climbing carabiner", (20, 35), ["metallo", "sport", "attrezzatura", "piccolo"], ["Carabiner", "Moschettone", "Karabiner", "Mosquetón", "Mousqueton"]),
    ("swim_goggles", "swimming goggles with a blue strap", (35, 20), ["plastica", "sport", "piccolo"], ["Swim Goggles", "Occhialini da Nuoto", "Schwimmbrille", "Gafas de Natación", "Lunettes de Natation"]),
    ("tennis_ball", "single yellow tennis ball", (20, 20), ["sport", "piccolo"], ["Tennis Ball", "Pallina da Tennis", "Tennisball", "Pelota de Tenis", "Balle de Tennis"]),
    ("badminton_shuttlecock", "white feather badminton shuttlecock", (20, 30), ["sport", "piccolo"], ["Shuttlecock", "Volano", "Federball", "Volante", "Volant"]),
    ("skateboard", "plain wooden skateboard with wheels", (80, 25), ["legno", "sport", "grande"], ["Skateboard", "Skateboard", "Skateboard", "Monopatín", "Skateboard"]),
    ("jump_rope_plastic", "modern jump rope with foam handles, coiled", (40, 35), ["plastica", "sport", "piccolo"], ["Jump Rope", "Corda da Salto", "Springseil", "Cuerda de Saltar", "Corde à Sauter"]),
    ("dumbbell_small", "small hexagonal dumbbell", (35, 20), ["ferro", "sport", "piccolo"], ["Dumbbell", "Manubrio", "Hantel", "Mancuerna", "Haltère"]),
    ("yoga_block", "purple foam yoga block", (35, 25), ["plastica", "sport", "piccolo"], ["Yoga Block", "Mattoncino Yoga", "Yogablock", "Bloque de Yoga", "Brique de Yoga"]),
    ("stopwatch_digital_sport", "digital sport stopwatch on a lanyard", (25, 35), ["plastica", "sport", "tecnologia", "piccolo"], ["Sport Stopwatch", "Cronometro Sportivo", "Sportstoppuhr", "Cronómetro", "Chronomètre"]),
    # fantasy, mystery, curiosity
    ("crystal_ball_stand", "clear crystal ball on a brass stand", (30, 40), ["vetro", "ottone", "occulto", "piccolo"], ["Crystal Ball", "Sfera di Cristallo", "Kristallkugel", "Bola de Cristal", "Boule de Cristal"]),
    ("tarot_card_single", "single face down ornate tarot card", (25, 40), ["carta", "occulto", "piccolo"], ["Tarot Card", "Carta dei Tarocchi", "Tarotkarte", "Carta de Tarot", "Carte de Tarot"]),
    ("potion_bottle_purple", "small round glass potion bottle with purple liquid and a cork", (20, 35), ["vetro", "occulto", "piccolo"], ["Potion Bottle", "Ampolla di Pozione", "Trankflasche", "Frasco de Poción", "Fiole de Potion"]),
    ("ancient_scroll_sealed", "rolled parchment scroll with a red wax seal", (55, 20), ["carta", "antico", "piccolo"], ["Sealed Scroll", "Pergamena Sigillata", "Versiegelte Schriftrolle", "Pergamino Sellado", "Parchemin Scellé"]),
    ("rune_stone", "small grey stone with a carved rune symbol", (25, 25), ["natura", "occulto", "piccolo"], ["Rune Stone", "Pietra Runica", "Runenstein", "Piedra Rúnica", "Pierre Runique"]),
    ("dragon_egg_stone", "large scaly stone egg, dark bronze", (30, 40), ["natura", "occulto", "piccolo"], ["Dragon Egg", "Uovo di Drago", "Drachenei", "Huevo de Dragón", "Œuf de Dragon"]),
    ("golden_goblet_jewels", "ornate golden goblet with red gems", (25, 45), ["metallo", "antico", "piccolo"], ["Jewelled Goblet", "Calice Ingioiellato", "Juwelenkelch", "Copa Enjoyada", "Coupe Ornée"]),
    ("treasure_coins_pile", "small pile of gold coins", (30, 20), ["metallo", "antico", "piccolo"], ["Gold Coins", "Monete d'Oro", "Goldmünzen", "Monedas de Oro", "Pièces d'Or"]),
    ("magic_wand_wooden", "twisted wooden magic wand", (60, 10), ["legno", "occulto", "piccolo"], ["Wooden Wand", "Bacchetta di Legno", "Holzstab", "Varita de Madera", "Baguette en Bois"]),
    ("ritual_dagger", "ornate ceremonial dagger with a curved blade", (15, 55), ["metallo", "arma", "occulto", "piccolo"], ["Ritual Dagger", "Pugnale Rituale", "Ritualdolch", "Daga Ritual", "Dague Rituelle"]),
    ("hourglass_black_sand", "ornate brass hourglass with black sand", (25, 45), ["ottone", "vetro", "occulto", "piccolo"], ["Black Hourglass", "Clessidra Nera", "Schwarze Sanduhr", "Reloj de Arena Negro", "Sablier Noir"]),
    ("amulet_moon", "silver moon amulet on a chain", (25, 35), ["argento", "accessorio", "occulto", "piccolo"], ["Moon Amulet", "Amuleto Lunare", "Mondamulett", "Amuleto Lunar", "Amulette Lune"]),
    ("wax_voodoo_candle", "black wax candle with drips", (15, 40), ["luce", "occulto", "horror", "piccolo"], ["Black Candle", "Candela Nera", "Schwarze Kerze", "Vela Negra", "Bougie Noire"]),
    ("bone_key", "old key carved from bone", (12, 40), ["osso", "chiave", "horror", "piccolo"], ["Bone Key", "Chiave d'Osso", "Knochenschlüssel", "Llave de Hueso", "Clé en Os"]),
    ("raven_skull", "small raven skull, bleached", (30, 20), ["osso", "horror", "piccolo"], ["Raven Skull", "Teschio di Corvo", "Rabenschädel", "Cráneo de Cuervo", "Crâne de Corbeau"]),
    ("spell_book_chained", "old thick book bound with an iron chain and lock", (40, 50), ["cuoio", "ferro", "libro", "occulto", "medio"], ["Chained Book", "Libro Incatenato", "Angekettetes Buch", "Libro Encadenado", "Livre Enchaîné"]),
    ("alchemy_flask_round", "round bottomed alchemy flask with blue liquid", (25, 40), ["vetro", "alchimia", "piccolo"], ["Alchemy Flask", "Ampolla Alchemica", "Alchemistenkolben", "Matraz Alquímico", "Fiole d'Alchimiste"]),
    ("gemstone_ruby", "single large cut ruby gemstone", (20, 20), ["accessorio", "piccolo"], ["Ruby", "Rubino", "Rubin", "Rubí", "Rubis"]),
    ("gemstone_sapphire", "single large cut blue sapphire gemstone", (20, 20), ["accessorio", "piccolo"], ["Sapphire", "Zaffiro", "Saphir", "Zafiro", "Saphir"]),
    ("pirate_compass_brass", "ornate brass compass with a broken glass", (30, 30), ["ottone", "vetro", "viaggio", "antico", "piccolo"], ["Broken Compass", "Bussola Rotta", "Kaputter Kompass", "Brújula Rota", "Boussole Cassée"]),
    ("message_in_bottle", "glass bottle with a rolled paper message inside, cork", (45, 20), ["vetro", "carta", "viaggio", "piccolo"], ["Bottle Message", "Messaggio in Bottiglia", "Flaschenpost", "Mensaje en Botella", "Bouteille à la Mer"]),
    ("sea_star_dried", "dried orange starfish", (35, 35), ["natura", "piccolo"], ["Starfish", "Stella Marina", "Seestern", "Estrella de Mar", "Étoile de Mer"]),
    ("conch_shell_pink", "large pink conch shell", (40, 30), ["natura", "piccolo"], ["Conch Shell", "Conchiglia", "Muschel", "Caracola", "Conque"]),
    ("sand_dollar", "white sand dollar sea urchin shell", (25, 25), ["natura", "piccolo"], ["Sand Dollar", "Dollaro di Sabbia", "Sanddollar", "Dólar de Arena", "Dollar des Sables"]),
    ("driftwood_piece", "piece of bleached driftwood", (60, 20), ["legno", "natura", "medio"], ["Driftwood", "Legno di Mare", "Treibholz", "Madera a la Deriva", "Bois Flotté"]),
    ("anchor_small_rusty", "small rusty boat anchor", (35, 45), ["ferro", "viaggio", "vintage", "medio"], ["Rusty Anchor", "Ancora Arrugginita", "Rostiger Anker", "Ancla Oxidada", "Ancre Rouillée"]),
    ("ship_lantern_brass", "brass ship lantern with glass", (30, 50), ["ottone", "vetro", "luce", "viaggio", "vintage", "medio"], ["Ship Lantern", "Lanterna da Nave", "Schiffslaterne", "Farol de Barco", "Lanterne de Navire"]),
    # second round, areas the catalog lacks
    ("ukulele", "small wooden ukulele", (30, 70), ["legno", "musica", "medio"], ["Ukulele", "Ukulele", "Ukulele", "Ukelele", "Ukulélé"]),
    ("maracas_pair", "pair of painted wooden maracas", (40, 45), ["legno", "musica", "piccolo"], ["Maracas", "Maracas", "Rasseln", "Maracas", "Maracas"]),
    ("xylophone_toy", "small toy xylophone with coloured bars and two mallets", (55, 30), ["legno", "metallo", "musica", "giocattolo", "medio"], ["Xylophone", "Xilofono", "Xylophon", "Xilófono", "Xylophone"]),
    ("adhesive_bandage_box", "small box of adhesive bandages, open, no text", (35, 25), ["carta", "medicina", "piccolo"], ["Bandages", "Cerotti", "Pflaster", "Tiritas", "Pansements"]),
    ("pill_bottle_orange", "orange plastic pill bottle with white cap, no label text", (20, 35), ["plastica", "medicina", "piccolo"], ["Pill Bottle", "Flacone di Pillole", "Pillendose", "Frasco de Pastillas", "Flacon de Pilules"]),
    ("gauze_roll", "roll of white gauze bandage", (25, 25), ["stoffa", "medicina", "piccolo"], ["Gauze Roll", "Rotolo di Garza", "Mullbinde", "Rollo de Gasa", "Rouleau de Gaze"]),
    ("spark_plug", "single automotive spark plug", (15, 40), ["metallo", "ceramica", "auto", "piccolo"], ["Spark Plug", "Candela d'Accensione", "Zündkerze", "Bujía", "Bougie d'Allumage"]),
    ("socket_wrench", "chrome socket wrench ratchet", (55, 15), ["metallo", "attrezzo", "piccolo"], ["Socket Wrench", "Chiave a Cricchetto", "Ratsche", "Llave de Carraca", "Clé à Cliquet"]),
    ("oil_filter", "car engine oil filter, blue", (30, 35), ["metallo", "auto", "piccolo"], ["Oil Filter", "Filtro dell'Olio", "Ölfilter", "Filtro de Aceite", "Filtre à Huile"]),
    ("tire_pressure_gauge", "small metal tire pressure gauge", (40, 15), ["metallo", "auto", "attrezzo", "piccolo"], ["Tire Gauge", "Manometro per Gomme", "Reifendruckprüfer", "Manómetro de Neumáticos", "Manomètre de Pneu"]),
    ("battery_9v", "single 9 volt battery, no brand", (15, 25), ["metallo", "tecnologia", "piccolo"], ["9V Battery", "Batteria da 9 Volt", "9-Volt-Batterie", "Pila de 9 V", "Pile 9 V"]),
    ("origami_crane", "white paper origami crane", (35, 30), ["carta", "arte", "piccolo"], ["Origami Crane", "Gru di Carta", "Papierkranich", "Grulla de Papel", "Grue en Papier"]),
    ("crayons_box", "box of wax crayons, open", (40, 25), ["arte", "piccolo"], ["Crayons", "Pastelli a Cera", "Wachsmalstifte", "Ceras", "Crayons de Cire"]),
    ("glue_bottle", "white school glue bottle, no label text", (15, 35), ["plastica", "ufficio", "piccolo"], ["Glue Bottle", "Flacone di Colla", "Klebstoff", "Bote de Pegamento", "Flacon de Colle"]),
    ("modelling_clay", "few coloured blocks of modelling clay", (35, 25), ["arte", "giocattolo", "piccolo"], ["Modelling Clay", "Plastilina", "Knete", "Plastilina", "Pâte à Modeler"]),
    ("honeycomb_piece", "piece of golden honeycomb", (35, 25), ["cibo", "natura", "piccolo"], ["Honeycomb", "Favo di Miele", "Honigwabe", "Panal", "Rayon de Miel"]),
    ("river_rocks", "few smooth grey river pebbles", (35, 25), ["natura", "piccolo"], ["River Stones", "Ciottoli", "Flusskiesel", "Guijarros", "Galets"]),
    ("autumn_leaves", "few dry orange autumn leaves", (35, 30), ["natura", "autunno", "piccolo"], ["Autumn Leaves", "Foglie Secche", "Herbstlaub", "Hojas Secas", "Feuilles Mortes"]),
    ("chess_set_pieces", "few classic black and white chess pieces", (40, 35), ["legno", "gioco", "piccolo"], ["Chess Pieces", "Pezzi degli Scacchi", "Schachfiguren", "Piezas de Ajedrez", "Pièces d'Échecs"]),
    ("coin_purse_red", "small red leather coin purse with a kiss clasp", (30, 25), ["cuoio", "accessorio", "piccolo"], ["Coin Purse", "Portamonete", "Münzbörse", "Monedero", "Porte-monnaie"]),
    ("raincoat_yellow", "folded yellow rain coat", (45, 40), ["plastica", "abbigliamento", "medio"], ["Raincoat", "Impermeabile", "Regenmantel", "Chubasquero", "Imperméable"]),
    ("rubber_boots", "pair of black rubber rain boots", (45, 50), ["plastica", "abbigliamento", "medio"], ["Rain Boots", "Stivali di Gomma", "Gummistiefel", "Botas de Agua", "Bottes en Caoutchouc"]),
    ("knitted_scarf_striped", "striped knitted wool scarf, rolled", (40, 30), ["stoffa", "abbigliamento", "piccolo"], ["Striped Scarf", "Sciarpa a Righe", "Gestreifter Schal", "Bufanda a Rayas", "Écharpe Rayée"]),
    ("wool_socks", "pair of thick grey wool socks", (40, 30), ["stoffa", "abbigliamento", "piccolo"], ["Wool Socks", "Calzettoni di Lana", "Wollsocken", "Calcetines de Lana", "Chaussettes en Laine"]),
    ("protractor_plastic", "clear plastic protractor", (40, 25), ["plastica", "studio", "piccolo"], ["Protractor", "Goniometro", "Winkelmesser", "Transportador", "Rapporteur"]),
    ("fridge_magnets", "few colourful fridge magnets", (35, 25), ["plastica", "cucina", "piccolo"], ["Fridge Magnets", "Calamite da Frigo", "Kühlschrankmagnete", "Imanes", "Magnets"]),
    ("paper_kite", "diamond paper kite with a tail", (45, 60), ["carta", "giocattolo", "medio"], ["Kite", "Aquilone", "Drachen", "Cometa", "Cerf-volant"]),
    ("party_balloon_red", "single red party balloon with a string", (30, 55), ["plastica", "giocattolo", "piccolo"], ["Balloon", "Palloncino", "Luftballon", "Globo", "Ballon"]),
    ("frisbee_disc", "plain orange frisbee disc", (40, 15), ["plastica", "sport", "piccolo"], ["Frisbee", "Frisbee", "Frisbee", "Disco Volador", "Frisbee"]),
    ("dart_set", "three darts with feathered flights", (40, 25), ["metallo", "gioco", "sport", "piccolo"], ["Darts", "Freccette", "Dartpfeile", "Dardos", "Fléchettes"]),
    ("snorkel_mask", "snorkel diving mask with a tube", (45, 35), ["plastica", "vetro", "sport", "medio"], ["Snorkel Mask", "Maschera da Snorkeling", "Schnorchelmaske", "Máscara de Buceo", "Masque de Plongée"]),
    ("swim_fins", "pair of black swimming fins", (45, 65), ["plastica", "sport", "medio"], ["Swim Fins", "Pinne", "Schwimmflossen", "Aletas", "Palmes"]),
    ("lunch_box_metal", "rectangular metal lunch box with a handle, plain", (45, 35), ["metallo", "contenitore", "cibo", "piccolo"], ["Lunch Box", "Portapranzo", "Brotdose", "Fiambrera", "Boîte à Repas"]),
    ("bento_box", "black lacquer bento box with sections, empty", (45, 30), ["plastica", "contenitore", "cibo", "piccolo"], ["Bento Box", "Bento", "Bentobox", "Caja Bento", "Boîte Bento"]),
    ("ice_cube_tray", "blue plastic ice cube tray", (50, 20), ["plastica", "cucina", "piccolo"], ["Ice Tray", "Vaschetta del Ghiaccio", "Eiswürfelform", "Cubitera", "Bac à Glaçons"]),
]

DROPPED = set(['ceramic_coffee_mug_white', 'toaster_chrome', 'chef_whisk_steel', 'sponge_kitchen', 'spray_bottle_plastic', 'toothbrush_holder', 'tv_remote', 'flashlight_black', 'computer_mouse', 'keyboard_compact', 'webcam_small', 'smartwatch_black', 'desk_calculator', 'highlighter_pens', 'water_bottle_steel', 'backpack_hiking', 'sunglasses_aviator', 'baseball_cap_blue', 'headlamp_modern', 'carabiner_orange', 'skateboard', 'jump_rope_plastic', 'tarot_card_single', 'potion_bottle_purple', 'ancient_scroll_sealed', 'dragon_egg_stone', 'magic_wand_wooden', 'ritual_dagger', 'hourglass_black_sand', 'message_in_bottle', 'pirate_compass_brass'])  # already in real style
C = [r for r in _RAW if r[0] not in DROPPED][:80]
